### ISSUE TITLE
papis add has permission issues

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#100]
`papis add` is causing permission issues when reading from `/tmp/`. 

https://github.com/papis/papis/blob/aeddcaf857488d37bb10de13da23dbf63b19c707/papis/commands/add.py#L160

Asks to open in binary read **and write** mode, when that isn't necessary.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError), https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn), https://github.com/papis/papis/issues/41 (Webapplication for papis), https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion), and https://github.com/papis/papis/issues/92 (papis-python-rofi).
