### ISSUE TITLE
automatically invalidate cache

### ISSUE THREAD

**Issue by bluehood** [papis/papis#103]
My papis library is a git repo, that I synchronize between laptop and workstation. I use papis on both.
Everytime I do a `git pull` and I try to use papis, I realize the cache is stale and still lists old entries (and more importantly does not list new entries), so I have to delete the cache manually.

I know that in general cache invalidation is one of the unsolved problems of computer science, but it might be doable in this case :smile: For example a check of the timestamp of the last modified document in the papis library would be a good indicator of a possible cache invalidation.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @alejandrogallo, and @kskyten.

A possibly related issue is https://github.com/papis/papis/issues/47 (use-cache option broken).

**Comment by bluehood** [comment]
ah, I just saw this is actually mentioned in the FAQ's. in fact this is the only FAQ! :sweat_smile:

**Comment by alejandrogallo** [comment]
Hi @bluehood , I would be open to implement a clean way of checking which documents
are not in the cache, in the case that you're using the `database-backend = papis`.

However you might also want to implement a `githook` for this, for instance a `post-merge`
hook. 
https://git-scm.com/docs/githooks

If you do this and you want to write a few lines in 
https://papis.readthedocs.io/en/latest/git.html,
it would be great :p

**Comment by alejandrogallo** [comment]
I think I'll be closing this ;)
