### ISSUE TITLE
question: what's your papis workflow to get arxiv papers into your library?

### ISSUE THREAD

**Issue by bluehood** [papis/papis#105]
Can I just give papis a arxiv URL and let it figure out the rest?
(if not, is it something that I could implement with little papis knowledge?)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/41 (Webapplication for papis).

**Comment by alejandrogallo** [comment]
There is a downloader for arxiv,
https://github.com/papis/papis/tree/master/papis/downloaders

So you can just do
```
papis add --from-url arxivurl
```

or
```
papis explore arxiv -a bluehood pick cmd 'papis add --from-url {doc[url]}'
```
Is this it? ;) Tell it to your arxiv-using friends! :D

**Comment by bluehood** [comment]
yes that's it, I forgot I found out I could do that a couple weeks ago!
it's even documented. sorry for bothering, tough day today :sweat:

**Comment by alejandrogallo** [comment]
Don't mention it, I'm happy to help ;)
