### ISSUE TITLE
Ref tags are no longer unique

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#107]
Adding a document no longer automatically changes the ref tags unique. This feature was originally implemented in #36 but doesn't seem to be working anymore.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/80 (papis update --force overwrites unique ref tag).
