### ISSUE TITLE
tagging a document after adding it

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#109]
Sometimes I read a paper and want to tag it after the fact. Currently, I need to `edit` the document manually. Is there a way to `--set tags` of an existing entry directly from the command line?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn), https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion), https://github.com/papis/papis/issues/100 (papis add has permission issues), https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError), and https://github.com/papis/papis/issues/107 (Ref tags are no longer unique).

**Comment by alejandrogallo** [comment]
Hi Michael, actually it's funny because I also needed it and I implemented last week or two weeks ago,
in the master code you have the `--set` flag in `update`, which exactly does this, check it out
and tell me if we can improve it somehow.

**Comment by michaelplews** [comment]
I see! Thanks!
