### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'clear_cache'

### ISSUE THREAD

**Issue by hshackle** [papis/papis#113]
Just installed papis on my laptop (arch linux) using pip. Running it gives the following error:

>Traceback (most recent call last):
  File "/usr/bin/papis", line 11, in <module>
    load_entry_point('papis==0.7.3', 'console_scripts', 'papis')()
  File "/usr/lib/python3.7/site-packages/papis/main.py", line 22, in main
    papis.commands.default.run()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: run() got an unexpected keyword argument 'clear_cache'

Happy to post any other information or outputs, although the Arch install is only a few days old, so I wouldn't think the problem would be super specific.

EDIT: Somehow didn't notice the other issue related to this. Likely this is just a result of pip not installing the most recent version?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/110 (TypeError: run() got an unexpected keyword argument 'clear_cache').

**Comment by alejandrogallo** [comment]
Hi! 
Yes, we already had this problem, I haven't updated the papis pip3 version yet,
I will do it this week!

You can fix it by installing the current master version, just do
```
pip3 install git+https://github.com/papis/papis
```
and then you'll have it installed from the master branch.

Cheers!

**Comment by alejandrogallo** [comment]
I just updated to version `0.7.4`, you can install it via pip3,
```
pip3 install --upgrade papis
```
This should fix it!
Cheers!
