### ISSUE TITLE
Default List Format

### ISSUE THREAD

**Issue by jessebett** [papis/papis#119]
`papis list --format ...` is too annoying to write every time. Is there a config file option to provide the `...` as default?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/90 (add-name in "first-author"-"year" format?).

**Comment by alejandrogallo** [comment]
Hi @jessebett 

Thanks for your question. Maybe a simple bash script would help you in this case, you could write
a script called `papis-myformat` and store either in your path or in `~/.config/papis/scripts` with the following

```shell
#!/usr/bin/bash

papis -l ${PAPIS_LIB} list --format "Your format here"

```

and then you could just use it as
```
papis myformat
```
Does this help you?

**Comment by jessebett** [comment]
Thanks! You're right that I should solve this with my own script.
