### ISSUE TITLE
Picker for tags

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#122]
It would be really nice if we could have a picker for 'tags'. For example:

`papis tags` would allow picking of all tags used in a library. Once picked, the entries tagged with that tag are shown.

Is there a quick script we could write for this or would it need some more attention?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/109 (tagging a document after adding it), https://github.com/papis/papis/issues/88 (New picker, dump curses dependency), https://github.com/papis/papis/issues/107 (Ref tags are no longer unique), https://github.com/papis/papis/issues/80 (papis update --force overwrites unique ref tag), and https://github.com/papis/papis/issues/67 ('ref' tag with spaces causes errors on LaTeX compiling).
