### ISSUE TITLE
Upgrade Slugify dependency

### ISSUE THREAD

**Issue by JP-Ellis** [papis/papis#124]
In `setup.py`), the dependency for `python-slugify` is fixed to be exactly `1.2.5`:

https://github.com/papis/papis/blob/579074c55f2e24de58a10dd6a8066b26fe95e91d/setup.py#L39-L56

Is there an incompatibility with the latest release of slugify (which is currently at `1.2.6`)?  Or could this be changed to require at least version `1.2.5` like with all other dependencies?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/44 (tk dependency not declared), and https://github.com/papis/papis/issues/88 (New picker, dump curses dependency).

**Comment by JP-Ellis** [comment]
Would you like me to create a pull request to upgrade this dependency?

**Comment by alejandrogallo** [comment]
Sorry for the delay, I'm doing it, passing the tests and updating the version

**Comment by alejandrogallo** [comment]
Done in v0.7.5, thanks!
