### ISSUE TITLE
Upgrade click dependency

### ISSUE THREAD

**Issue by thoth101010** [papis/papis#125]
The python-click package version is required to be under 7.0 but the more recent version of python-click is 7

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/124 (Upgrade Slugify dependency), https://github.com/alejandrogallo/papis/issues/44 (tk dependency not declared), https://github.com/papis/papis/issues/88 (New picker, dump curses dependency), and https://github.com/papis/papis/issues/86 (Migrate to click for simplicity and maintainability).

**Comment by alejandrogallo** [comment]
Hi @thoth101010,

sorry for the delay. So the thing is that some things break with v7.0.0, I'll put it on the todo list
and maybe we can run exhaustive tests to check that v7.0.0 does not break anything.

**Comment by michaelcadilhac** [comment]
Just FYI, this breaks the AUR package right now.

**Comment by alejandrogallo** [comment]
Hi @michaelcadilhac , thanks for commenting.
What do you mean exactly by `this` and `breaking`.
Do you mean that updating to v7.0.0 breaks AUR or that the fact of not updating breaks it?
I have a branch with v7.0.0 and it seems to be working, the tests are passing, so I'll update soon.

**Comment by michaelcadilhac** [comment]
Hi there; sorry if I was unclear.  I meant that Arch Linux has `python-click` 7.0, hence using `pacman` and the AUR, papis complains about that and refuses to start.  In other words, a fresh install gives a broken papis.  Cheers!

**Comment by alejandrogallo** [comment]
This should be working now in master

**Comment by michaelplews** [comment]
Is this issue fixed? I am still having issues with a fresh install.

Running `sudo make install-dev`

Followed by `papis open` gives the following:

![papis_img](https://user-images.githubusercontent.com/14098929/53513264-a24e3900-3a79-11e9-9aa8-c1893d133cf4.png)

**Comment by alejandrogallo** [comment]
Ui! It seems that `prompt_toolkit` updated the api of the `FormatBufferController` and did not update the middle version number. We should have `prompt_toolkit` higher or equal than 2.0.5, then it will work.
I'll commit then.That's bad, thanks for pointing it out!

**Comment by michaelplews** [comment]
Thanks @alejandrogallo, it works now!
