### ISSUE TITLE
open all files simultaneously when using edit --all

### ISSUE THREAD

**Issue by thoth101010** [papis/papis#126]
When using `papis edit --all` and `papis edit --all -n` , I think that it could be nice to open all files simultaneously with the editor by giving them as an unique argument rather than opening them one after the other.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/21 (Rofi GUI open wrong file, sometimes), https://github.com/papis/papis/issues/104 (How do you pick and open?), and https://github.com/papis/papis/issues/63 (Rofi GUI cannot open files if there's a space anywhere in the path name).

**Comment by alejandrogallo** [comment]
Hi, interesting, but I don't know if we should break it now and change it.
You can do it easily in one command

```
YourEditor $(papis list --info <your_query>)
```

for instance

```
vim $(papis list --info einstein)
```

Is something like this enough for you?

**Comment by thoth101010** [comment]
Thank you, I didn't though to do that but as it can be written in a custom script it's perfect :grinning:

**Comment by alejandrogallo** [comment]
I'm happy it helped!
