### ISSUE TITLE
Multiline header-format with vim as picktool

### ISSUE THREAD

**Issue by thoth101010** [papis/papis#127]
Using vim as picktool doesn't allow to use multiline header-format

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/118 (Error when using vim or dmenu as picktool), and https://github.com/papis/papis/issues/91 (vim/vimtex integration).

**Comment by alejandrogallo** [comment]
Yes, the vim picker might have this issue, I'm thinking anyways of taking it out of papis,
I thought no one was using it, I think it's better to make a separate project out of it, what do you think?

**Comment by thoth101010** [comment]
In fact, as it does not support multi-line, I only tried and went back to the default picker.
And yes, as it does not support the configuration possibilities, I think it's better to remove it and maybe do it as a separate project if someone would like to maintain it.
( and I will keep a link to the git version with the vim in fact I'm one day able to do it )

**Comment by alejandrogallo** [comment]
Version v0.8 will not have guis, so this is is solved by it.
