### ISSUE TITLE
crossref:Couldn't resolve DOI '10.1038/s41578-018-0065-0' through CrossRef: 'year'

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#129]
[This article](https://www.nature.com/articles/s41578-018-0065-0) is not added correctly when using the command 

```bash
papis add --from-doi '10.1038/s41578-018-0065-0' --set tags 'review'
```

Even though it [exists in Crossref](https://search.crossref.org/?q=10.1038%2Fs41578-018-0065-0)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/54 (doi resolution is buggy).

**Comment by alejandrogallo** [comment]
Hmmm... True, weird, we'll have to look into it, this is an excellent example for debugging! ;)

**Comment by michaelplews** [comment]
The above command now works as expected, I suspect this was a Crossref issue.
