### ISSUE TITLE
Wrong color format from prompt_toolkit

### ISSUE THREAD

**Issue by nelimee** [papis/papis#131]
### Error description:

Every call to `prompt_format` results in an exception being thrown (full stack-trace [here](https://gist.github.com/nelimee/9c31f6c38773d7bac1e7d77b0971a326)).

### Steps to reproduce the bug:

```bash
python3 -m venv ~/papis_bug_venv
source ~/papis_bug_venv/bin/activate
pip3 install -U pip
pip3 install papis
# Add at least 2 papers to let 'papis open' trigger prompt_toolkit.
papis open
```

### Additional informations:
- **Console**: Konsole 17.04.1
- **Python**: 3.6.5
- **`pip freeze`**: 
  ```
  arxiv2bib==1.0.8
  beautifulsoup4==4.6.3
  bibtexparser==1.0.1
  certifi==2018.11.29
  chardet==3.0.4
  click==6.7
  configparser==3.5.0
  filetype==1.0.1
  future==0.17.1
  habanero==0.6.2
  idna==2.7
  isbnlib==3.9.3
  papis==0.7.5
  parse==1.6.5
  prompt-toolkit==2.0.7
  pylibgen==1.3.1
  pyparser==1.0
  pyparsing==2.3.0
  python-slugify==1.2.6
  PyYAML==3.13
  requests==2.20.1
  six==1.12.0
  Unidecode==1.0.23
  urllib3==1.24.1
  wcwidth==0.1.7
  ```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/119 (Default List Format), https://github.com/papis/papis/issues/127 (Multiline header-format with vim as picktool), https://github.com/papis/papis/issues/21 (Rofi GUI open wrong file, sometimes), and https://github.com/alejandrogallo/papis/issues/43 (papis-python-rofi wrong name).

**Comment by alejandrogallo** [comment]
Hi @nelimee , thank you for taking the time to report.

I have checked that in version 2.0.6 from `prompt_tooklit` something happened with the colors:

https://asciinema.org/a/JU3Ru9PFJ7TacHlzae1DwfKrk

Also in version 2.0.7.
I just wanted to ask if you changed the [`header-format`](https://papis.readthedocs.io/en/latest/configuration.html#config-settings-header-format)
 config option. I'm running `prompt_toolkit` version 2.0.7 and I don't have any problems up to now,
only the color issue.

**Comment by nelimee** [comment]
Here is the output of `papis config header-format` on my machine:
```
<red>{doc.html_escape[title]}</red>                                                                                 
 <span color='#00ff00'>{doc.html_escape[author]}</span>                                                             
  <span color='#00ffaa'>({doc.html_escape[year]})</span> [<yellow>{doc.html_escape[tags]}</yellow>] 
```

I changed my `~/.config/papis/config` to something very simple before running the commands listed in "Steps to reproduce the bug" in my first message:
```
[settings]
default-library = qcpapers

# Define a library for quantum-computing papers
[qcpapers]
dir = ~/.papis/qcpapers
```
Moreover, I did a `papis --cc` in case anything was not valid in the cache (I think it was not needed, but in doubt I did it).

Finally, I tried with all the `prompt-toolkit` versions available on PyPi: `2.0.X` for `X` between (inclusive) 1 and 7, the bug is still triggered. 

I will try to do a complete re-install, I'll post the results here when done!

**Comment by nelimee** [comment]
Even though I already tried it before posting the issue, the fresh-install method worked!
I did a full remove this time (removed recursively everything that popped up with `find ~/ -name "*papis*"`), I suspect that some files where broken in `~/.cache/papis`.

Sorry for posting this issue too soon, I should have checked with a full-remove followed by a fresh install before.

Thanks for the reactivity (and for the awesome tool)!

**Comment by nelimee** [comment]
I found the origin of the problem: when one specific scientific paper downloaded from a DOI is in my library, the `prompt_format` crashes.
To add this specific paper to your library: `papis add --from-doi '10.1007/s11128-016-1495-5'`.

To sum up:
```bash
papis add --from-doi '10.1007/s11128-016-1495-5'
papis open # works because prompt_toolkit is not triggered
papis add --from-doi '10.1007/s11128-016-1495-5' # adds a second entry in the library, see below
papis open # fails
```

This is probably another issue, but repeating the command `papis add --from-doi '10.1007/s11128-016-1495-5'` multiple times results in the "same" document being added multiple times to the library. My filenames contain hashes, so this might be because the PDF file is modified for each download.

**Comment by nelimee** [comment]
The problem come from the unicode character `\xc2\xa0` within the name of one of the authors (`van den Berg` <- copy **not** containing the unicode character, see [here](https://hexdump.pieterhordijk.com/1f1ed389bb090224551929ffd870be78143b5d62) for hexadecimal values of the characters presents in the `info.yaml`).

I don't know why this character fails though... Another unicode character on the same line seems to be fine (the `î` in `Benoît`).

**Comment by alejandrogallo** [comment]
Hi @nelimee, 

I reproduced the error

https://asciinema.org/a/5N5rGO8LN8zeuWymtvGw4Cj2p

It is weird, really, but I'll take a look.

BIG BIG Thanks for this bug, this is extremely relevant.

**Comment by alejandrogallo** [comment]
This is solved in the new picker.
