### ISSUE TITLE
Upgrade Slugfiy to 2.0

### ISSUE THREAD

**Issue by JP-Ellis** [papis/papis#133]
`python-slugify` has upgraded to `2.x` earlier in the year.  According to [their changelog](https://github.com/un33k/python-slugify/blob/master/CHANGELOG.md), the breaking change only relates to the installation.  Hopefully this means papis could upgrade to `2.x` without too much issue?

If you'd like me to create a pull request for this, let me know.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/124 (Upgrade Slugify dependency), and https://github.com/papis/papis/issues/125 (Upgrade click dependency).

**Comment by alejandrogallo** [comment]
Hi @JP-Ellis,
thanks for noticing this, I just updated it and the tests seem to be ok with it, so it should be ok.
Thanks!

**Comment by alejandrogallo** [comment]
I should be updating the version very soon, however I'm quite busy at the moment...
