### ISSUE TITLE
Exporting --to-bibtex is semi-broken

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#134]
https://github.com/papis/papis/blob/b023ca0e551a29c0c15f73fa071addd3e61fa36d/papis/document.py#L129

I admit this is partly my fault from an earlier pull request wherein I wanted to explicitly map some papis fields to their proper bibtex equivalents. In doing so, I wanted to add/modify as few lines as possible. Everything was working okay until the `sorted` call was added in the line referenced above. Calling `sorted` actually creates a new list. Thus when I add these 'translated' keys back into the `document` dict, the _sorted_ version remains unchanged, and these fields are never added to the bibtex string, breaking the intended functionality.

I agree that having the fields sorted would be nice, which is why I'm opening the issue to see how best to resolve the dilemma. Also, I'm an engineer and am not very good at writing "real" software :smile:.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/35 (Add unicode to latex support for bibtex export), https://github.com/alejandrogallo/papis/issues/4 (Parsing of BibTeX breaks with nested curly brackets), https://github.com/papis/papis/issues/60 (Export multiple elements), https://github.com/alejandrogallo/papis/issues/10 (Additional bibtex keys), and https://github.com/alejandrogallo/papis/issues/38 (Multiple authors in bibtex).
