### ISSUE TITLE
papis explore citations gets stuck

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#137]
papis explore citations randomly gets stuck, and with large amounts of citations like in review articles, never completes.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/65 (Search citations), https://github.com/papis/papis/issues/41 (Webapplication for papis), https://github.com/papis/papis/issues/105 (question: what's your papis workflow to get arxiv papers into your library?), https://github.com/papis/papis/issues/92 (papis-python-rofi), and https://github.com/papis/papis/issues/100 (papis add has permission issues).

**Comment by alejandrogallo** [comment]
You're right, I fixed it now. When fetching dois, it checks if the doi is already in the library,
if there was more than one match to that query to the database, it would pick which one, however
this conflicted with the running instance of an app of prompt_toolkit, which made it crash.
Now it's fixed.
