### ISSUE TITLE
History of papis

### ISSUE THREAD

**Issue by teto** [papis/papis#138]
hi,

see the title. Many times I've been frustrated by mendeley being closed source (though i really like the software) and I can't get myself to like zotero after being used to mendeley.
Many times I've thought of starting my own project but gave up in front of the task. Papis looks like something I could use. I am just curious as to how papis got into existence, what are the authors' motivations etc.

As a sidenote, is there some search possible on pdf notes ? how to deal with pdf notes ?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/41 (Webapplication for papis), https://github.com/papis/papis/issues/100 (papis add has permission issues), https://github.com/papis/papis/issues/137 (papis explore citations gets stuck), https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError), and https://github.com/papis/papis/issues/92 (papis-python-rofi).

**Comment by teto** [comment]
Not sure how the files are saved yet but some pdf readers can save notes in a separate file such that it could be indexed for full search with xapian for instance. I think zotero picks up such notes though I am not sure. As for mendeley it's builtin in theyr fuc**ng ciphered  database.
I started my phd with mendeley then recently suffered from several breakage, tried zotero but don't like their stack nor the UI. I have a heavy terminal-based workflow so I will stick with papis. Looks great so far. I was dubious for the need of such software at first, but even after/without PhD, it's pretty useful. Thanks for your initiative !
