### ISSUE TITLE
Whoosh null queries return no results

### ISSUE THREAD

**Issue by bwinkler** [papis/papis#140]
When Whoosh is the database backend for a library, blank/null queries return no results. This means that commands like `papis export -all` do not export anything unless an additional wildcard query is supplied like '*'. Here is an example:

```
 papis -v --debug export --bibtex --all --out exportTest.bib
14-DEBUG:papis:DEBUG MODE FOR DEVELOPERS ON
15-DEBUG:papis:Imported commands
18-DEBUG:config:Merging configuration from /home/bwinkler/Docs/Work/.papis.config
74-DEBUG:db:whoosh:Initialized index found for library
74-DEBUG:db:whoosh:Query string .
84-DEBUG:db:whoosh:<Top 0 Results for <_NullQuery> runtime=1.9587110728025436e-05>
84-INFO:cli:export:Dumping to exportTest.bib
```

This produces an empty file called exportTest.bib. However, the following:
```
papis -v --debug export --bibtex --all '*' --out exportTest.bib
```
produces an export file with all the correct records. Note also that leaving out the `--all` option as in `papis export --bibtex '*' ...` does not export all the records either but instead opens the interactive interface to make an additional selection.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hello and thank you very much for your interest and attention.

 Yes as a matter of fact this is how you’re saying and actually there is a configuration settings to control this behavior, 

https://papis.readthedocs.io//latest/configuration.html#config-settings-default-query-string

 You can set the above setting to the *

 I hope this solves what you’re looking for. 
 Have a nice day and don’t hesitate to ask more questions here.

**Comment by bwinkler** [comment]
Shouldn't the default value of 'default-query-string' change from '.' to '*' when whoosh is in use?

**Comment by alejandrogallo** [comment]
Hi @bwinkler 
No because one of the reasons to switch to the `whoosh` database was
that the simple caching system cannot cope with a huge amount of documents.
Therefore it is not wanted to load all documents of a library every time one issues a papis command.
If you just have a couple of documents, maybe it's enought to use the cache database.
Chhers!

**Comment by bwinkler** [comment]
But surely when you use the option `--all` when exporting, you would expect to get *all* the records. When `whoosh` is enabled as a backend, though, something like
```
papis export --all --bibtex --out export.bib
``` 
will export no records unless you know to modify the `default-query-string` config variable. 

In contrast, when you use the simple caching system, the same command exports all the records. This is true because the default value of `default-query-string` is '.'. This seems especially confusing since you said that `whoosh` was adopted because the simple caching system could not handle large numbers of records.

**Comment by teto** [comment]
we ought to reopen this IMO. While apparently different backends have different ways to query the database, having 0 results with --all is pretty unexpected, there should be at least a warning.
