### ISSUE TITLE
feedback on first try

### ISSUE THREAD

**Issue by teto** [papis/papis#141]
I've tried papis a bit in real conditions. Here is some feedback, sometimes subjective, sometimes objective, sometimes actionable, sometimes without a clear path to resolution.

1. ~~my main concern is that upon `papis export --bibtex --all` citation keys are generated even though I imported from zotero. I could have coped with it if I were starting from a cleanslate but right now this breaks the compilation of all my papers. The keys got exported from zotero `extra: 'Citation Key: Heuschkel2018'` but are not used. I wonder if this actionable ? or if the generated citation key is part of papis' logic ?~~
2. ~~in nixos, usually it's enough to put the zsh completion in share/zsh/site-functions/ and it's picked up by zsh.
With papis, I added  `eval "$(_PAPIS_COMPLETE=source_zsh papis)"` on the advice of @dtz but it gave me some python errors on spawning shell (which I can't find it anymore), I actually wonder if this why my shells are now slow to start. I might need to investigate.~~
3. ~~I tried running `papis update --from-doi` and it asked me if I wanted to override fields even when they were equal.
For instance I got asked `skip user conflict (year conflict) Replace '2018' by '2018'`~~
4. ~~in the documentation, it says cache-dir is None by default but the default is $XDG_CACHE_HOME. Maybe it doesn't reflect the code but I think it should.~~
5. ~~I would really prefer if running just `papis` would print help instead of doing nothing. Might be just me though.~~
6. I use a solarized theme for my terminal and papis colors look really bad, to the point it's kinda unreadable. I don't think the default config could accomodate everyone but something I usually enjoy is when there is an exhaustive config with all options available somewhere. wireshark does it. Astroid generates such a config as well when none exists. It makes it easier to discover options. Also not everything is overridable in the TUI theme so I still have blue text on bluish background xD
7. Because I am used to fzf, I wanted to use it as a picktool but from the doc it was not clear how picktools work or how I can add one. I was expecting papis to just pipe everything out but seems like you need some adapter ? The help message:
```
This is the program used whenever papis asks you to pick a document or
options in general.
```
8. ~~First I tend to share my dotfiles across computers so I ended up with a papis config that pointed at a non-existing folder. I originally thought the folder existed so I ended up confused when running `papis open`:
`No documents found with that name.` 
I thought ok let's try verbose mode:~~
```
52-DEBUG:config:Merging configuration from /mnt/ext/Zotero/Documents/.papis.config
54-DEBUG:db:cache:Initializing
57-DEBUG:cache:Getting documents from dir /mnt/ext/Zotero/Documents
```
still no indication the folder does not exist.

Note that I might address some of the low hanging fruits (3,5) but would like your opinion on 1.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/90 (add-name in "first-author"-"year" format?).

**Comment by teto** [comment]
so yeah I found the trace I had saved when launching a shell:
```
  File "/nix/store/biq309lxqwpl1nfap4h3s58wcxd134xq-python3.7-pandas-0.24.1/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1125, in _validate
    raise MergeError("Merge keys are not unique in either left"
pandas.errors.MergeError: Merge keys are not unique in either left or right dataset; not a one-to-one merge



    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/teto/.config/papis/config' [line 33]: option 'options_list.selected_margin_style' in section 'tui' already exists
Traceback (most recent call last):
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/bin/.papis-wrapped", line 7, in <module>
    from papis.main import main
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/main.py", line 6, in <module>
    import papis.commands.default
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/commands/default.py", line 31, in <module>
    import papis.api
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/api.py", line 11, in <module>
    import papis.utils
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/utils.py", line 14, in <module>
    import papis.document
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/document.py", line 5, in <module>
    import papis.bibtex
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/bibtex.py", line 25, in <module>
    ] + re.sub(r" *", "", papis.config.get('extra-bibtex-types')).split(',')
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/config.py", line 975, in get
    return general_get(*args, **kwargs)
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/config.py", line 930, in general_get
    config = get_configuration()
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/config.py", line 1016, in get_configuration
    _CONFIGURATION = Configuration()
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/config.py", line 1108, in __init__
    self.initialize()
  File "/nix/store/v9l5zaa4apgi66sw72mkaqj5z4v9f83x-papis-0.8.2/lib/python3.7/site-packages/papis/config.py", line 1125, in initialize
    self.read(self.file_location)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/teto/.config/papis/config' [line 33]: option 'options_list.selected_margin_style' in section 'tui' already exists
```
i.e., an error in papis configuration gets printed as I try to load the completion. Getting completion shouldn't start python IMO  `eval "$(_PAPIS_COMPLETE=source_zsh papis)"` CC @dtzWill

**Comment by teto** [comment]
Some more feedback:
9. seems like `--nc` doesn't disable color in the picker with `papis, version 0.8.2`. I would prefer if it worked like usual gnu flags: `--color=always|auto|no`.

10. I've added `ref-format = {doc[author_list][0][surname]}{doc[year]}` in [settings] as an attempt to export to bibtex with keys that wouldn't break latex compilation but it didn't have any effect it seems.

11. Also I enabled the whoosh database because the default cache was too slow but then it stops exporting with a null query (it did export with the default one):
```
 papis -v export --all --bibtex > mylib.bib
29-DEBUG:config:Merging configuration from /mnt/ext/Zotero/Documents/.papis.config
91-DEBUG:db:whoosh:Initialized index found for library
91-DEBUG:db:whoosh:Query string .
98-DEBUG:db:whoosh:<Top 0 Results for <_NullQuery> runtime=1.26329978229478e-05>
98-INFO:cli:export:Dumping to stdout
```

I would like to start hacking a bit on papis but first I really need to be able to export to bibtex with the zotero key so that I can start using it. Would love to have some insight on this.

Also I would like to add fzf as a picker. I've seen the Picker class but seems like other picker have been removed. Any hint on how to implement such a picker please ?

**Comment by alejandrogallo** [comment]
Hi!

some points need to be commented in length but some points are solvable.

1. The citation key in the yaml file that papis uses is `ref`, so you just have to change that one.
  It is apparently not really discussed in the docs, I'll have to write
  a chapter about this. (TODO)

2. The shell completion works through the package `click`, which
  runs papis every time, I'm happy to accept pull requests with a custom
  shell completion, up to now is this the only way of doing it automatically.

3. Sometimes this happens if the number for instance contained some
  weird unicode characters or numerals, which then would mean that the
  strings where strictly different.

4. True, TODO.

5. Sometimes it is handy to do `papis --clear-cache`, however this is
  disputable.

6. Yeah, true, this I should document better and fix (TODO).

7. Yes indeed, it is not documented because at the time is buggy and I'm unsure
  about which is the best way of interfacing external pickers with papis,
  we could discuss about this too.

8. Yes, at least a warning there should be popping up.

9. We can consider this yes, it's better to do it this way, I agree. (TODO)

10. The `ref-format` is only at the time of adding, sadly.

11. Yes, this behaviour you can change with the setting
  It is realted to issue #140

**Comment by teto** [comment]
I checked for 3 and there is indeed code to prevent that. As you say must have been unicode.
I've started some PRs to fix some of the mentioned points and will open different PRs to discuss points that need more consideration (the picktool especially).

a few quick questions:

my libraries are synced in different folders on my different computers, thus I would like to share a global config and include a local config. Seems like there is an "include" key for that. Could you show me how it worked ? I couldn't make it work.
```
    def handle_includes(self):
        if "include" in self.keys():
            for name in self["include"]:
                self.logger.debug("including %s" % name)
                self.read(os.path.expanduser(self.get("include", name)))
```

I tend to edit python code with mypy which is in my experience the best static tool to find python errors yet it has some limitations or edgecases. Would you be ok if I send patches that silence some of the errors:
For instance replacing     `return general_get(*args, data_type=int, **kwargs)`
with
```
    kwargs.update(datatype=int)
    return general_get(*args, **kwargs)
```
This silences this kind of (edgecase) warning https://github.com/python/mypy/issues/2582 . I've noticed a few others.

**Comment by alejandrogallo** [comment]
Hi, about the local config, is the `.papis.config` config not good enough?
I have this library for instance
https://github.com/alejandrogallo/datasheets
and there I have the `.papis.config` in the folder.
https://papis.readthedocs.io/en/latest/configuration.html#local-configuration-files

About the mypy, everything that contributes to the better sanity of the code and passes
the PEP and the tests, I welcome it. Thanks, I'll check out the `mypy` project myself.

**Comment by teto** [comment]
depending on the computer, I want a different default library while sharing all the other settings. 
It doesn't matter much but because I saw the "include directive" I  thought for a moment it was possible.

**Comment by alejandrogallo** [comment]
Sorry, you're right, is not clear. But it is possible, in my papis config I have the following

```ini
[include]
tk-gui = ~/.config/papis/tk-gui.ini
rofi-gui = ~/.config/papis/rofi-gui.ini
```
and it sources the files there. However since this is not documented we can think about if this is the best thing to do or not.

**Comment by teto** [comment]
thanks that's exactly what I wanted. I've retested my zotero sql import changes and they do work, I was checking the wrong folder (will improve the script to make it more evident).

So now that I have a folder with my documents with proper `refs`, I am trying again to export again (the default library points towards the folder I exported to):
```
(ins)[nix-shell:~/papis]$ papis -v export --all --bibtex --out mylib.bib
37-DEBUG:config:Merging configuration from /home/teto/papis_db/.papis.config
119-DEBUG:db:whoosh:Creating index...
119-DEBUG:db:whoosh:Creating dir /home/teto/.cache/papis/whoosh/5b95a1a2ce149bd9e72f01dab58fd37e-papis_db
119-DEBUG:db:whoosh:Creating schema
121-DEBUG:db:whoosh:Indexing the library, this might take a while...
121-DEBUG:utils:Indexing folders
186-DEBUG:dir2doc:Running in 4 cores
197-DEBUG:dir2doc:pool started
2705-DEBUG:dir2doc:pool done (2507.693359375 ms)
4103-DEBUG:db:whoosh:Query string '*'
4113-DEBUG:db:whoosh:<Top 0 Results for <_NullQuery> runtime=2.1227984689176083e-05>
4114-INFO:cli:export:Dumping to mylib.bib

```
with /home/teto/papis_db full of only folders:
```
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZQBN6ZQ3
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZRLR5CVS
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZRU4XTLJ
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZRWM2L6I
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZSTJGUNB
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZT4KZL6K
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZTLYMVMH
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZU9S65PA
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZV8D5P6U
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZX99AX3S
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZXMFTU7N
drwxr-xr-x 2 teto users 4096 03-15 12:11 ZZEIZA56
```
I can't compare with my other (working) computer at the moment to check what's wrong.
I've tried `papis --clear-cache` several times to no avail. What am I missing ?

**Comment by teto** [comment]
In fact my db is ok, I can use open/search with a non null string etc, the problem is with the whoosh backend and export command with an empty string. My config does `have default-query-string = '*' `.
I don't know the whoosh api but this patch fixes the problem for me; might be nice to have a test.
```
diff --git a/papis/commands/export.py b/papis/commands/export.py
index 9a4d8d9..4586034 100644
--- a/papis/commands/export.py
+++ b/papis/commands/export.py
@@ -176,7 +176,10 @@ def cli(
     """Export a document from a given library"""
 
     logger = logging.getLogger('cli:export')
-    documents = papis.database.get().query(query)
+    if all:
+        documents = papis.database.get().get_all_documents()
+    else:
+        documents = papis.database.get().query(query)
 
     if json and folder or yaml and folder:
         logger.warning("Only --folder flag will be considered")

```

**Comment by teto** [comment]
One other thing I am not sure I get right is about papis' workflow. In mendeley/zotero I would first select documents and then apply an action on them. In papis, I have the feeling that I should an action to apply on documents selected by a query without knowing exactly what the query returns. Is that correct ?
I would rather pick documents first (fzf can do it, it has a preview mode as well https://github.com/junegunn/fzf) and then choose which action to apply.

**Comment by teto** [comment]
Most painpoints have been addressed. closing
