### ISSUE TITLE
--no-edit --no-confirm ignored when adding --from-folder

### ISSUE THREAD

**Issue by supersambo** [papis/papis#142]
Thanks for this tool it looks really promising! Unfortunately I'm not yet there...

I'm trying to migrate from an existing zotero database (~ 1400 entries). I use the papis-zotero-sql script which spits out all the necesary folders. After that I'm trying to add all my references using the bash loop provided [here](https://papis.readthedocs.io/en/latest/importing.html#importing-from-zotero-sqlite-file), only by adding the` --no-edit` and `--no-confirm` options. I also set them in my configuration file but they are being ignored when adding `--from-folder`. Given the amount of my library I'd like to avoid confirming all entries manually. Is there an easy way to do so?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/23 (add --from-isbn), https://github.com/papis/papis/issues/109 (tagging a document after adding it), https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion), https://github.com/papis/papis/issues/100 (papis add has permission issues), and https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError).

**Comment by alejandrogallo** [comment]
Hi @supersambo ,

I'm glad you're trying it out! You mean that if you add the ``--from-folder`` flag,
it asks you every time for editting and confirming?

Btw, I'm at the TU Wien, I see you're also in vienna, maybe at some point if you need more special support you can come by ;)

Cheers

**Comment by alejandrogallo** [comment]
I can't reproduce the behaviour that you are refereing to... Example:
https://asciinema.org/a/mBPzG5zx51YbFWp0wtda9irj6

**Comment by supersambo** [comment]
I see, I forgot to `--no-open` option! 

Sounds great, once I've become more familiar with papis, it would be great to talk about it!
