### ISSUE TITLE
zotero import sql: convert  `Citation Key:` to `ref`.

### ISSUE THREAD

**Issue by teto** [papis/papis#148]
convert  `Citation Key:` to `ref`. I've started doing it but I wonder which zotero script from which repo I should update

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/97 (zotero import script not working in 0.7), https://github.com/alejandrogallo/papis/issues/18 (Import bib (zotero) fails finding file), and https://github.com/alejandrogallo/papis/issues/17 (Import bib (zotero) fails if field is missing).

**Comment by teto** [comment]
Here is some knowledge after I've done a bit of research:
truth is I never really used zotero and so the `extra:Citation Key:` in info.yaml I see from papis is a leftover from the mendeley -> zotero conversion (while I thought it was a zotero key).
Apparently there is no citation key yet in zotero they are generated as explained in 
https://retorque.re/zotero-better-bibtex/citation-keys/

Better bibtex is a zotero plugin that can take use the exported mendeley key and use it as a zotero key but I can't find a proper item in the sql database, I believe it is generated so it might be hard
https://github.com/retorquere/zotero-better-bibtex/issues/1020

Enabling this extension also allows to add a "citekey" column in the middle of zotero, it seems like this citekey is managed by the plugin outside of the zotero database, I am currently looking for "where".

**Comment by teto** [comment]
seems like it is always generated https://github.com/retorquere/zotero-better-bibtex/issues/448. Looks simpler to just adjust my citations than dealing with  this mess :(
