### ISSUE TITLE
Adding a .pdf saves file as .pdf.pdf

### ISSUE THREAD

**Issue by jessebett** [papis/papis#151]
If I `papis add file.pdf` then the default filename is `file.pdf.pdf`. This is annoying to fix everytime. Is it possible to detect if the file is named `.pdf` and then not append another extension name?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/23 (add --from-isbn), https://github.com/alejandrogallo/papis/issues/22 (pdf import: rename file in a meaningful way), https://github.com/alejandrogallo/papis/issues/39 (file-name option and adding files with incomplete metadata), https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion), and https://github.com/papis/papis/issues/109 (tagging a document after adding it).

**Comment by alejandrogallo** [comment]
Hi @jessebett, thank you for this, fixing it...

**Comment by alejandrogallo** [comment]
This was indeed a problem, since most people have activated the `file-name` option, it did not appear in that case (my case for instance).

**Comment by jessebett** [comment]
Oh,  I also want to activate the file-name I think!

I just stole the [config file in the docs](https://papis.readthedocs.io/en/latest/configuration.html) do you think you could also include an example demonstrating the `file-name` option?

**Comment by alejandrogallo** [comment]
I have updated a little the documentation, now there is a more complete config file, I hope you like it!
I'm closing now this issue.

**Comment by jessebett** [comment]
If I add a file with `.pdf` in its name it still produces a new papis file with `.pdf.pdf`.
