### ISSUE TITLE
How to use subfolder structure?

### ISSUE THREAD

**Issue by hshackle** [papis/papis#152]
In the documentation, there is some mention of a subfolder/sublibrary structure, but I'm unclear how to properly utilize this feature. Specifically, I would like to

- add files (from a url, to be precise) to a specific subfolder
- view only the files in a specific subfolder using `papis open`
- move documents from one subfolder to another (I'm assuming this can be done by physically moving the files, but maybe there's a better way?)
- export only the files in a subfolder

Are any of these things possible? If so, how do I do them?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/28 (Making the metadata more structured), https://github.com/papis/papis/issues/83 (work with existing file structure), and https://github.com/papis/papis/issues/47 (use-cache option broken).

**Comment by alejandrogallo** [comment]
Hello @hshackle ,
subfolders are not really thought for this actually.
