### ISSUE TITLE
Extra line breaks with arxiv downloader

### ISSUE THREAD

**Issue by nelimee** [papis/papis#154]
Actual behaviour (version 0.8.2)
=========================

When adding a document from arxiv, long titles and abstracts contain extra line-breaks.

How to repoduce
---------------------

```sh
papis add --from-url https://arxiv.org/abs/1903.06311 --set tags 'IWantToFindBackThisEntry87356389'
papis edit IWantToFindBackThisEntry87356389
```

Output of `papis edit`
---------------------------

```
abstract: 'A Bell experiment can be conceptualized as a box, i.e., a process taking

  classical setting variables to classical outcome variables, which has a

  common-cause structure, i.e., one that can be realized by implementing local

  measurements on systems that are prepared by a common-cause mechanism, with no

  [more text...]

  consider the pre-order on the subset of common-cause boxes that are quantumly

  realizable and prove that every convexly extremal such box is at the top of

  this pre-order.'
archiveprefix: arXiv
author: Elie Wolfe and David Schmid and Ana Belén Sainz and Ravi Kunjwal and Robert
  W. Spekkens
eprint: 1903.06311v1
file: 1903.06311v1.pdf
files:
- 2019-elie-wolfe-and-david-schmid-and-ana-belen-sainz-and-ravi-kunjwal-and-robert-w.-spekkens-bell-quantified-the-resource-theory-of-nonclassicali.pdf
month: Mar
primaryclass: quant-ph
ref: 1903.06311v1
tags: test
title: 'Bell Quantified: The Resource Theory of Nonclassicality of Common-Cause

  Boxes'
type: article
url: http://arxiv.org/abs/1903.06311v1
year: '2019'
```

Expected behaviour
================

There should be only one (or maybe zero?) line break per line of text.

Remarks
=======

This issue is strange because the code seems to handle this [here](https://github.com/papis/papis/blob/master/papis/arxiv.py#L80) and [here](https://github.com/papis/papis/blob/master/papis/arxiv.py#L86).

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/19 (Scihub downloader failing), and https://github.com/alejandrogallo/papis/issues/3 (Choose option screen broken by left/right arrow).

**Comment by alejandrogallo** [comment]
You're right, however I know what is the problem, the problem is not in the `get_data` method
but in the `downloader`, `papis/downloaders/arxiv.py`, it should be a `TODO` to try to merge these two codes...

Thanks

**Comment by nelimee** [comment]
Do you want me to take a look if I have the time? 

PS: again, great tool and awesome support/reactivity!

**Comment by alejandrogallo** [comment]
@neelimee Please, feel free, I'll explain in a few words what's on my mind about this issue.

Basically I coded the `papis.arxiv.get_data` to parse information from arxiv using its `API`.
This is done without any library.
But before this the downloader for `arxiv` was implemented using the arxiv2bibtex package,
which is the problematic one. The downloader basically gets the arxiv identifier and spits out
the path for the pdf and the bibtex. The task would be to use the `get_data` routine together with the `id_list` to get the bibtex information, leaving the pdf path in the downloader untouched.

@nelimee You're welcome! :p

**Comment by nelimee** [comment]
Ok! I will try to have a look during the week or this week-end. Not sure I will have the time though, I keep you updated!

**Comment by nelimee** [comment]
Seems like the issue is fixed by adding 2 lines in `papis.bibtex.bibtexparser_entry_to_papis`:
```py
def bibtexparser_entry_to_papis(entry):
    """Convert keys of a bib entry in bibtexparser format to papis compatible
    format.

    :param entry: Dictionary with keys of bibtexparser format.
    :type  entry: dict
    :returns: Dictionary with keys of papis format.

    """
    result = dict()
    for key in entry.keys():
        if key == 'ID':
            result['ref'] = entry[key]
        elif key == 'ENTRYTYPE':
            result['type'] = entry[key]
        elif key == 'link':
            result['url'] = entry[key]
        elif key in {'title', 'abstract'}:               # < this line
            result[key] = entry[key].replace("\n", " ")  # < and this one
        else:
            result[key] = entry[key]
    return result
```

but this modification seems like a ugly hack. What do you think?

**Comment by alejandrogallo** [comment]
Hi! thanks for that, it was a little more involved, I already fixed as a part of something more
general. Thanks anyways! :)
The changes are on master, although I'll wait until v0.9 to release everythign I'm preparing, 
you can check from time to time the CHANGELOG.md file
