### ISSUE TITLE
Biber reported the following issues  Invalid format '2013-00-00 2013'

### ISSUE THREAD

**Issue by teto** [papis/papis#155]
After importing from zotero, I get `Biber reported the following issues with 'mptcpRFC6824': - Entry 'mptcpRFC6824' (papis.bib): Invalid format '2013-00-00 2013' of       ↳ date field 'date' - ignoring`

In the yaml files, all my dates are formatted as:
`date: 2013-00-00 2013`
I am not sure why. Any idea how to fix this ? like a knob in zotero, a setting in papis or a change in the import script. I don't get why zotero would record dates like this.

I changed the code to export `date: 2013-00-00` instead but biber would still complain because it needs real days/month, like  `  date = {2013-01-01},`. 

I am thinking of fixing this rather in the export phase but not sure how. Like don't export the date if day and month are 0. Would that be ok ?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
So this date comes from zotero? If so you can fix it by just not importing it in the zotero script, commenting it out.
In my opinion the date is irrelevant for bibtex, the year is ususally the important bit, you can just
kill them all
```
papis update '*' --all -s date '' 
```
I was also now thinking that it would be nice to have a `-d --delete [key]` flag in update actually.

**Comment by teto** [comment]
I can quickly patch it locally but what would be nice is the ability to run some hook/plugins. or one's own exporter since there are so many usecases, it's not possible to satisfy them all.
As a matter of fact, I think papis will need plugins one way or another (for pickers/exporters/importer etc). I've been using in one of my project stevedore which I find really great since the only dependency between projects is the "entry_point" string in the setup.py:
```
    entry_points={
        'mptcpanalyzer.plots': ....
```
If I install any python package with an `entry_point` called "mptcpanalyzer.plots", my program will find it and load it. Very practical: https://docs.openstack.org/stevedore/latest/user/index.html

**Comment by alejandrogallo** [comment]
Sounds very interesting, I agree with you, and stevedore is from openstack so it seems to be mature.
I'd be interested in this, if it can leverage out some functionality in papis. We should consider using it in papis.

**Comment by teto** [comment]
Let's say the '--delete' key worked out :)
