### ISSUE TITLE
Use stevedore to register configuration options?

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#160]
Hi @teto 

I have a question, maybe you've got a quick answer.
Could we use stevedore to register configuration options, imagine in the browse code we want 
to define options for the global project but only concerning browse, so that we can do

pseudocode
```python
stevedore.registeroptions({
 "browse-query-format": "https://duckduckgo.org",
})
```

and from other part of papis we can access them via the usual

```python
papis.config.get('browse-query-format')
```

etc...

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/papis/papis/issues/47 (use-cache option broken).

**Comment by teto** [comment]
You could have plugins that register additionnal options but I wonder if that would be helpful.

**Comment by alejandrogallo** [comment]
Yes, I'll think about this, I think it's good enough now too.

**Comment by alejandrogallo** [comment]
this is then probably not necessary. I'm closing it.
