### ISSUE TITLE
Use stevedore for pickers

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#161]
Hi @teto again! :D 

I just implemented a possible way for adding pickers with stevedore, and it's great.
I'd like you to take a look and tell me if that's what you had in mind in the first place.
I made a test with dmenu, and it works like a charm, thanks a lot.

Check it out too here
[papis-dmenu](https://github.com/papis/papis-dmenu/blob/v0.9/setup.py)

and [pick.py](https://github.com/papis/papis/blob/master/papis/pick.py)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/papis/papis/issues/122 (Picker for tags), https://github.com/papis/papis/issues/160 (Use stevedore to register configuration options?), https://github.com/papis/papis/issues/152 (How to use subfolder structure?), https://github.com/papis/papis/issues/88 (New picker, dump curses dependency), and https://github.com/papis/papis/issues/118 (Error when using vim or dmenu as picktool).

**Comment by teto** [comment]
I think you should instantiate the picker class directly rather than going through an intermediate function. You can have a look at my code https://github.com/teto/mptcpanalyzer/blob/master/mptcpanalyzer/cli.py#L190 where the entry point points at classes.

**Comment by alejandrogallo** [comment]
I'll export the picker, that's allright, but I meant also the header_formater and match_formater,
they will have to be implemented for all pickers, I think it makes sense, otherwise it can be left empty anyways. The header formater to know what kind of text must appear in the picker and in the case that the picker is flexible enough to match the query agains a text chunk that it's not the header then also.
