### ISSUE TITLE
Allow setting default subfolder per library

### ISSUE THREAD

**Issue by gaalcaras** [papis/papis#173]
I have a suggestion regarding subfolders. The way I usually work with my bibliography is first, I take some time to search for references and adding them to my reference system if they seem relevant. Then, when I have more time, I look at all the references I've added and process them (reading them, taking notes, all that good stuff).

So the way I like to setup my "folders" is pretty much like an email client. I have an inbox directory for the collecting stage, and a bunch of other directories where they go only after I've processed them.

I've tried to use `add-folder-name` to do it but it doesn't seem to work, e.g. `inbox/{doc[author]}-{doc[title]}` doesn't put the directory inside the `inbox` sudirectory. Would that be possible? Otherwise, using a `add-subfolder-name` option would be okay as well.

**Comment by teto** [comment]
I don't see why papis should be involved at all ? since the folder with unreviewd papers is well-defined and you can just add them on the go to papis.
Not sure if papis support tags, otherwise there could be an "unreviewed" tag.

**Comment by gaalcaras** [comment]
> I don't see why papis should be involved at all ?

It's just a matter of 1) saving a few keystrokes and 2) making sure papis does it for me systematically instead of relying on me remembering to type `-d inbox`. Right now I'm using an alias, which is fine.

Another use of specifying default subdirectories would be to have your references in a nice tree structure, like `{doc[author]}/{doc[year]}-{doc[title]}`. Using `fzf` or the default picker in papis is how I access documents 90% of the time, but sometimes I'll want to use a file manager like ranger, or maybe I'm on a mobile device with no terminal where a directory structure makes browsing references easier.

> Not sure if papis support tags, otherwise there could be an "unreviewed" tag.

Papis does support tags (just another field in the `info.yaml`), although they don't feel super convenient at the moment. I would also argue that it's *very* useful to have both a directory system (where one reference can only belong to one directory) and a tag system (which is many-to-many) to fit different use cases. The concept of directory maps better to my workflow than the concept of tags.

Of course, that's not a critical feature or anything, but I still think it would be useful.
