### ISSUE TITLE
improved tag management

### ISSUE THREAD

**Issue by thoth101010** [papis/papis#175]
I think that an easier tag management could be awesome to quickly navigate and sort the document list.

Maybe it would be nice to have a taskwarrior style of tag management. 

The idea is that you would use `+tag1 +tag2 …` in the `add` command to add tags, and `+tag1` or `-tag1` in queries to select tags ( the `+` tag select specific tags, and the `-` remove the tags.

However, I'm not sure if it's better, but I like this feature in taskwarrior.

Maybe there are also better options to explore to improve the tag management.

_I know it would require an huge work to implement it, and I plan to implement one day it if I find some time, but I leave the idea here to have comments and know if it make sense_

### Examples for the taskwarrior style of tag management
- `papis add +to_read +flowers […]`  would add a paper with the `to_read` and `flowers` tags
- `papis list +flowers -reviewed […]` would list all the papers that have the tag `flowers` but that havn't the tag `reviewed`

However, it would cause problems with the `papis update` command, as `papis update +flowers [query]` should add the tag `flowers` to the result of [query], but there could also be tags in query. In taswarrior, this is not a problem as the query is before the command. 
Parsing the query before the command would solve the problem (example : `papis [query] update +flowers`) but it would require to completely change the cli library just for one feature :sweat: … so it's impossible to use that workaround.

It would also be difficult to parse `-` I think.

**Comment by alejandrogallo** [comment]
As of today, this would break to much the current workflow.
