### ISSUE TITLE
YAMLLoadWarning when opening papis

### ISSUE THREAD

**Issue by capaldo** [papis/papis#176]
When opening papis, I'm repeatedly getting the following warning: 
```bash
523: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  structure = yaml.load(fd)
```

**Comment by urielz** [comment]
This is fixed in the current dev branch. If you prefer to use the stable branch, you can locally edit document.py, replace:

`structure = yaml.load(fd)`

with: 

`structure = yaml.load(fd,Loader=yaml.FullLoader)`

**Comment by capaldo** [comment]
> This is fixed in the current dev branch. If you prefer to use the stable branch, you can locally edit document.py, replace:
> 
> `structure = yaml.load(fd)`
> 
> with:
> 
> `structure = yaml.load(fd,Loader=yaml.FullLoader)`

Worked beautifully. Thank you!
