### ISSUE TITLE
FYI: Development pause

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#179]
Hi all,

I've been sick the last weeks due to an accident, that's why the development stalled.
I'll not be able to attend all issues effectively for a while, although I'm slowly recovering
and trying to push version 0.9. Do not get upset if I don't answer all your issues right away.

Happy paping,
Alejandro

**Comment by Xunius** [comment]
Wish you recover soon.

**Comment by teto** [comment]
I was wondering if a deadline had kept you busy as you seemed so keen on releasing 0.9 soon.
Take your time and recover. software can wait :) especially as a new release would result in a surge of new issues.
Yet, if you need some help to get a release out, feel free to ask, I am just not sure if https://github.com/papis/papis/pull/162 is ready and if you want some help to test :/

**Comment by bluehood** [comment]
You don't _owe_ us a release! Get better soon! To paraphrase wise @teto, free and open source hobby software can wait :smile:

**Comment by alejandrogallo** [comment]
Thank you guys, I'm feeling much better after five weeks of resting. I'll start where I left it, let's see if we can push v0.9!

**Comment by teto** [comment]
as some of my favorite casters would say "Take my energy !!" :p
Thanks for the news !
