### ISSUE TITLE
I packaged papis for conda

### ISSUE THREAD

**Issue by bluehood** [papis/papis#180]
Hi,
in case you are interested, I grew tired of using [conda](https://www.anaconda.com/) for all my python dependency management needs -- except for papis.

So I [packaged papis](https://gitlab.com/bluehood/papis-feedstock) and a few [of](https://gitlab.com/bluehood/pylibgen-feedstock) [its](https://gitlab.com/bluehood/arxiv2bib-feedstock) [dependencies](https://gitlab.com/bluehood/isbnlib-feedstock) that were not available on conda, and now papis is installable as part of a conda environment with

```bash
conda install -c conda-forge -c bluehood papis
```

I don't plan to push for adoption of the package in conda-forge (the official unofficial channel for conda packages), as I don't have time to polish the recipe to run within their CI system (not at the moment, at least), but in case you are interested I just wanted to let you know some of the work has already been done.

Cheers,
bluehood

**Comment by alejandrogallo** [comment]
Hi @bluehood ,

that is great! Thank you very much, so now it is installable as a part of `conda-forge`, right?
Should I write in the papis documentation then that papis is installable also through conda by the
command you just wrote?

And also maybe we could put this badge then?

[
![badge](https://anaconda.org/bluehood/papis/badges/version.svg)
](https://anaconda.org/bluehood/papis/badges)

Cheers!
Ale

**Comment by bluehood** [comment]
Hi,
so conda has different channels, the default channels, conda-forge (the largest non-default channel) and I also have my personal channel ("bluehood").

Papis is currently available from my personal channel, but some dependencies must be taken from conda-forge (others from the default channel), so the full command is 

```
conda install -c conda-forge -c bluehood papis
```

There is a procedure to add a package to the `conda-forge` channel but I have no time to work on it.

**Comment by teto** [comment]
@bluehood I have no idea about conda but if you open a PR to add a badge linking towards the papis package, we will accept it.

Thanks again
