### ISSUE TITLE
papis export --bibtex human readable bibkeys

### ISSUE THREAD

**Issue by ttxtea** [papis/papis#187]
Is it popssible to modify the way papis generated bibkeys during `papis export --bibtex`. Either by specifying the format or adhering to something like zotero's convention. It might be possible to postprocess this by using something like bibtool.

**Comment by teto** [comment]
yes it's possible , there is sthg like ref_format described in the doc. 
For instance I use : 
`ref-format = {doc[author_list][0][surname]}{doc[year]}`
You might need https://github.com/papis/papis/pull/168 though

**Comment by ttxtea** [comment]
Wonderful. To mimic zotero style there is the `doc[title]` variable. But is there a way to specify the first word (or even first word except if it is an article). Something like `doc[title][first word]`?

**Comment by teto** [comment]
The key is formatted via `def format_doc(python_format, document, key=""):` so you might be able to run some python code in the format. Not sure.

**Comment by avonmoll** [comment]
There's a bit more info in #114. I ended up using the following settings in my config:

```
format-jinja2-enable = True
ref-format = {{doc["author_list"][0]["family"].lower().replace(" ", "")}}{{doc["year"]}}{{doc["title"].split(" ")[0].lower()}}
```

If I'm not mistaken, all the jinja2 stuff will soon be taken out of papis. My hope is that it will be possible to plug in a custom script. For example, one that uses the first word of the title whilst ignoring stop words (like in Zotero). Of course, you could always write a script to alter `ref` "in post",   as in, after a document has been created. I'm more interested in having a `ref`-formatter script run when the document is first being added.

**Comment by teto** [comment]
yep jinja2 should go away. Not sure how you will be ble to accomplish this in v0.9 but now that the needs has been mentioned, it should be ok :)

**Comment by jessebett** [comment]
@teto I don't know if this is related to #196 but when I `papis export --bibtex` the `ref-name` is does not follow what I've specified in my config, it just gives me the automatically generated folder name as in the issue #196...

I have this in my config:
`ref-format = {doc[author_list][0][surname]}{doc[year]}`

**Comment by alejandrogallo** [comment]
Hi all, sorry for the delay, it was not voluntary sadly.
So the reference building is done in

https://github.com/papis/papis/blob/80a3b5f648b9ffe16cc66abc52567103a018ef17/papis/document.py#L149-L174

So as you see in particular, if you've got already a reference, it will not be
created on the fly whenever you do `papis export`.

I don't think it's safe to do it in general like that, instead I'd rather
put this functionality in the `papis-bibtex` script project
https://github.com/papis/scripts/tree/master/papis-bibtex. What do you think?
