### ISSUE TITLE
feedback on 0.9 branch `add --from`

### ISSUE THREAD

**Issue by teto** [papis/papis#189]
So I've been trying
`papis add --from bibtex https://www.usenix.org/biblio/export/bibtex/180723`
but this doesn't support urls yet (this would be so cool) so I did:

```
curl https://www.usenix.org/biblio/export/bibtex/180723 -o test.bib
papis add --from bibtex test.bib 
```
first of all I am not fond of the new merge system. The idea sounds good but maybe we can keep the current system until the other one is polished.

Then it doesn't parse the bibtex correctly (see the remaining `{XXX}`). I wonder if it's known and if there is already a plan to fix it (like using a 3rd party parser etc).
```

address: San Jose, CA
author: Costin Raiciu and Christoph Paasch and Sebastien Barre and Alan Ford and Michio
  Honda and Fabien Duchene and Olivier Bonaventure and Mark Handley
booktitle: 9th {USENIX} Symposium on Networked Systems Design and Implementation ({NSDI}
  12)
isbn: 978-931971-92-8
pages: 399--412
publisher: '{USENIX} Association'
ref: '180723'
title: How Hard Can It Be? Designing and Implementing a Deployable Multipath {TCP}
type: inproceedings
url: https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/raiciu
year: '2012'
```

I don't mind helping but I would like to know where to start from (master/v0.9?). Would be cool to merge v0.9 in master.
also I would like a syntax such as `papis add --from https://www.usenix.org/biblio/export/bibtex/180723` to work. Would that be ok ?

**Comment by teto** [comment]
also autocompletion for explore repeats "Examples of..."
```
$ papis explore                                                                                                                                                                                                                                          
unsorted
arxiv      -- Look for documents on ArXiV.org.
base       -- Look for documents on the...
bibtex     -- Import documents from a bibtex file Examples...
citations  -- Query the citations of a paper Example: Go...
cmd        -- Run a general command on the document list...
crossref   -- Look for documents on crossref.org.
dissemin   -- Look for documents on dissem.in Examples of...
export     -- Export retrieved documents into various...
isbn       -- Look for documents using isbnlib Examples of...
isbnplus   -- Look for documents on isbnplus.com Examples...
json       -- Import documents from a json file Examples of...
lib        -- Query for documents in your library Examples...
pick       -- Pick a document from the retrieved documents...
yaml       -- Import documents from a yaml file Examples of...

```

**Comment by teto** [comment]
and also when adding a file, it should check for similar references IMHO, in my case I was able to add 2 documents with the same `ref`.

**Comment by teto** [comment]
> first of all I am not fond of the new merge system. The idea sounds good but maybe we can keep the current system until the other one is polished.

I may have been a bit harsh. It's very convenient but mostly the palette of colors (background color) makes the output kinda aggressive.

**Comment by alejandrogallo** [comment]
> also autocompletion for explore repeats "Examples of..."
> 
> ```
> $ papis explore                                                                                                                                                                                                                                          
> unsorted
> arxiv      -- Look for documents on ArXiV.org.
> base       -- Look for documents on the...
> bibtex     -- Import documents from a bibtex file Examples...
> citations  -- Query the citations of a paper Example: Go...
> cmd        -- Run a general command on the document list...
> crossref   -- Look for documents on crossref.org.
> dissemin   -- Look for documents on dissem.in Examples of...
> export     -- Export retrieved documents into various...
> isbn       -- Look for documents using isbnlib Examples of...
> isbnplus   -- Look for documents on isbnplus.com Examples...
> json       -- Import documents from a json file Examples of...
> lib        -- Query for documents in your library Examples...
> pick       -- Pick a document from the retrieved documents...
> yaml       -- Import documents from a yaml file Examples of...
> ```

This is sadly a *feature* of `click` kind of, I would not really know how to change it.

**Comment by alejandrogallo** [comment]
@teto, you haven't been too harsh with the new interface, sometimes even myself I've got trouble making sense of it, but changing the colors might be something, I'll experiment with this option,
but the adding and updating interface we've got to clean before v0.9 can be safely released...
