### ISSUE TITLE
v0.9: papis -cc displays a warning

### ISSUE THREAD

**Issue by teto** [papis/papis#191]
```
$ papis -cc
WARNING:config:Overwriting previous configuration
```
which is a bit anxiogenic without more information. I would suggest to either remove it, make it more informative or change the log level.

**Comment by alejandrogallo** [comment]
This happens when we intend to read a configuration from the file `c`, which I agree may happen
often, and this warning is in `papis/config.py`, which should not be there, so I will put it in the entry point of papis, i.e., in `commands/default.py`.

Now the behaviour will be:
```
$ papis -cc open
Usage: papis [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-c" / "--config": Path "c" does not exist.
```
