### ISSUE TITLE
Consider storing pdfs in different location?

### ISSUE THREAD

**Issue by klaxalk** [papis/papis#194]
Hey, I am wondering whether different storage for PDFs would be possible. My use case is to have the yamls in a git repository and the pdfs in some synchronized data services (Dropbox, GDrive, etc). Adding pdfs with link is an alternative, which is currently ok, but the ability to organize pdfs automatically into the renamed subfolders would be nice.

Edit: The attachements can't be added as a link using "addto" :-(.

Sincerely
klaxalk

**Comment by teto** [comment]
what's the usecase ? why not sync everything via dropbox ? i don't think the yaml files evolve that much that they would need versioning. 
Alternatively you can create a git repository that ignores pdf files and maybe tell dropbox to ignore the .git folder ?

**Comment by klaxalk** [comment]
Hey, I would like to split it into Dropbox+git for several reasons. First, I think its just a cleaner solution. The repository with yamls can be shared and collaborated on easily with my colleagues (we use git for almost everything), without the need to clone/copy the bulk of pdfs. However, I would still like to have a synced-up folder with pdfs. My colleagues can even have a different folder with pdfs with a different subset of papers. Since the yamls are text only, git will handle them fine. Wheres Dropbox doesn't handle merges well, but it is significantly better with binary data (which will not change, only new pdf will appear or old will be deleted). I also prefer to version the yamls because I add additional custom information to the entries, such as keywords or descriptions which I would like to version traditionally.

I already made the changes to papis which allow me to do this. I utilized the list of "dirs' from the config file (if I am not mistaken, currently only the first entry is used). I treat the first "dir" is the primary one for yamls and the second as the secondary one for pdfs. I also updated the addto command to support:
a) adding it directly to the primary folder (original functionality),
b) adding it to the secondary folder and creating a symlink to the primary,
c) adding it to the secondary folder and pasting the path directly to the yaml (which makes more sense to me than a link).

I will polish it to the state, where the original functionality is preserved. I will let you know if it works for me ;-). Will you be interested in a pull request?

**Comment by teto** [comment]
Iam just a plain user like you so my opinion doesn't matter much :) 
don't b and c) imply that all users share the same directory structure ? what about linux vs windows paths ?
I believe a solution should leave the yaml untouched. the function to retrieve the pdf loading/writing could be changed to use the alternative folder.

**Comment by wbrandenburger** [comment]
Hi,

currently I am adding further functionality to papis and testing it with pytest in windows. For my purposes, e.g., I need the same functionality described in by [klaxalk](https://github.com/papis/papis/issues/194#issuecomment-515746441). I think also that it is a "cleaner" solution.

**Is there a interest to discuss a solution for that use case, which can be directly included in papis**?

**Comment by teto** [comment]
(sym)links sound troublesome if we target windows as well (and few users seem interested in that possibility).
The simplest approach I can think of is write a relative path to the pdf, and prepend a "pdf/binary folder" value configured in the library config before accessing it. Would that satisfy every usecase ?
I don't think papis folder change names once a document is added but I could be wrong.

**Comment by alejandrogallo** [comment]
Hi

I just realized that there are better tools for this matter.
I don't think it is very beneficial for papis users to be able to do this
when there are extremely efficient tools out there that can do this much better
than a possible implementation on papis.

In particular I'd recommend you to take a look at
[`git-annex`](https://git-annex.branchable.com/).

I think we should focus on how to enable these kind of application to play
well with papis.

With `git-annex` you could have the pdfs anywhere, as in some in harddrive `A`,
repository `B` etc..

I'd like to know your thoughts about this. For the moment I marked the issue
as `wontfix`.
