### ISSUE TITLE
add-name referenced in docs but appears to be deprecated

### ISSUE THREAD

**Issue by jessebett** [papis/papis#197]
The description for `add-file-name` references `add-name` but it appears this was deprecated in favour of `add-folder-name`. Is this correct? `add-name` does not appear in the descriptions of configuration options.

https://papis.readthedocs.io/en/latest/configuration.html#config-settings-add-file-name

**Comment by wbrandenburger** [comment]
The option add-name does not appear in source code regarding papis v0.8.2 as well as v0.9. These observations may support your assumption that the setting was deprecated.

**Comment by alejandrogallo** [comment]
Hi all,
in the CHANGELOG.md there is the description of the change of naming convention.
Sorry for the delay guys, please if you change something in the future let's try to put everything in the CHANGELOG. IMO the new naming convention is cleaner.
