### ISSUE TITLE
Papis for Windows

### ISSUE THREAD

**Issue by wbrandenburger** [papis/papis#203]
Hi,

currently I am adding further functionality to papis and testing it with pytest in windows. For my purposes, e.g., I need the same functionality described by [klaxalk](https://github.com/papis/papis/issues/194#issuecomment-515746441).

Anyway, for the use in windows there is a update necessary due to several problems:

- bug in search of documents regarding issue #182 and #165 (currently fixed by my own)
- functions from `os` do not proper deal with windows and linux paths, it is preferred to use functionality of package `pathlib` when building paths (currently fixed by my own)
- creation of links does not work properly in windows (todo)
- the opening of user defined tools, especially with marks, does not work properly in windows (currently fixed by my own)

Further tests, e.g, with pytest show that papis works besides of these problems excellently in windows. I appreciate that piece of work and have been using papis as my main literature, document and bookmark manager after I had implemented only a few additional functions.

Is there a pull request for windows user meaningful?

**Comment by teto** [comment]
go ahead, make sure to create several small PRs and not a big one. Does the pathlib change remove support for older python papis could support ?

**Comment by wbrandenburger** [comment]
I think also that PR's with a few changes are more meaningful to establish a version which works on all considered os. The pathlib package is intended to work properly with linux and windows paths, only the os.path functions will be replaced. That is not much effort.

Besides of that, the design of opening functions `edit`, `open` and `browse` should be redesigned, in order to get a cleaner solution which is more understandable. Additionally the Document Class and some further functions, too. That is a little bit more than some small PR's. I have restructured all mentioned functions and have preserved the existing functionality so far. There is another proceeding 
favourable?

I am totally interested to invest a little bit more time to work with that repository. Especially the integration in visual studio code as extension is not inconvenient. In windows there are not really  convincing latex editors. Whereas visual studio code shows meanwhile several strengths. A deeper interaction with papis would simplify my work. 

Is there a possibility to become a contributor? I am not uninterested to help with pull requests and answering issues?

**Comment by teto** [comment]
Your post lists many things, it might be best to focus on small things that can be accomplished first before redesigning the full UI (which I really dislike).  papis'API makes it easy to experiment out of tree (I would like to implement some alternative based on fzf or cmd2 but don't have the time).

pathlib was introduced in python 3.4. That would make us drop support for python 3.3, which is fine in my book so please go ahead.

papis author has little time right now, and so do I so any help is welcome. but it would have to deal with small changes first (easy to review).

**Comment by alejandrogallo** [comment]
Hi @wbrandenburger 
This sounds nice, right now it's @teto and me on it, me sadly because an accident I have been on and off on papis, but now I'm coming back gradually. I think you're in Viena, if that's the case let us meet one day if you want.
Otherwise as @teto said, it's best if we do small pull requests with different points, you can just submit pull requests with features, and we will review them.

**Comment by wbrandenburger** [comment]
Hello, thank you a lot for your answers.

First I want to say that, I have been developing in PowerShell Core two main packages (published in PowerShell Gallery) as a preliminary work for the integration of Papis in VS Code and to simplify the use of different libraries with different virtual environments in Windows (the last issue is more a aspect when developing Papis) as well as dealing with the input of data. Besides a Papis Wrapper (PSPocs) it is a virtual environment wrapper (PSVirtualeEnv), with additional stuff. I'm really surprised, that there are people who have been downloaded the second package so far, even though not completely error-free but stable.

I have developed papis the last weeks and I changed a lot, it is know a highly experimental version of papis. I'm playing heavily with your work, which is a appreciating fundament. Now it is up to me, to submit small pull request, thank you for the opportunity. Because of the extensive changes (the list is a little bit longer, *cough*, than I described above ) it is know possible to evaluate the most important things to work on, which may be discussed briefly?

I'm working in Munich, that is not really close to Vienna, but I would appreciate a short talk via team explorer or skype?

**Comment by teto** [comment]
Do you have links towards your different projects ? I am curious as to what's their purpose.

I prefer to work async but I think there are 2 things we can distinguish here:
1/ the required changes to have papis work on windows
2/ the changes required to ease the integration of papis with your projects

2 can take time as we discuss different approaches while 1/ should progress steadily and help everyone out (like the pathlib change). Waiting for your PRs :) !

**Comment by wbrandenburger** [comment]
Surely,

- PSVirtualEnv, [GitHub](https://github.com/wbrandenburger/PSVirtualEnv) and [PSGallery](https://www.powershellgallery.com/packages/PSVirtualEnv/0.5.7), which simplifies the work with virtual environments, their installation, development, etc.,
- PSPocs, [GitHub](https://github.com/wbrandenburger/PSPocs) and [PSGallery](https://www.powershellgallery.com/packages/PSPocs/0.4.7), which simplifies the work with papis, (currently with functions of my fork of papis), e.g. creating new libraries, adding bunch of documents, setting properties, etc.

Additionally I'm working on another module (SciProfile)[https://github.com/wbrandenburger/SciProfile], which has the focus to share my settings, libraries and supplementary automatisms when working in a team. That profile does include a complete installation of all modules and corresponding settings. 

The module SciProfile is certainly experimental but PSVirtualEnv works fine, and PSPocs has been already a facilitation.

Thank you a lot for the discussion. To have the chance to benefit from further developments of papis your suggestions can be considered as highly meaningful ;). I will begin to share my developments for a properly working papis version on windows in the next, at the latest the week after next. 

Thank you!

**Comment by alejandrogallo** [comment]
Feel free to reopen this when there's some updates!
