### ISSUE TITLE
Customize bibtex cite keys

### ISSUE THREAD

**Issue by chenpeizhi** [papis/papis#204]
I wonder whether there is any plan to support customized bibtex cite keys. Many research groups use specific formats for cite keys, e.g. [FirstAuthor][Year][issue]_[page]. It would very be helpful if papis can automatically generate customized cite keys as many other bibliography managers do.

It would be ideal if one could specify the cite key format in the config file and let papis generate the cite keys from the yaml key fields upon exporting. In this way, one would be able to use different cite key formats for different manuscripts.

**Comment by teto** [comment]
you might want to lookt at https://github.com/papis/papis/issues/187

**Comment by chenpeizhi** [comment]
Thank you! This feature is very helpful.
