### ISSUE TITLE
Add options not working from config file

### ISSUE THREAD

**Issue by JBlocklove** [papis/papis#205]
I have 3 "add" options set in my papis config file:
```
add-folder-name = {doc[title]} - {doc[author]}
add-file-name = {doc[title]}
ref-format = {doc[author_list][0][surname]}{doc[year]}
```
and none of them seem to do anything.

I mostly add files using `--from-doi` or `--from-bibtex` and I always get the same result: the folder is a hash followed by the author's name (if it was able to pull it out, which can be hit or miss from the doi). The file name stays the same, but with a second .pdf extension added (related to #151). And the ref-format always ends up being the doi until I change it.
If I change other things in my config file, those changes propogate through, like changing my default library recently, but the add options seem to have no effect.

If I run the `papis config` command and give it `add-file-name`, `add-folder-name`, and `ref-format` it shows me that they are set to the right thing.

Also, in regards to the double .pdf extension, #151 would indicate that adding the `add-file-name` configuration should fix that, but it seems to have no effect.

EDIT: Slight amendation - it appears that setting `file-name` rather than `add-file-name` fixes the .pdf issue and sets the file name correctly when adding. This is not reflected properly in the documentation. `folder-name` rather than `add-folder-name` seems to have no effect, though.

**Comment by avonmoll** [comment]
Per my latest response to #196, it appears that the proper configuration setting for folder names is actually `add-name`. The documentation seems to apply to versions > 0.8.2. The settings `add-file-name` and `add-folder-name` are definitely used in later versions.

**Comment by JBlocklove** [comment]
Fantastic, that fixed my problem without a hitch. So it seems like the issue is mostly one of the documentation being out of sync with the current stable release, rather than missing/broken functionality.

**Comment by alejandrogallo** [comment]
Yes, exactly, the configuration options on the documentation is of the master branch, we should in the future make it version dependent, it would help a lot, I'll look into how this is done in rtd.org.
