### ISSUE TITLE
Get papis to appear similar to how its demo'd in the readme

### ISSUE THREAD

**Issue by capaldo** [papis/papis#206]
For some reason, my library does not appear anything like whats shown. Can someone share the config thats necessary to attain the same appearance?

<img src="https://camo.githubusercontent.com/71234a30742a266fd57d4d793cda5f5f2840532e/68747470733a2f2f70617069732e6769746875622e696f2f696d616765732f7375706572717569636b7374617274312e737667"/>

**Comment by teto** [comment]
what version ? what is different ?
papis is currently undergoing lots of changes.

**Comment by capaldo** [comment]
> what version ? what is different ?

I'm currently running the most up to date version.

**Comment by alejandrogallo** [comment]
Could you provide a screenshot?

**Comment by capaldo** [comment]
<img width="1280" alt="window 2019-09-30 @1929" src="https://user-images.githubusercontent.com/41103209/65923912-a4ce9380-e3b8-11e9-88fb-6ed5f3606bfa.png">

**Comment by alejandrogallo** [comment]
I think the format that you have in your configuration file is telling papis to do this.
Take a look at the documentation
[here](https://papis.readthedocs.io/en/latest/configuration.html#config-settings-header-format).

Can you also tell me what the contents of the files

```
~/.papis.conf
~/.config/papis/config
```

are? Probably it is set there.

**Comment by capaldo** [comment]
This was in fact a configuration issue. Thank you.
