### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by noahhdf** [papis/papis#209]
```, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.```

**Comment by marty-oehme** [comment]
This seems to be a duplicate of issue #176 and should be doable through the [methods mentioned](https://github.com/papis/papis/issues/176#issuecomment-498350818) - either by switching your installation to the dev branch or fixing the line in question yourself.

**Comment by noahhdf** [comment]
ah correct, thanks
