### ISSUE TITLE
Rofi GUI open wrong file, sometimes

### ISSUE THREAD

**Issue by nico202** [papis/papis#21]
Hi, I don't know how to debug this right now. However, opening a file with the gui --rofi not always open the correct paper (both for edit/show file) while the vim GUI for the same entries open the correct file.

I'll look if I can reproduce this with a smaller library

**Comment by alejandrogallo** [comment]
Thanks, I'll keep an eye on it, the thing is that I do not use the rofi gui so much, and I was thinking
about reimplementing it in form of a papis external script, but I'll use it now more regularly to see if 
I also notice something weird.

**Comment by alejandrogallo** [comment]
I'll go ahead and close this issue for the time being, we can open it again when
we find some similar behaviour again.
Thanks!

**Comment by nico202** [comment]
I'm still experiencing it, I'll try to find out a simple way to reproduce and why it's happening tomorrow. The issue should be re-opened

**Comment by alejandrogallo** [comment]
Ok! Let me know!

**Comment by nico202** [comment]
Just this two:

```
author: Ritterbush, Jon
title: Supporting Library Research with LibX and Zotero
year: '2008'
```
```
author: Xue Lu and Niall Adams and Nikolas Kantas
title: On Adaptive Estimation for Dynamic Bernoulli Bandits
year: '2017'
```

are enough to make rofi gui go cazy (it show 4 elements)
