### ISSUE TITLE
Request for Comment: thoughts on sorting documents

### ISSUE THREAD

**Issue by j-c-w** [papis/papis#210]
Hi,

I'd like to implement sorting of results (e.g. with `papis open "*"`), so that results can be sorted on e.g. author name.

Eventually, I'd like to implement add a "time added" field, so that papis could sort by recency.  That's my use-case for this anyway.

Regardless, there seems to be some choice for how best to sort.

I see two ways:

1.  Press <C-s> and have a field appear in which the user can enter a field (with a prompt).
2.  Just type "sort:<field> <rest of query>" into the search bar.

I'm leaning towards 1, but am keen to hear your thoughts on it  and whether there might be another way to do this.

Thanks,

Jackson

**Comment by teto** [comment]
That would be a useful feature. Maybe we can focus on sorting by author name first (the "time added" can come afterwards).
I believe you could add a `--sort` option to papis/commands/open.py and/or pass a sort flag in base.py as well `def query(self, query_string [, sort]):` depending on if some backends can leverage it (can whoosh sort results natively for instance ?).

I think we should only sort according to one field, papis is simple, let's keep it simple :)

**Comment by j-c-w** [comment]
Yep, a flag makes sense, I'll proceed that way.  Thanks for the feedback.
