### ISSUE TITLE
Request for comment: git commands for multiple repos and moving documents between libraries

### ISSUE THREAD

**Issue by j-c-w** [papis/papis#211]
Hi all,

Two things I would like to be able to do are:

(1) Move a document between libraries.  I'm envisioning something like: `papis mvlib lib1 "document search" lib2 (with some flags like --all)

(2) Similarly, I'd like to be able to run a single git command in all libraries at the same time.  As-is, if I use git for backup, ISTM that papis scales quite poorly with the number of libraries, as I have to (for example) `papis -l <lib> git pull` etc. to all of them.  I'd like to add a command like `papis gitall <git command>` that can run in all libraries at once.

Now, both these require new base-commands for relatively simple functionality.  I can see alternatives.  For (1), I could add a --libraries <lib1> <lib2> flag to `papis mv`, which might be simpler.  For (2), I could add a --papis-all flag to `papis git` which would run the following git command in all libraries.

I'm keen to hear whether you think it is better to have a new command or to add a library related flag to the existing commands for this.

Jackson

**Comment by teto** [comment]
I agree 1) makes sense.
2) can easily be scripted without papis support.

If you look into setup.py, you can see that all commands are implemented as plugins (under the entry point `papis.command`). So both of your suggestions could be implemented as plugins without any changes into the core.
The plugin system is https://github.com/openstack/stevedore

**Comment by j-c-w** [comment]
OK.  I currently script 2, and  looking at the structurre of the library opening functionality that might be the best way to leave it.

I'll take a look at doing both of these with the plugin system when I have some time, thanks.

**Comment by teto** [comment]
In fact both can be plugins. Feel free to ask if you have any problem. Basically the plugin system works like:
you create your own python package whatever way you want, just you need to reference the revelant code in your setup.py:
```
    entry_points={
        'papis.command': [
            "gitall=your_package:gitall_cli",
        ]
    }
```
