### ISSUE TITLE
Should add `papis bibtex` to the papis core?

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#218]
Since most people are going to use `papis` for writing papers and everything,
I was wondering if people should want a dedicated command (which is already in `papis/scripts`)
for bibtex, should I add it to the main papis core ?

**Comment by teto** [comment]
I am not what you are talking about ? I don't see anything in papis/scripts

**Comment by alejandrogallo** [comment]
I just did it, and I think it will make sense to do it like this.
