### ISSUE TITLE
Papis synchronizes between multiple machines poorly

### ISSUE THREAD

**Issue by j-c-w** [papis/papis#219]
Hi,

I have two machines, synchronized with a git repository.  Both use whoosh as a backend.

If I add a document on one, `papis add ...` and the push `papis git add ... papis git commit ... papis git push ...` and then on the other run:

`papis git pull`, and then `papis git open "*"`, I can't see the document, presumably because it is not indexed properly with whoosh.

My 2c is that there needs to be a check when opening the database that the underlying filesystem contents have not changed: if so, everything needs to be re-indexed.  I'm not sure how strong this check should be.  Perhaps it should just hash the output of `ls` (which would be fast), but that will miss issues where one of the .yaml files is updated.  A hash of every single .yaml file might not scale very well (I have not tested).

Another approach would be to add a `papis reindex` command that rebuilds the database.

I do't currently have time to fix this, I'll make a note on the issue if I start working on this.

Jackson

**Comment by teto** [comment]
I use `papis --cc` whenevenr I need to regenerate the index. Maybe exposing the implementation would make sense in this scenario (with a  `papis db` command) as people know better when to regenerate the DB.
Users can edit everything outside papis (so no stateful solutions) and cross-platform stateless solutions might be too complex for now.

**Comment by j-c-w** [comment]
Whoops, my bad.  Thanks for pointing this out.
