### ISSUE TITLE
papers not found after git synchronisation

### ISSUE THREAD

**Issue by ttxtea** [papis/papis#220]
Attempted to use the wonderful [git workflow](https://papis.readthedocs.io/en/latest/git.html) to sync article databases. `papis git pull` in a library folder results in `fatal: not a git repository (ar any of the parent directories): .git`. Using git directly without papis works fine.

However evocing `papis -l mylib open` only shows the articles that were added locally, but not the ones that came from a git pull.

I suppose there needs to be something to tell papis to update this information. On a related issues, if one deletes a folder from `mylib` to remove an article (propably should not be done) this also does not update or change the list shown with `papis -l mylib open`.

**Comment by alejandrogallo** [comment]
Hello @ttxtea,
you've got to clear the cache. At the moment papis cannot know if something changes in your library directory since it does not monitor it.

https://papis.readthedocs.io/en/latest/database_structure.html#clearing-the-cache
Cheers!

**Comment by ttxtea** [comment]
Perfect, thanks a lot! That does it.
