### ISSUE TITLE
YAML Load Warning: Calling without loader specified is depreciated.

### ISSUE THREAD

**Issue by ddefranza** [papis/papis#224]
I consistently get the warning:

`YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  structure = yaml.load(fd)
`

Using Python 3 in Debian Buster.

This should be a relatively easy fix by specifying the loader.

**Comment by teto** [comment]
please see https://github.com/papis/papis/issues/209

**Comment by teto** [comment]
feel free to reopen if the previous issue didn't  help.

**Comment by ddefranza** [comment]
I followed the methods [described here](https://github.com/papis/papis/issues/176#issuecomment-498350818), which solved my problem. Thanks!
