### ISSUE TITLE
Export notes file

### ISSUE THREAD

**Issue by jessebett** [papis/papis#225]
Is there any way to export the notes file using the `papis export` command?

This is related to https://github.com/papis/papis-vim/issues/4  towards my desired workflow that integrates vimwiki (in particular, the diary) with papis. I would ultimately like to use `papis-vim` to quickly query my papis library, and paste a formatted reference to the document (not just the current latex `\cite`) and have that also be a markdown link to the notes file. 

At this moment I don't know how to access the notes file except through `papis edit -n`.

**Comment by alejandrogallo** [comment]
Actually I was thinking of reviewing a little bit the `list` command, if it makes a lot of sense.
I've pushed a cleaning-up and consistency commit right now, you can check it out and tell me.
You can do now the following

```
papis list --all --notes einstein
```
this will print out the notes for all documents matching `einsten`, if the files exist.

**Comment by jessebett** [comment]
@alejandrogallo this is not working as intended on the current version installed via `pip`.

For instance, I can create a notes file with `papis edit -n query`. 
Then I get `WARNING:cli:edit:The document selected has no notes attached,
creating a notes files`
I edit and then save the notes file, and it is given when I rerun `papis edit -n query` so papis is aware of it.

However, when I run `papis list -n query` it returns nothing.

**Comment by jessebett** [comment]
I was able to fix this by clearing the cache..
