### ISSUE TITLE
Version 0.9 comments

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#226]
Tests are passing, I'd like to release finally version 0.9.
The only thing really delaying the whole process is:

- [x] Update the projects relying on papis:
  - [x] `papis-dmenu`
  - [x] `papis-rofi`
  - [x] `papis-zotero`
  - [x] `papis-scihub`

- [x] Remove `jinja` support.
- [x] Windows support, is anyone willing to make sure that
  papis works on Windows? If I have to do it myself
  it will take some more time. (issue #182)

- [x] I guess the importer mergin `tui` is ok for everyone,
  so about the user experience I assume it's usable for
  `v0.9`.

Things that can be done _after_ release are:
- [ ] Review changelog (`CHANGELOG.md`) and update some documentation
  - [ ] Update the git workflow.
  - [ ] Document the new plugin infrastructure.
  - [x] Partially document the new `papis-bibtex` command.

**Comment by wavefrontshaping** [comment]
Why removing Jinja support? I used it heavily as it was the only way I found to get the filename I wanted (first word of the title + year + first authors family name) and also to handle some peculiar stuff (like the fact that the authors sometimes have "family" sometimes "surname").
Is there an alternative or am I doomed to use an old version?

**Comment by alejandrogallo** [comment]
this was done during the rewrite of the plugin architecture.
The implementation of a `formatter` is a todo issue right now.
So Jinja should be supported in the future, specially if some people like
you are using it or rely on it.

In my opinion the points to be done are the following right now

- How should the API of a formatter look like in python.
  I guess something like

```python
import papis.formatter

# this will be Jinja formatter, or the python one etc.
fmt = papis.formatter.get()

formatted_string = fmt(doc, papis.config.getstring("author-style-fmt"));

```
  but maybe it's a good idea now to thing about the main use cases.

- Implement it also using the `papis.plugin` and `stevedore` architecture
  just like the explorers etc.
  That way we will be able to create a separate package
  `papis-jinja` that only has this formatter in it.

This was the main consensus, and also the jinja support was specially removed
because it was quite ugly coded, since of course it is also used in the database
for query etc. Therefore the API thing it's quite important, it is not difficult
but it has to be done nevertheless.
