### ISSUE TITLE
Better error message if library folder doesn't exist?

### ISSUE THREAD

**Issue by chiraag-nataraj** [papis/papis#227]
Right now, if the library folder doesn't already exist when attempting to add a file, papis will crash. It might be better to raise a more informative error or, better yet, just create the directory?

**Comment by alejandrogallo** [comment]
Hi, about the creating the folder, we decided not to do it, it used to be the case before.
About the program crashing, I agree. 
Thanks for the feedback.

**Comment by alejandrogallo** [comment]
I improved the error messages, now it should be much more terse, many thanks!
