### ISSUE TITLE
document[X] returns a string whatever the supposed type of X

### ISSUE THREAD

**Issue by teto** [papis/papis#229]
papis 0.9 is now available in nixos master.

I've had this error with 0.9:
```
papis addto -f ~/Downloads/paper25.pdf "Modeling TCP"
INFO:addto:[CP] '/home/teto/Downloads/paper25.pdf' to '/home/teto/papis_db/bba9771fd71a461451f0befd8a3c41d8-padhye-jitendra-and/paper25.pdf'
Traceback (most recent call last):
  File "/run/user/1000/tmp.aIJoOQ1n8A/bin/papis", line 11, in <module>
    load_entry_point('papis', 'console_scripts', 'papis')()
  File "/nix/store/a4mk5bylfrlb92dgskg6ihnrdgvm26qd-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/a4mk5bylfrlb92dgskg6ihnrdgvm26qd-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/a4mk5bylfrlb92dgskg6ihnrdgvm26qd-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/a4mk5bylfrlb92dgskg6ihnrdgvm26qd-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/a4mk5bylfrlb92dgskg6ihnrdgvm26qd-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teto/papis/papis/commands/addto.py", line 114, in cli
    return run(document, files)
  File "/home/teto/papis/papis/commands/addto.py", line 81, in run
    document['files'] += new_file_list
TypeError: can only concatenate str (not "list") to str
```
the `files` component is absent of the info.yaml so the
```
    def __missing__(self, key):
        """
        If key is not defined, return empty string
        """
        return ""
```
in document returns a string.  @alejandrogallo I don't know how you want to approach that, special case __missing__ for "files" for instance ? I wonder if we wouldn't be better off having Document being a dataclass instead of a dict. It would allow mypy to run typing checks (files is a list) and prevent this kind of errors (which I suppose there are other in the code).

As I was going through the documentation https://docs.python.org/3.5/library/typing.html I realized there was no doc for 3.3 and 3.4. Seems like both reached end-of-life status. Could we require 3.5 so as to enforce some static typing ? not everywhere but for the Document class at least. I bet it would catch quite a few mistakes.

**Comment by teto** [comment]
(note to myself: it seems papis add --from doi 10.1109/INFCOMW.2015.7179403
 --file-name ~/Downloads/mptcp-GI15.pdf doesn't add the file either. I can fix
 it myself but not at the moment, a bit busy.)

**Comment by capaldo** [comment]
> (note to myself: it seems papis add --from doi 10.1109/INFCOMW.2015.7179403
> --file-name ~/Downloads/mptcp-GI15.pdf doesn't add the file either. I can fix
> it myself but not at the moment, a bit busy.)

Its the `addto.py` file causing issues right? Maybe I can give it a crack if the maintainer is open to it.

**Comment by alejandrogallo** [comment]
Hi teto, about the 
```
papis add --from doi 10.1109/INFCOMW.2015.7179403
--file-name ~/Downloads/mptcp-GI15.pdf
```
command, it will not add the file, since you're telling him to add from doi and with a `name` of a path.
In order for this to be ok it should be

```
papis add --from doi 10.1109/INFCOMW.2015.7179403 ~/Downloads/mptcp-GI15.pdf
```
or
```
papis add ~/Downloads/mptcp-GI15.pdf --from doi 10.1109/INFCOMW.2015.7179403
```

Likewise the command
```
papis add ~/Downloads/mptcp-GI15.pdf 10.1109/INFCOMW.2015.7179403
```
would work.

I mean, we have to document this better probably...

**Comment by alejandrogallo** [comment]
About the python version of 3.5, I guess you're right.
Would it really improve the quality? I guess the static checking of `mypy` and related tools would be a life safer yes. Maybe we should do it for `v.0.10`, I agree.
