### ISSUE TITLE
add --from-isbn

### ISSUE THREAD

**Issue by nico202** [papis/papis#23]
It would be nice to be able to add books given their ISBN, like it's possible to use PMID for papers. Zotero does this with they "magic add" tool

**Comment by alejandrogallo** [comment]
Yes, this will be done, and it is to some extent already there, throught the service isbnplus.org.
Right now what you can do is to do magical

```
papis update --auto -i
```

I'll try to test this using isbnplus, however I'm already working on the BASE
interface [link](https://www.base-search.net/) and I have been already talking to people there,
however as always the time is a problem.

**Comment by nico202** [comment]
OK thanks!

Yes I keep opening lots of issues because I'd like to track what IMHO is important to be able to fit in all my needs and finally switch completely over to it. I can't find a roadmap or something else then the todo list on the readme, so I open issues. But it's not to put pressure on you. I'd also like to help, and knowing what you are already working on would be useful. Is there such a place?

**Comment by alejandrogallo** [comment]
Hello Nicolo, sorry for the delay, it is true that we should have something like a rodamap file or something, the TODO's are quite vague and hard to understand for external people wanting to contribute like you. Do you think a TODO/Roadmap file, where these things accurately and explicitly (with hints for the code) explained is would be helpful for people like you?
Maybe also open a channel in irc ??
Again I thank you very much for your great suggestions and work!

**Comment by alejandrogallo** [comment]
I have added a first version for the ROADMAP
in the file ``ROADMAP.md``, more points are to come!!
