### ISSUE TITLE
Make papis use terminal color scheme

### ISSUE THREAD

**Issue by gipert** [papis/papis#231]
Papis currently uses for the TUI his own colors instead of my terminal's color scheme. How do I change this behaviour? Not clear to me from the docs...

Thanks

**Comment by alejandrogallo** [comment]
can do

**Comment by gipert** [comment]
cool

**Comment by gipert** [comment]
Well, I actually discovered that I can play with the `header-format` setting and use `ansiblue` instead `blue` etc to actually make use of my colorscheme. This solves the issue from my point of view.

Another question: is it possible to make use of conditional expressions in the `header-format` setting? Let's say I want to display the DOI with `.. <fg>{doc.html_escape[doi]}</fg> ...`, if present, and the arXiv ID, when the first is not available. Is there a way to achieve this? Such a thing would be helpful in general to make things more robust. Another example: right now I was trying to display the first author in the format `Surname, N.` with the following:
```
{doc[author_list][0][family]}, {doc[author_list][0][given][0]}.
``` 
But I obviously get an error if the author_list is not defined in `info.yaml`.
