### ISSUE TITLE
First-author from multiple and separated author field and --format python

### ISSUE THREAD

**Issue by jessebett** [papis/papis#233]
When I pass a template into papis, is it not calling out to python string formatting?

This is related to #90, where I want to get the first author for a format that looks like `(First Author et al., title, year)`

However, `doc[author_list][0]` does not work if only the `author` field is populated with `and` separated `author` field (which is what you get from importing bibtex provided by arxiv... The above will give an index error.

I see that there is a multiple-author format utility. Should I be configuring that to expect `and` separated author fields? 

Alternatively I tried do something like 
`papis list --format '{doc[title]} {doc[author].split(" and",1)} et al. ({doc[year]})'`
to use python formatting to split the first author off. However, I get the error 
`'str' object has no attribute 'split'`. 

Does `--format {}` not send the command to python for string processing? If yes, any idea why string splitting wouldn't work?

**Comment by jessebett** [comment]
Having updated papis I realize that my entries from previous versions do not have `author_list`. I will try updating my papis folder with the new version and see if it correctly populates these fields.

**Comment by alejandrogallo** [comment]
If there is some update about this, feel free to reopen the issue.
