### ISSUE TITLE
Import of bib-files not working

### ISSUE THREAD

**Issue by cristobaltapia** [papis/papis#239]
Hi,
I was following the steps described in [0] to import ''bib'' files, but the script `papis-zotero` does not work anymore. Is there a new recommended way to do this?

Thanks  

[0] https://papis.readthedocs.io/en/latest/importing.html

**Comment by alejandrogallo** [comment]
Hello Cristóbal,

yes the documentation is sadly a little bit outdated.
There is now the separate project `papis-zotero`
which you can find at the following url

  https://github.com/papis/papis-zotero

there you find the updated scripts and project.

We should update the documentation, oh boy, so much to do ;)

Cheers,
Alejandro

**Comment by cristobaltapia** [comment]
Oh, thanks for that reference!

And don't worry, I now it's not always easy to find the time for an open source project ;)
