### ISSUE TITLE
Upgrade dependencies?

### ISSUE THREAD

**Issue by JP-Ellis** [papis/papis#242]
I recently upgraded papis for Arch Linux to v0.9; however, this has caused a number of issues as Arch Linux packages are usually up to date, and for some reason papis puts upper limits on a number of dependencies.  In particular:

- [ ] `python-slugify<4,>=1.2.6` -- Is there a known incompatibility with version 4?  Looking at the [`python-slugify` changelog](https://github.com/un33k/python-slugify/blob/master/CHANGELOG.md), the only change between v3 and v4 is that they've dropped some older Python versions.
- [ ] `lxml<4.3.5` -- Again, the main breaking change for v4.4 I can see is a drop in support for older Python versions, and one deprecation.
- [ ] `prompt_toolkit<3` -- This seems to be a bigger change, but perhaps work towards `v3` should be considered?  (On Arch Linux, the latest version is still `2.0.10`, so I'm guessing the change to v3 is not completely trivial).
- [ ] `isbnlib<4` -- This is not an issue for now as `v4` hasn't been released; but is there a reason to preemptively be incompatible with the next version?

It appears to me, from the limited testing I have done, that removing the upper restrictions on the versions does not introduce any regressions (but this is from very limited testing).

**Comment by jghauser** [comment]
I recently made an [Arch package ](https://aur.archlinux.org/packages/papis-git/) for the Git version of papis. The `isbnlib` package for Arch is at 3.10, and thus beyond the upper limit defined in papis (<3.10). Is there a reason that this upper limit wasn't removed? From my (very cursory) testing, papis seems to work just fine with 3.10.

**Comment by alejandrogallo** [comment]
I'm not really sure anymore of which version is the best for papis
features right now.
I vaguely recall some problem with python version 3.5.3 with isbnlib,
but I'm not sure anymore. Which python version have you tested it with?

**Comment by jghauser** [comment]
I'm on Python 3.9.1

**Comment by alejandrogallo** [comment]
Oh, we're not testing papis now for python 3.9, I guess we should
update the CI to test for it too, I'm normally using 3.6 up to 3.7.

**Comment by alexfikl** [comment]
Just to add to the isbnlib issue. I've also been using papis with 3.10+ and it's working just fine.

From what I remember the incompatibility was just that passing `None` as the default service didn't work anymore, but that was fixed in 42f7073a9c73e888a88910cc7e9e31540eae30b3.

**Comment by alejandrogallo** [comment]
Ok Thanks Alex, I'll lift the restriction and add python3.9 in the CI
integration, let's see what happens ;)

Alex Fikl <notifications@github.com> writes:

> Just to add to the isbnlib issue. I've also been using papis with 3.10+ and it's working just fine.
>
> From what I remember the incompatibility was just that passing `None` as the default service didn't work anymore, but that was fixed in 42f7073a9c73e888a88910cc7e9e31540eae30b3.


-- 
Alejandro Gallo

**Comment by alejandrogallo** [comment]
It seems to work!
