### ISSUE TITLE
Support for web sites items natively.

### ISSUE THREAD

**Issue by marcofavorito** [papis/papis#245]
## Feature request

Is there a way to support websites (and more in general any URLs) natively?

That is, `website` would be a distinct type, that must specify an `url`. When `papis open` is called on a `website` type, it retrieves the `url` field and opens it with the specified 'viewer' for that (e.g. `firefox`).

the idea is, once it has been added, it can be exported as bibtex like:
```
@misc{id,
  author = {An Author},
  title = {{A Title}},
  howpublished = "\url{http://an-url}",
  year = {2008}, 
  note = "[Online; accessed 19-July-2008]"
}
```
notice the `note` that should be generated automatically by Papis when the item is added (if not specified by the user).

If it is not in the roadmap, how can I implement such behaviour?

I'm new at using `papis`. I apologize in advance if the question is not relevant.

**Comment by marcofavorito** [comment]
I've just discovered that `papis browse QUERY` automatically looks for the `url` key into the matched `info.yaml` file, so that part of the issue is solved. However, the issue tries to be a more general observation on the native support for the web page type.

**Comment by teto** [comment]
seems like a bookmark manager :p (see https://github.com/jarun/Buku). Seems like it would need some browser support/extension to work ?

**Comment by michal-h21** [comment]
What about https://github.com/papis/papis-zotero? It supports arbitrary websites using Zotero connectors.

**Comment by marcofavorito** [comment]
> seems like a bookmark manager :p (see https://github.com/jarun/Buku). Seems like it would need some browser support/extension to work ?

@teto thanks a lot for the suggestion! I didn't know the Buku project.
However, I'm not looking for bookmarking. I realized that often it is needed to cite resources that can be identified only by their URLs (e.g. think about blog posts or articles, that have not a DOI).
What would be helpful for this use case is to make easy the categorization of such kind of item and then to export it in Bibtex format in order to use it in a bibliography.

@michal-h21 thank you for the hint! Will surely look into `papis-zotero` :-)

**Comment by alejandrogallo** [comment]
Hi @marcofavorito, 

you should consider writing an opener script.
Instead of using `xdg-open` or a `pdf` viewer as the opener of the documents,
use a script that checks if it's a url or not, and opens a browser of your choice accordingly.
In the case of pdf files, it will open a pdf file.

I hope this helps, in papis I don't think it's useful to hardcode this.
Cheers

**Comment by alejandrogallo** [comment]
I think the last comment should setllte the issue, if not, feel free to reopen the issue.
