### ISSUE TITLE
Include library parameter in the run() function of commands.add.py 

### ISSUE THREAD

**Issue by cristobaltapia** [papis/papis#248]
It would be useful to add a parameter to choose the library in the `run()` function. For what I understand it is now only possible to change the name of the folder to place the document and `info.yaml` file, but this is always placed inside the default library.

**Comment by alejandrogallo** [comment]
Hello @cristobaltapia 
Thanks for you feedback. We removed this functionality from the `run` functions on purpose.
You can use the `api` to change libraries. Specifically, you can use

[papis.api.set_lib_from_name](
https://github.com/papis/papis/blob/515abc822c818d67f0dfb2ae7057971d7b7c4432/papis/api.py#L30i
)

for this.

Let me know if this is useful and developer friendly if you can.

Cheers

**Comment by cristobaltapia** [comment]
Hi @alejandrogallo 
thanks for your quick reply and for the tip regarding the function `set_lib_from_name()`. I think it is developer-friendly enough ;)

Cheers
