### ISSUE TITLE
The "papers" library has to be defined in configuration

### ISSUE THREAD

**Issue by koalp** [papis/papis#249]
When there is no `papers` library defined in the configuration, papis won't work and will raise the following exception.
```
File "/usr/lib/python3.8/site-packages/papis/config.py", line 477, in get_lib_from_name
    raise Exception(
Exception: Path or library 'papers' does not seem to exist
```
Another library is set as default and it works when the `papers` is defined in the configuration.

**Comment by alejandrogallo** [comment]
You're right, this seems to be a little bug, I confirm this behaviour.

**Comment by hyperkahler** [comment]
I also bumped into the same bug mentioned as above and tried to find a temporary workaround by
making papis refer to the local config file `.papis.config` as suggested at the documentation, though got the following error:
`NameError: name 'yaml_path' is not defined`

I use python 3.8, papis 0.9

**Comment by alejandrogallo** [comment]
FIY: I'll take a look at it as soon as the `typing` branch has been merged into master.
