### ISSUE TITLE
Export adding test.conf file

### ISSUE THREAD

**Issue by JBlocklove** [papis/papis#255]
When I run `papis export -f bibtex -o <name>.bib`, I get an extra file that appears to be a cleaned up (no comments or extra whitespace) version of my configuration file called `test.conf`.

This seems to happen with every iteration of the `export` command that I've used.

**Comment by alejandrogallo** [comment]
Hello @JBlocklove, thanks for reporting.
I also noticed this a while ago. Sadly debuging the configuration I forgot removing a creation statement
of a file `test.conf`. This is fixed now and won't be the case anymore in v0.10, thanks though!
