### ISSUE TITLE
Strange behavior on Arch, even on master, and possible issue or suggestion.

### ISSUE THREAD

**Issue by johnabs** [papis/papis#263]
papis, version 0.9 on AUR and papis-master
# how to reproduce the issue
Used AUR pkg standard, and with changing the source to "https://github.com/alejandrogallo/papis/archive/master.zip" along with the correct SHA256SUM and patches.  

Running "papis open" sans search query returns the following: "WARNING:cli:run:No documents retrieved". This also occurs with "papis edit", and "papis export -a". So basically, the default does not assume all documents are intended, and the tui is not utilized without values. This only occurs if "whoosh" is being used as the back-end, and if there's a way to address this that would be awesome, as whoosh is super fast apparently. But for now, I'm using what I can. The output is as follows:

```
> papis -v open
451-DEBUG:db:whoosh:Initialized index found for library
451-DEBUG:db:whoosh:Query string .
461-DEBUG:db:whoosh:<Top 0 Results for <_NullQuery> runtime=2.7141999453306198e-05>
462-WARNING:cli:run:No documents retrieved
```

Suggestion: remap default "papis open" to "papis open title:*" when whoosh backend is being used (which should display appropriate behavior in a vast majority of cases).

Also, this master version and the original PKG both exhibit the bug  #240 , where it hangs on using the tui through "papis open programming", to use the same example on the README. I understand this is apparently a bug in cpython 3.8, but it looked as though this was resolved. I'm running python version 3.8.1, if that matters. Also, to be upfront, there are 2 necessary patches to get this to work on Arch as it seems there was an issue with the versions of some dependencies, which may be causing the issue; however, I'm not sure if that's the case or not.  If there's anything else I can do/provide to help this move forward, I'd be more than happy to do so. Thank you very much for your time and consideration.

**Comment by alexfikl** [comment]
I think the first issue might be by design given [this](https://github.com/papis/papis/blob/master/papis/database/whoosh.py#L132). You would need to call
```
papis open '*'
```
to get a picker with all the documents. 

Not sure about the second issue from #240. It's been working fine for me since that got fixed (also on Arch with latest python). Is it just `open` that hangs? When I was experiencing that bug, it was hanging in `edit` and others too.

**Comment by johnabs** [comment]
Thank you for your quick response, and for the clarification on my first issue! That example provided worked great, I just found that discrepancy strange between the two back-ends. 

It is not just open that hangs, it's on edit and others as well. I may try out deleting and re-installing some packages to see how that goes. Do you have any packages installed via pip that may be allowing yours to work? Or perhaps I'm in that scenario where I have an out-of-date package not being updated due to pip. Would it be helpful if I link a paste containing the output of 

```
pip freeze
```
which should include all python packages including those installed via pacman? Or should I look for the pacman specific packages? I'm also thinking of just deleting all the packages manually and reinstalling them with something like this

```
sudo pacman -S $(pacman -Qq | grep python)
```
Thoughts? 

Thank you so much for your help, I greatly appreciate it!

**Comment by alejandrogallo** [comment]
You can try setting the configuration variable

[
`config-settings-default-query-string`
](
https://papis.readthedocs.io/en/latest/configuration.html#config-settings-default-query-string
)

for the library that you're using.
I heard this from other users also, but since now the default papis library
is quite fast, I don't think there is a need for it.

Feel free to post you thoughts.
Ale

**Comment by johnabs** [comment]
Ale,

I'm not primarily concerned with speed unless it gets to the point that the service becomes insanely slow without it, and in that case, I'll definitely switch to back to whoosh and try using that parameter you suggested. (That's also one less package I have to worry about manually keeping up-to-date) However, I am still struggling with the #240 bug. Would you happen to have any debugging advice? I'll leave a paste of pip freeze, with version numbers, [here](https://pastebin.com/sP1KkU7f) - if it will help.

Thank you so much for your time and input!

--- John

**Comment by alejandrogallo** [comment]
Hi John,

**Comment by johnabs** [comment]
Hi Ale,

It's the second link in the above post, the "here" link. But here it is again. [https://pastebin.com/sP1KkU7f ](https://pastebin.com/sP1KkU7f)  Thank you for being willing to take a look! 

--- John

**Comment by johnabs** [comment]
Extra info: 

I did a full system reinstall of the base python packages, to see if that would address my issue and no dice. I'm guessing (though I could be wrong) that someone has a slightly newer version of a dependency than I do - likely due to pip- but I could be wrong.

**Comment by alexfikl** [comment]
Just for comparison:
* [this](https://pastebin.com/m0Xu4Dtf) is my output from `pip freeze`.
* I have no globally installed python packages through pip, everything is managed by `pacman`
* I just updated papis to this commit b2de252 (latest at this time)

and I can't get anything to hang. What's the list of python errors you're getting when killing it?

**Comment by johnabs** [comment]
Sooo...I'm not sure what happened, or why it happened, but it's working now? I did use the newest commit, and I also cleared my paccache (perhaps this was part of it). I'm going to repeat these steps that worked using the newest commit, as well as the original AUR pkg. 

If mine works then I'll submit a new pkgbuild as a suggestion, or perhaps set it up as a papis-git pkg? But for now, at the very least, it seems functional. I'll report back shortly when I know more. Thank you so much for your help!

**Comment by alexfikl** [comment]
Ooh! Yeah, that's expected. The fix for #240 was added in #241 which is not included in the `v0.9` release, just in master, so the package from AUR would still hang.

**Comment by JP-Ellis** [comment]
It would be good if a new version (say `0.9.1`) could be released soon(ish).  Any timeline on this?

**Comment by alejandrogallo** [comment]
I'll release v0.10 this weekend, then it'll be hopefully alright
