### ISSUE TITLE
Support --folder with --all flag

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#266]
Exporting a document with `--folder` is nice for sharing, especially for putting some documents into repos shared with collaborators. It seems it should be able to support using the `--all` flag so one need not manually select individual files.

For example: I'm working on `projectA` with a collaborator via a shared repo. I want to dump a portion of my main papis library into the repo via the following
```
$ papis export --all --folder "project:projectA"
```

Alternatively, I could create a papis library inside the repo and use `papis add --from lib`, but once again, this is limited to manually selecting one document at a time.

**Comment by alejandrogallo** [comment]
Hi @avonmoll,
this is actually working, the syntax would be

```
papis export --all --folder -o output-lib "project:projectA"
```

Cheers
