### ISSUE TITLE
error macos

### ISSUE THREAD

**Issue by nlpirate** [papis/papis#268]
* papis version (0.9):
OS: macos Catalina

hi, I've just installed papis, but as soon as I try to add the first test document this error appears. It also occurs if I try to add the file from a url. How can I fix it? the configuration is the default one
thanks

```
 ~/Desktop  papis add libc.pdf --set author "Sandra Loosemore" --set title "GNU C reference manual" --set year 2018 --set tags programming --confirm         ✔  1911  16:57:52
ERROR:yaml:Yaml syntax error:

'utf-8' codec can't decode byte 0xd0 in position 10: invalid continuation byte
INFO:utils:matcher:libc.pdf matches fallback
ERROR:utils:matcher:Invalid URL 'libc.pdf': No schema supplied. Perhaps you meant http://libc.pdf?
INFO:add:run:Got an automatic folder name
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papis/commands/add.py", line 554, in cli
    link=link)
  File "/usr/local/lib/python3.7/site-packages/papis/commands/add.py", line 310, in run
    papis.config.get_lib_dirs()[0],
IndexError: list index out of range
```

**Comment by Galicarnax** [comment]
The same problem here. Freshly installed papis on Ubuntu 19.10, trying to import first pdf yields absolutely the same error (Yaml syntax error, No schema supplied, etc.).

**Comment by alexfikl** [comment]
By default papis uses a library called `papers` and tries to put it in `~/Documents/papers`, but it doesn't create the folder if it doesn't exist already, so you would need to create it yourself.

Does that fix it?

**Comment by Galicarnax** [comment]
Works for me, thanks. IMO, this is something that should be explicitly stated in docs and in quick start.

**Comment by jessebett** [comment]
I agree with @Galicarnax . I just ran into this utf-8 error. It should have an error message that says "directory does not exist".

**Comment by alexfikl** [comment]
Those are actually different errors:

* The YAML error is from [here](https://github.com/papis/papis/blob/master/papis/yaml.py#L58). It just complains because it tried to read a pdf file as a yaml file.
* The `Invalid URL` error is from [here](https://github.com/papis/papis/blob/master/papis/downloaders/__init__.py#L146). It just tries to use your local file as a URL and gets and error from the `requests` library.

Both of those should probably just be warnings or something less scary.

**Comment by jessebett** [comment]
Thanks @alexfikl

**Comment by alejandrogallo** [comment]
Through improvement of the error messages related to issue #227 this is now fixed, before adding a document papis will complain that the library does not have existing folders tied to the library
