### ISSUE TITLE
Imported files from `papis zotero` cannot be found in `papis open`

### ISSUE THREAD

**Issue by lyh970817** [papis/papis#270]
* papis version (`$ papis --version` or commit number):
0.9

Import files with `papis zotero --from-bibtex ~/Library/Papers` or `papis zotero--from-sql lib.bib -o ~/Library/Papers` then `papis open`

Command and output of `papis --log INFO <command>`:
```
papis --log INFO open 
xdg-open: file '/home/lyh970817/Yandex.Disk/Library/Papers/ba2ef4bd27feaeb745fff932499c55c8/1d6f4mq8yywzy8eermrgl6ovwmufokgker.pdf' does not exist 
```

```

**Comment by alejandrogallo** [comment]
Hi,
1. Does the file 
  ```
 '/home/lyh970817/Yandex.Disk/Library/Papers/ba2ef4bd27feaeb745fff932499c55c8/1d6f4mq8yywzy8eermrgl6ovwmufokgker.pdf'
  ```
  exist?

2. Otherwise could you provide me with the output of running
  ```
  papis -v open
  ```
