### ISSUE TITLE
format string without Jinja

### ISSUE THREAD

**Issue by wavefrontshaping** [papis/papis#274]
* papis 0.10

Hi guys, thanks for maintaining this very useful tool.

I used Jinja templating to format the name of my files, and it worked great. Now Jinja is gone and I cannot make things working the way I want.

It seems that any command are not passed to Python correctly through the `.format()` function.
I want my files to be named First author family name + year + first word of the title.

This is what I had with Jinja:

```
add-folder-name =  {{(doc["author_list"][0].get('surname','') or doc["author_list"][0].get('family','') ) if doc["author_list"] else doc["author"].split()[1]}}{{doc["year"]}}{{doc["title"].split()[0]}}
```

Now, I struggle even to get the first word of the title

```
add-folder-name = {doc["title"].split()[0]}
```
Gives `'str' object has no attribute 'split'.`

What can I do?

I have read that Jinja could be brought back with a plugin but I did not find it...

Thanks for your help!

**Comment by alejandrogallo** [comment]
I think now it's a good time to work on the plugin API for formatters, so that we can do Jinja support for `v0.11`

**Comment by wavefrontshaping** [comment]
Thanks for your reply. Where can I find information about the plugin system for papis?

**Comment by alejandrogallo** [comment]
I just documented a little bit the main idea of the plugin architecture
in here https://github.com/papis/papis/blob/master/papis/plugin.py.
It will be soon available in the docs 
[here](https://papis.readthedocs.io/en/latest/plugins.html)
as long as the build is complete.

In principle the main road would be the following in my opinion:

- define a format class with an API that all formatters should adhere to
  in `papis/format.py`.
  Whoever takes this can be inspired by the
  `papis/pick.py` file.
- Define the usual python formater in `papis/format.py` like maybe
  ```python
  # if it is subclassed or not will depend on the API
  class PythonFormater:
    def format(fmt: str, doc: papis.document.Document) -> str:
      ...
  ```
- Put this object in the `setup.py` entrypoints like
  ```python
  ...
  "papis.formater": [
    "python=papis.format.PythonFormater"
  ]
  ...
  ```
- We can try to define a Jinja formatter with this API.

In principle I can also work on this, but if someone wants to take it for a
stroll I can also oversee the process..

**Comment by wavefrontshaping** [comment]
OK,
I did something like that on my fork
https://github.com/wavefrontshaping/papis
(sorry, I am not good enough with git to do better)
It seems to be working, now I have to add the Jinja formater

**Comment by wavefrontshaping** [comment]
and needs to put
`formater = python`
in the config file.

How do I put default config values?

**Comment by wavefrontshaping** [comment]
I now have Jinja back!
I put both formaters in the same papis.format.py file, not sure it is the best bet.

**Comment by alejandrogallo** [comment]
Merged!
