### ISSUE TITLE
Option for skipping unicode to latex conversion?

### ISSUE THREAD

**Issue by jloow** [papis/papis#279]
I often use papis to generate bibtex files (to use with pandoc and pandoc-citeproc). I have several references where words are in all caps (e.g. "OHS"), but I find no way of retaining this capitalization when exporting to bibtex. In the bibtex format one can retain capitalization etc. by enclosing the word in curly brackets (e.g. "{OHS}"). But when papis exports to bibtex it will convert the brackets to latex (e.g. `{` becomes `\lbrace{}`). Currently, my solution is to comment out line 325 and 327 in `bibtex.py`, but perhaps it would be an idea to add an option to this effect?

**Comment by j-c-w** [comment]
You want to set `bibtex-unicode = true` in your config.  It skips the conversion of other types of characters too though.

I had some discussion about this issue here, and had arrived at the same approach until I decided that it would be best to manually format all my documents as bibtex style within the yaml files: https://github.com/papis/papis/pull/276

**Comment by jloow** [comment]
I had missed that PR and I understand the problems with different solutions.
Would there be any drawbacks in having, as @avonmoll  suggested, papis enclose all-caps words in brackets when exporting to bibtex? I'm thinking such a solution would be quite simple to implement.

**Comment by j-c-w** [comment]
From my perspective, the downsides of that approach are that it is partial, so I'd need to go through and markup a bunch of documents anyway (e.g. for names) --- this creates a weird situations where we've taken bibtex's odd bracketing rules, that are odd, but that everyone is aware of and turned them into odd bracketing rules that are specific to papis.

I definitely think that bibtex formatting within the yaml files is the way to go --- support for this could look like changing the document selector to know about this and some support for auto-bracketing in the importer.  Backwards-compatability issues surrounding this though.  Perhaps such features could be enabled with the bibtex-unicode flag.

**Comment by jloow** [comment]
Yeah, I see what you're saying.
I noticed, too, that when converting to yaml, capitalization will also be removed. Seems papis could use a general way of retaining capitalization and such (as you mention in the PR).
I'll close this issue though.
