### ISSUE TITLE
Making the metadata more structured

### ISSUE THREAD

**Issue by kskyten** [papis/papis#28]
While having no schema for the metadata is very convenient, I think it might be good to add some structure to the data. I think this would greatly improve interoperability. It also make it easier to query the data. Perhaps it is possible to add [YAML-LD](http://wiki.cfcl.com/Projects/Arborescence/YAML-LD) contexts to the metadata files? [Datalad](http://datalad.org/) uses json-ld for metadata and whoosh for searching it, maybe we could do something similar.

**Comment by alejandrogallo** [comment]
Hi, I guess this is one of this things that are obvious to someone once one has understood it
but I was taking a look at the `json-ld` specs and I kind of fail to see where it would be beneficial for

**Comment by nico202** [comment]
Maybe it's a bit OT, but while talking about the data structure I wonder if yaml is even suited for this at all.
YAML is human readable, but it's damn slow.

On julia:

@time for i in 1:10000 JSON.eval("{\"A\": \"hi\"})") end                                                                                                                                  
  0.000364 seconds

julia> @time for i in 1:10000 YAML.load("A: ciao)") end                                                                                                                                          
  1.375175 seconds (2.58 M allocations: 169.830 MiB, 2.11% gc time)                                                                                                                              

          
                                                                                                                                                                                       
In [30]: %time for i in range(1,10000): yaml.load("A: hi")                                                                                                                                     
CPU times: user 2.17 s, sys: 36 ms, total: 2.21 s
Wall time: 2.17 s
                                                                                                                                                                                                 
In [31]: %time for i in range(1,10000): json.loads("{\"A\": \"hi\"}")                                                                                                                          
CPU times: user 41 ms, sys: 14 ms, total: 55 ms
Wall time: 45.4 ms

We are not talking about peanuts, the difference is astonishing. I don't know if toml or something similar is faster. I'll do some well structured benchmark in the next days with real-world (papis info.yaml converted to various formats) example

**Comment by alejandrogallo** [comment]
Hi Nico, thank you for this appreciation.
It is certainly something worth investigating. 
My current understanding of yaml is that it is the exact equivalent of json when it concerns
simple data structures. Therefore wether an implementation is slower than the json equivalent
or faster, it is a matter of the implementation.

That being said, I think it is wortwhile exploring the idea of allowing other formats for the info file.

I have some points in pro of the `yaml` format, though:
- I don't know if it's fair to say that many people will have 10.000 documents in a library. If so, papis 
gives you the freedom to create other libraries within libraries.
- In the next papis version (hopefully), the `whoosh` database backend will be availabe.
This backend does not rely on loading an `info.yaml` file to get the information, but deals with
the indexing in another fashion. It is fair to say that if for instance someone implemented an sql
database backend, the only slow part would be indexing for the first time, where the info files will be read, so it would be a one-time thing.
- I personally value the fact that it is human readable, people can make sense of the actual data
being stored. Json would also be 'ok', but is way harder to read.

**Comment by nico202** [comment]
To my understanding, yaml is slower by design, see https://stackoverflow.com/questions/1726802/what-is-the-difference-between-yaml-and-json-when-to-prefer-one-over-the-other#1729545

However I don't know his the DB thing is being implemented. Because I fear that parsing 100 long (paper details) yaml is a pain (I'm having performance issues with 400 papers) but with the DB thing this 1.5 second wait will happens only during the indexing.. so yes ill wait to see and test it

**Comment by alejandrogallo** [comment]
This is now solved by having the option of using external databases in order to search,
so the json problem is only affected in the case where no database is used.
