### ISSUE TITLE
be able to pass URL to papis addto -f

### ISSUE THREAD

**Issue by eparejatobes** [papis/papis#280]
* papis version (`$ papis --version` or commit number): 0.10

As the title says; right now whenever the pdf cannot be downloaded directly by the importer (sciencedirect for example) I need to

1. download the pdf somewhere
2. pass that path to `papis addto -f`
3. rm the original pdf

PS great tool, it's saving me a lot of time

**Comment by alejandrogallo** [comment]
Hello Eduardo,

do you mean that papis should try to get again
the pdf from the url that you're giving it?

The thing is that if papis was not able to get the pdf
at the moment of adding it might be futile to try again.
Nevertheless it would be interesting to think about such
a feature, maybe not with `-f` but with `--url` or something
like this.

For the time being maybe you can try

```
papis update --auto
```

it will try to get pdfs from dois and urls.
Sometimes I do this and it works quite fine.

Cheers

Eduardo Pareja Tobes <notifications@github.com> writes:

> * papis version (`$ papis --version` or commit number): 0.10
>
> As the title says; right now whenever the pdf cannot be downloaded directly by the importer (sciencedirect for example) I need to
>
> 1. download the pdf somewhere
> 2. pass that path to `papis addto -f`
> 3. rm the original pdf
>
> PS great tool, it's saving me a lot of time


-- 
Alejandro Gallo

**Comment by eparejatobes** [comment]
> do you mean that papis should try to get again
the pdf from the url that you're giving it?

no, I think it's easier if I just give an example. If I add this: https://www.sciencedirect.com/science/article/pii/002240499390035R doing `papis add https://www.sciencedirect.com/science/article/pii/002240499390035R` everything works OK but for downloading the article (I guess is due to Elsevier being Elsevier, doing his best to avoid scrapping). Now (and this is fairly common for maths articles) I can get this from https://core.ac.uk/download/pdf/81979461.pdf. So I'd like to pass that to `papis addto`, or even better, to `papis add --pdf-url` or something like it.

> Nevertheless it would be interesting to think about such
a feature, maybe not with `-f` but with `--url` or something
like this.

That would be nice.

> For the time being maybe you can try (...)

didn't knew about that, will try, thanks.

**Comment by alejandrogallo** [comment]
you can also try the following

```sh
papis add https://www.sciencedirect.com/science/article/pii/002240499390035R https://core.ac.uk/download/pdf/81979461.pdf
```

it will correctly download the pdf from the second url too.
