### ISSUE TITLE
License file format is not understood by GitHub

### ISSUE THREAD

**Issue by TechnologyClassroom** [papis/papis#286]
Hi!  Cool project!

I see in the license file that the program is licensed as GPL-3.0-or-later which is great!  GitHub expects that file to contain the GPLv3 text.  Once there, the project would be clearly labeled as GPL at a quick glance when viewing the project page.  The content within the license file would fit nicely on the readme file.

I could make this as a PR you if you'd like.

**Comment by alejandrogallo** [comment]
Thanks for pointing it out! Sure if it's not a problem for you I'd be happy to merge the changes. Cheers !
