### ISSUE TITLE
notes flag

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#296]
Hi folks,  the screen capture here on github shows a -n or notes option which would be fantastic.  I installed (what I assumed was the) latest version via sudo pip3 install this morning but the -n flag is not recognized.

Suggestions?

R Haynes

**Comment by alejandrogallo** [comment]
Hi @rhaynes74, the `-n` flag is only available in the `edit` command, so you should do

```
papis edit -n
```
and not 
```
papis -n
```
Was this your problem ?

**Comment by rhaynes74** [comment]
Yes - sorry for the silly typo.
