### ISSUE TITLE
list of filetypes that can be added to a library

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#298]
Hi folks, is it possible to add all filetypes to a papis library? 

Best,
R Haynes

* papis version (`$ papis --version` or commit number):

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```

```

**Comment by alejandrogallo** [comment]
Hi, what do you mean exactly by `filetypes`, could you state an example where you would use it?
Cheers!

**Comment by rhaynes74** [comment]
Many thanks for the reply.  I guess I am thinking about a “project” in more general terms - papers, notes, code, images etc.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by alejandrogallo** [comment]
In principle you can have any kind of files.
For instance I have a library with datasheets

  https://github.com/alejandrogallo/datasheets

where the associated files for every document is indeed a pdf.

However you can also have images linked to a
document. The only think you have to change for this
is the `opentool` setting. For instance
if you have a library for images called `images`
then you would put in your `~/.config/papis/config`
file

```dosini
[images]
opentool = your-favourite-image-viewer
``

And so on. In general
you can set the `opentool = xdg-open` in `GNU/linux`
or `open` in `macOS`
to open automatically files according to their filetype.
This is indeed the default in papis.
