### ISSUE TITLE
Trouble using the --from arxiv with a url

### ISSUE THREAD

**Issue by benoit-combes** [papis/papis#305]
Dear developpers,

First thanks for developing this very useful tool ! 

I am on "papis, version 0.10" and have a few trouble on how to automate the adding of new references to my library:

Basically, I have no pb when using the "simple" way: 
```
$ papis add https://arxiv.org/abs/2005.10314
```
and then selecting  `arxiv` as 'importer' when asked by the tool.

By contrast, when I try to be a bit more specific (to avoid the need to specify by hand the sources) using:
```
$ papis add --from arxiv https://arxiv.org/abs/2005.10314
```

I get 
```
INFO:downloader:arxiv:downloading file from https://arxiv.org/pdf/https.pdf
ERROR:downloader:arxiv:The downloaded data does not seem to be ofthe correct type (pdf)
ERROR:cli:add:there is nothing to be added
```

I am a bit confused as, in theory, the two approaches seem to me equivalent.
Thanks in advance for your help

**Comment by alejandrogallo** [comment]
Hello Benoît,

thank you for your message.
This seems to be a bug in the arxiv downloader, **I'll take a look**.
I've confirmed it with `v0.11.1` so...

As a workaround for now you can do
```
papis add --from arxiv 2005.10314
```

This works for me and I think it should work for you,
this means, just take the `arxivId` of the paper.

benoit-combes <notifications@github.com> writes:

> Dear developpers,
>
> First thanks for developing this very useful tools ! 
>
> I am on "papis, version 0.10" and have a few trouble on how to automate the adding of new references to my library:
>
> Basically, I have no pb when using the "simple" way: 
> ```
> $ papis add https://arxiv.org/abs/2005.10314
> ```
> and then selecting  `arxiv` as 'importer' when asked by the tool.
>
> By contrast, when I try to be a bit more specific (to avoid the need to specify by hand the sources) using:
> ```
> $ papis add --from arxiv https://arxiv.org/abs/2005.10314
> ```
>
> I get 
> ```
> INFO:downloader:arxiv:downloading file from https://arxiv.org/pdf/https.pdf
> ERROR:downloader:arxiv:The downloaded data does not seem to be ofthe correct type (pdf)
> ERROR:cli:add:there is nothing to be added
> ```
>
> I am a bit confused as it seems not me equivalent in theory.
> Thanks in advance for your help


-- 
Alejandro Gallo

**Comment by benoit-combes** [comment]
Thanks for your answer. The solution you suggest me is sufficient for my usage.

Have a good day !
B.

**Comment by alejandrogallo** [comment]
I just fixed it, now you can use it also with the url (or beginning version v0.12)
