### ISSUE TITLE
Feature request - HTML export

### ISSUE THREAD

**Issue by ttxtea** [papis/papis#306]
I am wondering if it is difficult to generate a HTML list of articles for a library with links to the document in the papis `dir`. This way one could auto generate an overview in a gitlab repo that holds the library.

Some thing like `papis -l mylib export -f html`. It could also be `markdown` instead of html. There is something like it in the papis scripts repo, but its disfunctional with `papis, version 0.11.1`. With some hints I could try to help implement it.

**Comment by alejandrogallo** [comment]
Hi you could either try to fix the html script in papis script or something like
```
papis list --all --format '
<li>
  {doc[title]} <br>
  {doc[author]} <br>
  {doc[year]} <br>
</li>
'
```

Here you have some more documentation
https://papis.readthedocs.io/en/latest/commands.html#module-papis.commands.list

Is this helping you?

**Comment by ttxtea** [comment]
Thanks a million!! This is very flexibile for all sort of listing. I suppose that all information in the `info.yaml` is accessible via `doc[key]` for example the file name `doc[files][0]`. However, the auto-generated to the files probably not, right?

**Comment by alejandrogallo** [comment]
What do you mean by auto-generated?

**Comment by ttxtea** [comment]
The folder into which articles and bib info is placed. The first part of the path to a library can be found from `$HOME/.config/papis/config`. But then papis generates subfolders starting with a hash. I am wondering if that complete path is somewhere available through `doc[key]` or if one has to maybe search for the file to get the path.

**Comment by alejandrogallo** [comment]
This is right now only in `papis-export`, to be able to get the folder of the document.
We could also change this but in principle this is a good chance to write a simple script using
the functions in `papis.api`
https://papis.readthedocs.io/en/latest/api.html
.

If you do for instance


```
papis export --all --format json
```

you will get the field `_papis_local_folder` which is the folder
pointing to it. I'd recomment either writing a script
getting all the documents and generating the html you want using python
or reading from the json file with a script and also generating.
