### ISSUE TITLE
papis bibtex import succeeded - now what?

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#309]
Hi folks, I was having trouble with papis bibtex import with version 0.11.1, but followed the suggestion in issue #281 and was able to do the import.  Now my database is filled with hundreds of info.yaml files - each having a link to the pdfs that were contained in file= fields in my .bib file.     But now what? $papis list doesn't yields anything.  

papis list
WARNING:cli:list:No documents retrieved

**Comment by alejandrogallo** [comment]
- Which database are you using? In the case of whoosh you need to give a
  query to see something i.e. papis list einstein
- try also clearing the cache
    papis list --clear-cache
    papis list
    papis open
    etc..
- Also if this does not work, maybe you can also paste here a debug
  information of your running of the command (verbose)
    papis -v list

let's hope this helps !

rhaynes74 <notifications@github.com> writes:

> Hi folks, I was having trouble with papis bibtex import with version 0.11.1, but followed the suggestion in issue #281 and was able to do the import.  Now my database is filled with hundreds of info.yaml files - each having a link to the pdfs that were contained in file= fields in my .bib file.     But now what? $papis list doesn't yields anything.  
>
> papis list
> WARNING:cli:list:No documents retrieved


-- 
Alejandro Gallo

**Comment by rhaynes74** [comment]
Hi - using whoosh.  Indeed papis —clear-cache fixed things!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
