### ISSUE TITLE
possible to have vi keybindings when navigating papis list query (for ex?)

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#310]
Hi folks, is it possible to change the keybindings used to navigate the output of commands like papis list?

**Comment by alejandrogallo** [comment]
I would not recommend this since the picker is not modal.
You can do `C-n` and `C-p` to go up and down, this is how I do it, like in `dmenu` or `emacs`.
take a look here also
https://papis.readthedocs.io/en/latest/configuration.html#terminal-user-interface-picker
