### ISSUE TITLE
clean_document_name odd behaviour

### ISSUE THREAD

**Issue by jghauser** [papis/papis#311]
I think the `clean_document_name` function's behaviour can be a bit strict and at times also faulty. I noticed this when using the jinja2 formatter. Is there a reason that underlines aren't allowed? And capital letters?

More importantly, however, backslashes seem to lead to the whole string until the backslash to be suppressed. When I pass `Reda_2015_2014/2256(INI)-Draft-Report-on` to the function, it returns `2256-ini-draft-report-on`. This is unfortunate because now both the author and year are suppressed. 

I haven't tested it yet, but I suspect similar problems might exist for `ref_cleanup` in `bibtex.py`

EDIT: Maybe, I should explain what I'm trying to achieve. I was trying to adapt your script in in #295 to update my folder names, which is where the problem with the forward slashes appeared. It doesn't seem to happen when adding a new document. The other issues (re underlines, capital letters) happen also when adding a new document.

I also had another look at `ref_cleanup`. I'm unable to create ref tags with underscores and with only small letters (I was trying to recreate the tag style I used in zotero e.g. `dworkin_model_1967`).

**Comment by jghauser** [comment]
Closing this because I can't see the error anymore. Not sure if I was doing something wrong or something has changed in papis itself.

**Comment by alejandrogallo** [comment]
Hallo Julian,

thanks for your comments. I hope I can answer
all of the issues.

- Clean document name I think you're right to be
  buffled by its behaviour, this is the definition
  of the function basically

  ```python
  def clean_document_name(doc_path: str) -> str:
      import slugify
      regex_pattern = r'[^a-z0-9.]+'
      return str(slugify.slugify(
          os.path.basename(doc_path),
          word_boundary=True,
          regex_pattern=regex_pattern))
  ```

  and as you see the function take the basename of `doc_path` ,
  which is the argument to the function.
  So actually the naming
  of the function is not accurate, it should read
  `clean_document_path` I guess. That's why your string gets mutilated
  before the `/`.
  Furthermore, you also see that the only characters that are allowed
are
  alphanumerics and the dot, and they will be replaced by `-`.

- Allowing for `_` I guess we can do it for paths, yes.
  In general it's best to limit the characters that can appear in
  paths, but `_` is not a problematic one in afaik neither in WINDOWS
  nor in *nix systems.

- About having the `_` in references, as far as I know
  latex can't deal with underscores, that's why I decided
  to be strict about it, since most people will not ever want
  to have an underscore in their reference when working with *tex
  (and most papis users also use *tex). However if you have some new
  thoughts about this issue I'm all ears.

**Comment by jghauser** [comment]
I've by now made peace with the missing underscores :laughing:.What would be nice, however, is if the folder names wouldn't get mutilated for documents that contain `/`. Although this is a rather rare occurrence in my case and I've solved it by calling `slugify` directly in my script.

**Comment by choreutes** [comment]
Hi,

I have also stumbled upon this when I started using papis as I was thinking to use the DOI of papers as their paths which tend to contain underscores. Since I don't think simply changing the slugify method would be a good idea I'm instead considering adding a configuration option for this with the current behaviour as default. I have a few questions regarding this:
1. Do you think this would be a good idea at all?
2. If I were to write up pull request for this, is there a deadline for the next release yet?

**Comment by jghauser** [comment]
I think it's fine to change the function to allow underscores at least. As @alejandrogallo writes above, that character should not be problematic. The problem with the backspace is probably a bit harder to solve, though I haven't looked at the various places from where `clean_document_name()` is called. But that doesn't seem to be your focus anyway (and that's ok) :). Let's see what @alexfikl thinks.

I don't think there's a deadline yet for the next release, but we have been talking about making one soon. If it's important to you that this change still makes it, maybe you can give us an estimation of how long it'd take you and we'll probably be able to work something out :grinning:.

**Comment by alexfikl** [comment]
I'm on board with adding some configuration option to customize how files and other things get slugified. The easiest way around that should be just adding the regex in `clean_document_name` as a config variable, e.g.
```
regex_pattern = papis.config.getstring("add-clean-regex-pattern")
```
Would that work for what you had in mind? It should allow adding uppercase letters and underscores in there if desired.

> What would be nice, however, is if the folder names didn't get mutilated for documents that contain `/`

Is this still an issue? For `papis add` at least, this chunk of code should go over the folder name string and split things:
https://github.com/papis/papis/blob/eef210ac3d1054bc9b23561161b3505ea458e118/papis/commands/add.py#L347-L350

For example, you can do things like
```
papis add --folder-name "{doc[year]}/{doc[author]}/{doc[doi]}-{doc[title]}" <URI>
```
and it should work. I'm not sure if it creates all the intermediate folders, but we can fix that :grin:

**Comment by jghauser** [comment]
You're totally right! And it seems to also create all the intermediate folders without problems (at least it's what I see doing a quick test). So that's even better, once we add a configurable option for the regex, this issue can be closed :grinning:. I do think having the underscore allowed by default would be good, but I don't have strong feelings either way.

**Comment by choreutes** [comment]
Yes, that was exactly what I had in mind! Thanks a lot for the quick reply! I also don't have strong feelings as to what the default of that option should be.

For the slashes in folder names I can say that I've been using them almost the entire time and it worked for me without issue. So this doesn't seem to be a problem (anymore?).

**Comment by alexfikl** [comment]
> Yes, that was exactly what I had in mind! Thanks a lot for the quick reply! I also don't have strong feelings as to what the default of that option should be.

I would say to keep the current value as a default, so that people don't suddenly get a bunch of new and exciting characters in the file names?

**Comment by jghauser** [comment]
hey @choreutes, are you still interested in getting this to work? we're discussing releasing a new version soon (see #799) and I wanted to give you a heads up as you expressed interest in getting this feature done before the new release.

**Comment by choreutes** [comment]
Thanks for the heads-up! I'd still be interested to get this in, but I'm not in the country at the moment and have to see how much time I could dedicate to this. Also I have to figure out how to test things on my system. So depending on how soon “soon” is I might not be able to make it.

**Comment by alexfikl** [comment]
> EDIT: Okay, maybe I made this more difficult in my head than it actually is. You documented the process **really** well in the HACKING.md file. I'm trying to get it done now but may still need some getting used to.

Feel free to make a draft PR and ask any specific questions you have! It will be easier to see what tests are failing on the CI too.

**Comment by choreutes** [comment]
A draft PR is now open under #803.

**Comment by fab6** [comment]
Hi,
I am curious, how I can set the folder and file format so that I can keep the underlines and even keep capital letter at the beginning of words :-) I understood from the above that this can be included now, but unfortunately I havent figured it out yet...

**Comment by alexfikl** [comment]
> Hi, I am curious, how I can set the folder and file format so that I can keep the underlines and even keep capital letter at the beginning of words :-) I understood from the above that this can be included now, but unfortunately I havent figured it out yet...

@fab6 You should be able to set
1. `doc-paths-word-separator = _` in your configuration file to allow underscores to be used as word separators.
2. `doc-paths-lowercase = false` in your configuration file to keep capital letters. Note that this will only keep capital letters if they're already there in the original string (e.g. title), but it will not capitalize them for you.

I haven't tried it myself, but that should work. What problem did you encounter?

**Comment by fab6** [comment]
Thank you for the quick help... this works for me now, thought the file name is not according to the command

with 
```
papis add -d testFolder_test3 1-s2.0-S0022407322000188-main.pdf --file-name "Andre et al  2022  The absorption line distribution function for ra.pdf" --folder-name "Andre et al  2022  The absorption line distribution function for ra" 
```

I get the folder to be
```
Andre_et_al_2022_The_absorption_line_distribution_function_for_ra
```
which is as given in the command, but for the file name the config default is used:
```
Andre_2022_The_o_absorption_line_distribution_function_for_rank_correlated_SLW_model_prediction_of_radiative_transfer_in_non_uniform_gases.pdf
```

Maybe see directly what I am missing.
Thank you!
