### ISSUE TITLE
[Enhancement] Allow opening/creating a note from picker with ctrl+foo

### ISSUE THREAD

**Issue by jghauser** [papis/papis#316]
It would be great if it were possible to open/create an attached note from the default picker with `c+foo`. This would be analogous to opening an attached file (`c-o`) or editing the yaml (`c+e`).

My use case for this is that I like to have the picker open with all documents that relate to a certain project. From there I then open the files as I need them without having to start the picker again every time I open a document. It would be great if this worked also for notes.

I'm not sure what the best shortcut would be, seeing that c-n is already taken.

If that's something you'd like to see, I'd be happy to give a shot at implementing the feature. I'm not much of a programmer, but with a pointer or two in the right direction, I think I should able to do it.

**Comment by alejandrogallo** [comment]
This is doable, you can basically
play with the file
`papis/tui/app.py`

There you find the function
`get_commands` which basically gets the commands
and assigns them to keybindings for the picker.

This part of papis is yet to be documented, but you
can add there a new command following the example of
the edit command there, i.e.:

```python
    @kb.add(keys_info["edit_document_key"]["key"],  # type: ignore
            filter=has_focus(app.options_list.search_buffer))
    def edit(cmd: Command) -> None:
        from papis.commands.edit import run
        docs = cmd.app.get_selection()
        for doc in docs:
            run(doc)
        cmd.app.renderer.clear()
```

I hope this helps you to get started experimenting.

**Comment by jghauser** [comment]
Thanks for the help! I'll see how I can make this work and report back once I got something.

**Comment by jghauser** [comment]
This has been implemented (see merged pull request above)!
