### ISSUE TITLE
merging 

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#317]
Hi folks, I hope things are well.  Will papis accurately "merge" a new .bib file into the database? I have imported my main "master" .bib file into papis.  But I do have a few other .bib files around which may contain papers not in the master.   If I use the bibtex import feature will in detect the duplicates and not import or will it attempt to the merge the information?

**Comment by alejandrogallo** [comment]
Papis will try to find duplicates, this is specially possible whenever
there is a DOI in the bibfile too for the paper.

In general it can be that some papers get added twice, specially if
no DOIs are present, then sometimes the titles have typos, mathematical
expressions etc which accept some variations depending on which format
they're written in.
