### ISSUE TITLE
Announcement: Zulip chat

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#318]
I opened a zulip organization, maybe it's a good idea to also discuss
there some issues that don't really belong to the issues.

https://papis.zulipchat.com

UPDATE: Zulip was nice enough to give us a full membership, so I really
        encourage this service, hopefully people join us there!

**Comment by alejandrogallo** [comment]
If you want to be invited please go to this url

https://papis.zulipchat.com/join/bgtv3pmg4iqo2r7dpikuq6sx/

**Comment by ttxtea** [comment]
The invitation link returns:

~~~
Whoops. The confirmation link has expired or been deactivated.
~~~
for me

**Comment by alejandrogallo** [comment]
Sorry about that

  https://papis.zulipchat.com/join/yjf3v3by3yw3esdclum6sh5h/

I'd like the link not to expire but I don't really know how.. :}
