### ISSUE TITLE
Remove 'type' from 'bibtex_keys'?

### ISSUE THREAD

**Issue by jghauser** [papis/papis#322]
Is there a reason that `type` is among the `bibtex_keys` in `bibtex.py`? At least for me, it leads to problems when using exported .bib files with pandoc. It seems pandoc citeproc picks up that value and uses it in bibliographies which leads to random `incollection`, `misc` etc. in my bibliographies.

**Comment by alejandrogallo** [comment]
Actually it's true, this should not be the case, right? **IF** `type`
is not an official bibtex key then we should remove it, indeed.

**Comment by jghauser** [comment]
Great, thanks for the super quick response!
