### ISSUE TITLE
Suggested Mutt macro in documentation is broken

### ISSUE THREAD

**Issue by antimike** [papis/papis#326]
* papis version (`$ papis --version` or commit number): 0.11.1

# how to reproduce the issue
This is technically not a bug, so not sure if this is the appropriate place to raise this.  (OTOH, should be a quick fix.)
The issue is that the documentation suggests a Mutt macro that is now broken as a result of the deprecation of the `export --file` flag:
```
macro compose \cp \
"<enter-command>unset wait_key<enter>\
<shell-escape>rm -f /tmp/paper.pdf<enter>\
<shell-escape>papis export --file -o /tmp/paper.pdf<enter>\
<attach-file>/tmp/paper.pdf<enter>\
```

**Comment by alejandrogallo** [comment]
True, there is no `--file` anymore, better would be addig a folder, with `--folder` and zip it and send it. This was removed since some documents might have many pdfs associated, and then in this case this would be problematic.

**Comment by alejandrogallo** [comment]
the documentation was updated, thanks for this!
