### ISSUE TITLE
papis is unable to download pdf from arxiv.org

### ISSUE THREAD

**Issue by rusty-electron** [papis/papis#335]
* papis version 0.11.1

# how to reproduce the issue
`papis add --from arxiv https://arxiv.org/pdf/2012.04643.pdf`
## desired output:
papis downloads the pdf from `arxiv.org` and adds it to my paper library
## actual output:
```
INFO:downloader:arxiv:downloading file from https://arxiv.org/pdf/https.pdf
ERROR:downloader:arxiv:The downloaded data does not seem to be ofthe correct type (pdf)
ERROR:cli:add:there is nothing to be added
```
Hi, I recently started using papis and found this command in the docs but I am not able to get it working.

**Comment by alejandrogallo** [comment]
Hi Pritom,

thanks for this, it is true, apparently there seems to be a problem
when the string ends with `.pdf` like

`papis add --from arxiv https://arxiv.org/pdf/2012.04643.pdf`

I'll take a look at the regular epxression for this, however the
following works


papis add --from arxiv https://arxiv.org/abs/2012.04643
papis add --from arxiv https://arxiv.org/pdf/2012.04643
papis add --from arxiv 2012.04643
papis add --from arxiv arxiv:2012.04643
papis add arxiv:2012.04643
papis add https://arxiv.org/pdf/2012.04643

I hope this works as a workaround for you for now.

Cheers!

Pritom Gogoi ***@***.***> writes:

> * papis version 0.11.1
>
> # how to reproduce the issue
> `papis add --from arxiv https://arxiv.org/pdf/2012.04643.pdf`
> ## desired output:
> papis downloads the pdf from `arxiv.org` and adds it to my paper library
> ## actual output:
> ```
> INFO:downloader:arxiv:downloading file from https://arxiv.org/pdf/https.pdf
> ERROR:downloader:arxiv:The downloaded data does not seem to be ofthe correct type (pdf)
> ERROR:cli:add:there is nothing to be added
> ```
> Hi, I recently started using papis and found this command in the docs but I am not able to get it working.


-- 
Alejandro Gallo

**Comment by rusty-electron** [comment]
Thanks, `papis add --from arxiv 2012.04643` worked. 

Thanks again for creating this tool. I always wanted a cli-based tool for managing my paper lib and citations. Once I figure stuff out, I will be switching to papis from zotero.
