### ISSUE TITLE
select renamed documents in subfolder and transfer to tablet - like zotfile

### ISSUE THREAD

**Issue by fab6** [papis/papis#336]
Hi,

I have a general question... Is there an option to select a few document (which are renamed e.g. like Author_year_title) and transfer them to a tablet; very similar like zotfile [http://zotfile.com/](http://zotfile.com/) is doing!?
Zotfile basically tags (e.g. with `_tablet`) the document and creates a copy in another folder (synced with cloud) with the corresponding subfolder.  Once it is read or annotated it retrieves the copy back to the main directory structure with the corresponding subfolders.

This would have the advantage that one does not have to sync all files on the tablet itself; but just the selection which is relevant for current reading.

Or maybe there is a similar way to read the documents offline on an ipad/tablet without syncing the whole library.

Thank you in advance!
Fab

**Comment by alejandrogallo** [comment]
Well there are many ways of doing this, I will list some
that I use. For instance when I'm on my tablet
I often use a small script to serve the document folder
on my local network with the `python3 -m http.server 8888`
command, I have it in a raku script named `,serve` like this (you can do also a bash
script)

```raku
#!/usr/bin/env raku
unit sub MAIN($dir=".", $port=9999);

indir $dir, {
  shell qq!
    python3 -m http.server $port
  !
}
```

and then I do
```
papis run -p einstein ,serve
```
to do a query as `einstein` and run the `,serve` command in the selected
documents folder.


Another way of achieving something similar easily is tagging all the documents
that you want as `zotfile`, so you do in your `info.yaml`
```yaml
zotfile: 1
```

or something like
```yaml
tags: informatics ... zotfile
```

and then you select them with the queries `zotfile:1` in the first case
or `tags:zotfile` in the second case.
Then you can copy all pdfs in these files to a folder like

```sh
zotfile_folder="~/wherever"
mkdir -p ${zotfile_folder}
for folder in `papis list --all tags:zotfile`; do
  cp "${folder}/*.pdf" "${zotfile_folder}/"
done
```


If you want more control renaming, I suggest you look at the python API
for scripts, something like
```python
import papis.api

docs = papis.api.get_documents_in_lib(search="tags:zotfile")
for doc in docs:
    folder_name = "{doc[author]}_{doc[title]}".format(doc=doc)
    files = doc.get_files()
    ...
```

**Comment by fab6** [comment]
Oh, thank you very much for your quick and interesting reply!
I will check how it works for me.
