### ISSUE TITLE
DBLP (computer science bibliography) Integration

### ISSUE THREAD

**Issue by mvcisback** [papis/papis#337]
Hi,

Would it be possible to support DBLP keys and links for adding papers? This seems like a straight forward integration.

**Comment by alejandrogallo** [comment]
hi @mvcisback
I'd be happy to take a look into it, could you provide with a quick example of how this would work?
I already implemented a dblp backend, so I guess it will be quickly implemented.
Cheers!

**Comment by mvcisback** [comment]
Hi @alejandrogallo 

What I was imagining was looking up the paper by its dblp key, e.g.,

`papis add --from=dblp conf/nips/Vazquez-Chanlatte18`

This would let you:

1. look up the bibtex, https://dblp.uni-trier.de/rec/conf/nips/Vazquez-Chanlatte18.html?view=bibtex
2. look up the corresponding doi to find a pdf

The first feature is my main request.

**Comment by alexfikl** [comment]
@mvcisback In case you're still using `papis`, some support for DBLP has been added in #489. You should be able to add papers based on their DBLP key or full url with
```
papis add --from dblp 'conf/nips/Vazquez-Chanlatte18'
papis add --from dblp 'https://dblp.org/rec/conf/nips/Vazquez-Chanlatte18.html'
```
which imports the bib file from DBLP.

**Comment by alejandrogallo** [comment]
In principle this is solved now, is that right?
