### ISSUE TITLE
Documentation on the bibtex use is incomplete

### ISSUE THREAD

**Issue by wwywong** [papis/papis#338]
The current documentation for the `papis bibtex` command is incomplete/incorrect. 

https://papis.readthedocs.io/en/latest/commands.html#module-papis.commands.bibtex

Under the subheading `cli`, what is displayed is the manual for `papis add` and not `papis bibtex`.

**Comment by alejandrogallo** [comment]
Well spotted! Thank you very much, I just fixed it.
