### ISSUE TITLE
Improve bash completion and add zsh completion

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#34]
I have added a script to create a bash completion script
in
```
scripts/shell_completion
```
just hit make and source the script at ``build/bash-completion.sh``.
Maybe someone uses zsh and wants to update it to create a ``build/zsh-completion.zsh`` script?

**Comment by alejandrogallo** [comment]
Asciinema example:
https://asciinema.org/a/Iz1MyhsUBipTHCyZGoGRGJEI4

**Comment by michaelplews** [comment]
I can't seem to get this to work. `make` says it's creating `dist/bash-completion.sh` but then the file isn't there in the current directory, or in the `papis/dist/` directory. Am I missing something?

**Comment by alejandrogallo** [comment]
Hi you're right I misspelled `build` writing `dist` ... ;)

So the completion script will appear
in `build/bash/papis`, I changed it and I forgot to update the comment,
sorry for that.

After building I have the following
directory structure:

```
.
├── build
│   └── bash
│       └── papis
├── Makefile
└── tools
    ├── bash.sh
    └── lib.sh

```

**Comment by alejandrogallo** [comment]
BTW zsh would be nice, I don't  use it but it would be very nice.
For that I think the functions you need are in `tools/lib.sh`, using these functions
you can write a script in `tools/zsh.sh` for instance that write the zsh script for completion,
since from `tools/lib.sh` you get functions to get the current papis commands and flags...

**Comment by teto** [comment]
Would be awesome to have zsh completion, I launch bash just for papis.

**Comment by alejandrogallo** [comment]
Hi ! I'm not a zsh user, do you have experience writing completions for zsh ?
Maybe if you give us an example we can adapt it.

**Comment by alejandrogallo** [comment]
Version 0.8 will have zsh autocompletion!

**Comment by teto** [comment]
that's awesome. I've tried to update the nix package to test the changes but seems like setup.py install won't install the dependencies which ends up in
```
Traceback (most recent call last):
  File "/nix/store/ik8qa581vh7bdrjld92cc8wma5f9f8m0-papis-0.7.5/bin/.papis-wrapped", line 8, in <module>
    from papis.main import main
  File "/nix/store/ik8qa581vh7bdrjld92cc8wma5f9f8m0-papis-0.7.5/lib/python3.6/site-packages/papis/main.py", line 6, in <module>
    import papis.commands.default
  File "/nix/store/ik8qa581vh7bdrjld92cc8wma5f9f8m0-papis-0.7.5/lib/python3.6/site-packages/papis/commands/default.py", line 34, in <module>
    import papis.deps.colorama as colorama
```
If I look at the folder here it's almost empty:
```
$ ls /nix/store/ik8qa581vh7bdrjld92cc8wma5f9f8m0-papis-0.7.5/lib/python3.6/site-packages/papis/deps/
__init__.py  __pycache__
```

Any reason not to have these dependencies in setup.py ?

**Comment by michaelplews** [comment]
This is great. I'm interested to see how this was done as I wasn't able to understand it from the zsh documentation when I had a go!

**Comment by alejandrogallo** [comment]
Hi @teto,
did you make the submodules ?

```
make submodules
```

Cheers!

**Comment by teto** [comment]
@alejandrogallo but then when packaging papis, it duplicates the packages and makes it hard to reason about (which version do I have etc.). Why not adding them in setup.py ?

**Comment by alejandrogallo** [comment]
Because they will conflict with other existing packages in your system.
If I update the `click` library to 7.0.0 and your `youtube-dl` uses 5.0.0, then `youtube-dl`
will cease to work. The end user does not care about this and you can always lookup
the commit message. For me I can sleep better at night knowing that I wrap the most important libraries and they will not get screwed by other packages you install. In my opinion.

And everything together are a couple of hundreds of `kB`.

**Comment by teto** [comment]
This is the role of distributions to work around that. Wit www.nixos.org I can have as many versions of any application/libraries in parallel as I want so it's actually more trouble. In more standard distrib, you would use virtualenv as well. There are standard ways to work around that and now I have to learn the way papis does it: it doesn't scale :'(

**Comment by alejandrogallo** [comment]
I understand your concern and I think it's valid, but from my point of view you don't have to learn the *papis way*. There are still dependencies in the setup.py, which will be taken care of by the respective package managers. Only some that are widely used and often updated will remain in the source,
in `papis/deps`.

It's kind of unfair that if a non-expert user installs a program `A` with a dependency of
`prompt_toolkit`, say `1.0.0`, that only because of this papis cannot work anymore, and the user's
research get stalled two weeks because of this, this is unacceptable.

It's nice that `nixos` can do all these things and of course you can get by with virtual environments just fine. However most users will even have trouble doing the `virtual environment` step, it's just unfortunate that I can't have two versions of the same library system-wide in python.

To package papis right now you just have to do the same as before, just `make submodules`
before packaging. Is this really that barroque?
```
make submodules && python setup.py sdist
```
Anyways I wanted to discuss this with the community before releasing `v0.8`, if this is such a bad idea I can remove it, I'm just thinking about realistic scenarios that I have encountered with many users, and
issue #99 is just an example.

**Comment by teto** [comment]
I agree with you that python packaging is a mess but so is debian's etc (when programs require different versions of a same library etc).

I myself try not to rely on git submodules because it usually feels tricky (not really in this case).
I don't know if you have experience maintaining packages for distributions but "standard" practice are a good thing.  

> To package papis right now you just have to do the same as before, just `make submodules`
before packaging. Is this really that barroque?

Well as a user now I have to look it up in the documentation. Or you could provide a link as to how to setup a virtualenv and if I already know about it then I can skip the rest.

As a developer, (I think I will stick with papis, I am writing a paper right now so I'll see if it's a good fit but it should be ok, I see a few things I might want to patch), I had a look and I see `import papis.deps.colorama` and I was like "is that the standard colorama I know" ? so I had to check the url against the standard package, hence a cognitive load and a barrier to new developers IMO. 

As you understand, I have strong feelings about this xD but let's hear about others :D

**Comment by alejandrogallo** [comment]
I've been thinking about this the whole week, I hate not being able to trust fully that python
does not break because of libraries. However I agree with you, really.
I think for now libraries that should be heavily used by
developers should be used normally, like for instance `colorama`. Other libraries, without the exact
version of which papis cannot work, if possible we can also ship them with papis, like for instance `prompt_toolkit`, I agree is not the best solution, we can try for the moment like this and see.

The problem with virtualenvironments is that also in principle papis should be used by people
as a library for scripting quick python scripts. Within a virtualenv is too much of a hustle to set the paths
or the python binary, I think.

It seems that the decision is between you and me :D

**Comment by alejandrogallo** [comment]
As a matter of fact, you're right, I'm erasing all submodules.

**Comment by teto** [comment]
what happened ? a problem with submodules xD ? 
I am really happy that's your decision. Thus I went on to try the zsh autocompletion but I notice you bumped the versions to like the latest version of slugify/colorama/pygments... 
```
    install_requires=[
        "requests>=2.11.1",
        "filetype>=1.0.1",
        "pyparsing>=2.2.0",
        "configparser>=3.0.0",
        "arxiv2bib>=1.0.7",
        "PyYAML>=3.12",
        "chardet>=3.0.2",
        "beautifulsoup4>=4.4.1",
        "colorama>=0.4.1",
        "bibtexparser>=0.6.2",
        "pylibgen>=1.3.0",
        "click>=7.0.0",
        "python-slugify>=2.0.1",
        "habanero>=0.6.0",
        "isbnlib>=3.9.1,<4.0.0",
        "prompt_toolkit>=2.0.0",
        "pygments>=2.3.1",
    ],

```
It's easy to update them in nix so that's what I am doing but I wonder if papis really needed the latest version of these packages ? since the last version didn't and isn't that old.

**Comment by teto** [comment]
I've updated the nix package and autocompletion kind of works but for commands, all commands get the same name. It might be caused by nix because it wraps the binary in some shell script, is the output different on your machine ?
```
teto@jedha> papis cli                                                                                                               ~
unsorted
cli                         -- Add a document into a given library                                                                  
cli                         -- Add files to an existing document                                                                    
cli                         -- Delete command for several objects                                                                   
cli                         -- Edit document information from a given...                                                            
cli                         -- Explore new documents using a variety of...                                                          
cli                         -- Export a document from a given library                                                               
cli                         -- List documents' properties                                                                           
cli                         -- Move a document into some other path                                                                 
cli                         -- Open document from a given library                                                                   
cli                         -- Open document's url in a browser                                                                     
cli                         -- Print configuration values                                                                           
cli                         -- Rename entry                                                                                         
cli                         -- Run a git command in the library folder                                                              
cli                         -- Run an arbitrary shell command in the library...                                                     
cli                         -- Update a document from a given library                                                               
external-cli                -- Convert zotero library to papis library using sqlite                                                 
external-cli  external-cli  -- No help message available               

```
I just pressed `papis <TAB>` and it autoselected "cli"

**Comment by alejandrogallo** [comment]
Hi!

- About the submodules, I just thought about what you said, and even though the work
perfectly and such, it is true that *standards are a good thing*. I agree, and as much as it annoys me
`pip`, for now there is nothing soo special that cannot be bundled with it. So I thank you for your suggestion, you brought light to the dark side.

- About the versions, you're right, I have to relax the versions, I set the versions so to match them with the test suite, but today I'd like to relax them as long as the tests pass and then release `v0.8`.

- About the autcompletion, I think I know why, in every algorithm I did not write the name of it not to repeat, in `@click.command`, I'm fixing this now, not your fault.

**Comment by alejandrogallo** [comment]
Commit 58e1f91 should solve the issue of the `cli` names, thank you very much for pointing it out.

**Comment by teto** [comment]
That's better, still a few redundant "cli" though

```
add                  -- Add a document into a given library                                                                                                                                                                                                                   
browse               -- Open document's url in a browser                                                                                                                                                                                                                      
cli                  -- Add files to an existing document                                                                                                                                                                                                                     
cli                  -- Explore new documents using a variety of...                                                                                                                                                                                                           
cli                  -- List documents' properties                                                                                                                                                                                                                            
config               -- Print configuration values                                                                                                                                                                                                                            
external    default  -- No help message available                                                                                                                                                                                                                             
edit                 -- Edit document information from a given...                                                                                                                                                                                                             
export               -- Export a document from a given library                                                                                                                                                                                                                
git                  -- Run a git command in the library folder                                                                                                                                                                                                               
mv                   -- Move a document into some other path                                                                                                                                                                                                                  
open                 -- Open document from a given library                                                                                                                                                                                                                    
rename               -- Rename entry                                                                                                                                                                                                                                          
rm                   -- Delete command for several objects                                                                                                                                                                                                                    
run                  -- Run an arbitrary shell command in the library...                                                                                                                                                                                                      
update               -- Update a document from a given library                                                                                                                                                                                                                
zotero-sql           -- Convert zotero library to papis library using sqlite  
```

**Comment by alejandrogallo** [comment]
Ups! I just fixed it, I forgot those! Thanks! It is in the branch pick2, soon in master and in new version.
