### ISSUE TITLE
Unique document keys don't working during import with bibtex command

### ISSUE THREAD

**Issue by reyman** [papis/papis#342]
* papis version = 89fe3a78ad237e9773e18d86af52641497842074

I'm trying to use `unique-document-keys = ['file','ref']` to filter duplicate between two bib file.

I run two time an import using `papis bibtex` from the same ext file and there is no detection of duplicate on this field, is it a normal behavior ? 

```
papis bibtex read myfile.bib import --all 
```

When i check the yaml duplicated, the `ref` and `file` key are exactly the same.

**Comment by reyman** [comment]
@alejandrogallo Some news on that ? perhaps i need to test with other backend ?

**Comment by alexfikl** [comment]
> @alejandrogallo Some news on that ? perhaps i need to test with other backend ?

You can definitely try with the `papis` backend to see if that works. If that works and it's an issue with the `whoosh` backend, my best guess would be that it doesn't know the fields, so you could try adding
```
whoosh-schema-fields = ['files', 'ref']
```
to your config file.

**Comment by reyman** [comment]
@alejandrogallo Yes you're right this is linked to schema fields ! thanks
