### ISSUE TITLE
`_papis_local_folder` not exported with bibtex format

### ISSUE THREAD

**Issue by reyman** [papis/papis#356]
* papis version (`$ papis --version` or commit number):

papis, version 0.11.1

# how to reproduce the issue

With `info.yaml` that contain files metadata like this : 

```
➜ cat ~/Notes/Papers/fe54d4250e4ca234001f4236a4a82d7b-xxx/info.yaml 
author: xxx, xxx
author_list:
- family: xxx
  given: xxx
booktitle: xxxx
chapter: '1'
files:
- xxx.pdf
pages: 17--29
title: '{Introduction}'
type: incollection
year: '2001'
```

Command and output of `papis --log INFO <command>`:
```
papis export --all --format bibtex --out test.bib
INFO:cli:export:Dumping to test.bib
nano test.bib
```
Doesn't produce the awaited `_papis_local_folder` with `bibtext` format. I try with json and it works.

**Comment by alejandrogallo** [comment]
Hi
thank you for your detailed issue. This is intentional, since we would not want in general for people
to export bibtex entries and put `papis dirt` into some other people's bibfiles or in the own bibfile.
If you want it you have to tell bibtex explicitly in the config file that you want this papis key to be exported,
specifically this should work

```
[your-library]
extra-bibtex-keys = ["_papis_local_folder"]
```

Sorry for this, but I think this is the correct default behaviour in general, I'll mark this issue as a `faq` for future reference.
I hope this helps!

**Comment by reyman** [comment]
Thanks for your very quick answer @alejandrogallo , i also started to look into script / api to do this manually (convert into .bib using to_bibtex) function but i found this is not possible because bibtex file key, also used in zotero/mendeley/jabref ( ex `file = {Albeck1991.pdf:Albeck1991.pdf:PDF}`) is not available into `https://github.com/papis/papis/blob/master/papis/commands/bibtex.py`

**Comment by alejandrogallo** [comment]
I'm also an emacs user, I started https://github.com/papis/papis.el some time ago but probably I should do some rethinking of the code again. Anyways my goal was to reuse much of org-ref as possible, maybe you want to give it a look.
In principle how I solved the problem you are aluding to is by checking the ref in papis and getting the file 
https://github.com/papis/papis.el#org-ref-compatibility

Do you mean that reftex does this by expecting a file field in the bibtex? If this is the case I think we could
have a workaround for this, I would be open to that since I'd be intrigued to know what is exactly your plan.

**Comment by reyman** [comment]
I see there is a papis.el, that really interesting. Actually the problem is the "citation ecosystem", there are very different tools co-existing. I don't know if you see, but citation **is included natively** into org mode, so i manage to use this **without org-ref** dependency : https://blog.tecosaur.com/tmio/2021-07-31-citations.html and https://blog.tecosaur.com/tmio/2021-10-31-release.html

So, actually i'm using native citation engine with the great citar package (named bibtex-actions in the past) developped by bdardus : https://github.com/bdarcus/citar

Citar and Org have some function to open directly pdf based on `file` field existing in .bib file : 
- https://github.com/bdarcus/citar#files-file-association-and-file-field-parsing
- https://github.com/bdarcus/citar/blob/79512aefdf11071b66908320aa346255dd349234/citar.el#L558

So if imagine there are two workflows possible using papis to open PDF directly by clicking on cite : 

**First WF :** 
- using papis to export to generate a `.bib` with `file` field.
- using org native citation and citar function to open the `file`

**Second WF :** 
- link citar function with `papis-org-ref-get-pdf-filename` that crawl directly the `folder` used to store yaml and pdf.

**Comment by alejandrogallo** [comment]
That is really interesting, I made papis.el before oc came out
so yeah, maybe we can simplify papis.el with `oc` and `citar`,
that'd be awesome.

Thank you for this, I made a test, I think your first solution is the best, but I don't know if having the full path to the document
is the best option, probably not, maybe for ad-hoc projects then this is fair enough. But as I understand most of these programs
work by giving the path to a folder and having the format for the pdfs like `bibreference.pdf` or whatever. Is this what citar is expecting also? 

What I did now is to dfine the config option in 2be73ce
 `bibtex-export-zotero-file`
that you have to set to true to have Zotero like semicolon separated
list of files, you can do



```
papis -s bibtex-export-zotero-file True export -a --format bibtex einstein
```

and this should work, maybe you can test it with citar that it is what
is needed in these cases. In this case I'll merge to master.
Soon I should do release 0.12...

**Comment by alejandrogallo** [comment]
So I tested citar and org-ref with a special configuration where the
`bibtex-completion.el` package also works more or less according to my
tests like the citar package. So for me this makes it very useful and
I am for adding it.

What I normally do is that I have the following alias

```sh
papis_update_bib() {
  set -x
  rm ~/Documents/papers/bibfile.bib
  papis export --all --format bibtex -o ~/Documents/papers/bibfile.bib
  (cd ~/Documents/papers/; git add bibfile.bib; git commit -m 'Update bib')
  set +x
}
```
and so on, it is a fair enough solution, and now opening the pdfs we don't have
to make an extra papis call which for my old computer is a good thing ;)

Did you get to do some testing? For me it's good enough to go then,
I will document it also in papis.el during the weekend.

**Comment by reyman** [comment]
Great, i will also try this this week end ! Thanks @alejandrogallo

**Comment by reyman** [comment]
I checkout the branch with your commit, but i actually failed to generate a bibtex file with `file =` from papis folder.

I try `papis -s bibtex-export-zotero-file True export -a --format bibtex -o 2nbrain.bib`

Perhaps my yaml are bad formed due to multiple import : 
```
  GNU nano 5.4          ./ec07634a25ea48f3fb964f94b2b36bc2-chorley-richard-j./info.yaml                   
author: Chorley, Richard J.
author_list:
- family: Chorley
  given: Richard J.
file: /home/reyman/Sync/PDF_Webfaction/Chorley_1962_Geomorphology and general systems
  theory.pdf
files:
- chorley-1962.pdf
journal: Geological survey professional paper
pages: '14'
project: PHD
ref: Chorley1962
title: '{Geomorphology and general systems theory}'
type: article
url: http://pubs.usgs.gov/pp/0500b/report.pdf
volume: 500-B
year: '1962'
```

The `file` is an old link from zotero import.
The `files` list contain the `pdf` (one or multiple) in the folder. 

If we have multiple file attached to 1 folder (not so uncommon actually ...) perhaps it's better to write something that take the first on this `files` list by default for the export ?

**Comment by alejandrogallo** [comment]
ah yes, sorry I did this so that only there will be an export if "file" is not already a property in the yaml, but I can relax this.
It would be a good idea anyways to remove all your `file` keys from your yamls.

Right now there is no limitation for the number of files, but the format is the following

`file1.pdf;file2.pdf;file3.pdf;`

So, right now you can remove the `file`, I commited this  here 1168f6f, now it should work even if you have "file" in the yaml

**Comment by reyman** [comment]
Ok, i retest now, with 
```
     /home/reyman/Notes/Papers/ec07634a25ea48f3fb964f94b2b36bc2-chorley-richard-j./info.yaml             
author: Chorley, Richard J.
author_list:
- family: Chorley
  given: Richard J.
files:
- chorley-1962.pdf
journal: Geological survey professional paper
pages: '14'
project: PHD
ref: Chorley1962
title: '{Geomorphology and general systems theory}'
type: article
url: http://pubs.usgs.gov/pp/0500b/report.pdf
volume: 500-B
year: '1962'
```
I obtain this : 
```
  GNU nano 5.4                                   2nbrain.bib                                             
@article{Chorley1962,
  _papis_local_folder = {/home/reyman/Notes/Papers/ec07634a25ea48f3fb964f94b2b36bc2-chorley-richard-j.},
  author = {Chorley, Richard J.},
  journal = {Geological survey professional paper},
  pages = {14},
  title = {\lbrace{}Geomorphology and general systems theory\rbrace{}},
  url = {http://pubs.usgs.gov/pp/0500b/report.pdf},
  volume = {500-B},
  year = {1962},
  file = {/home/reyman/Notes/Papers/ec07634a25ea48f3fb964f94b2b36bc2-chorley-richard-j./chorley-1962.pdf>
}
```
So that seems good.

So to be sure, the good way to define multiple pdf file in yaml is not : 
```
files:
- chorley-1962.pdf
- chorley-1962.html
 ```
 but 
 ```
 files: chorley-1962.pdf;chorley-1962.html ?
```

**Comment by alejandrogallo** [comment]
> So to be sure, the good way to define multiple pdf file in yaml is not :

No, I meant that the output file in the *bibtex*
will be a zotero format, i.e., a `;` separated list of files,
so if you have in your yaml

```yaml
files:
  - a.pdf
  - b.pdf
```

then in the bibtex you'll have

```bib
@ref{article,
  ...
  file = {a.pdf;b.pdf},
  ...
}
```

so to be clear, now it should work even though you might have some
zotero remainders from the import as you had before with

```yaml
file: /home/reyman/Sync/PDF_Webfaction/Chorley_1962_Geomorphology and general systems
  theory.pdf

```

in your yaml, which as you said comes from the importing from zotero.

**Comment by reyman** [comment]
Great ! Thanks again, if you need some help for documentation, i will be happy to help you by writing some paragraph when i test such use case.
I don't know if that help you, but one place to list all things that miss actually in the doc could be a great place to start.

**Comment by alejandrogallo** [comment]
I documented the setting and merged into master. About documentation, feel free to write in the documentation (or link
a blog post or something) about your workflow with papis and emacs packages citar and oc, that would be very useful, 
either in papis documentation or maybe separate in `papis.el`, if you find the time ;) 
I have to document somewhere that the correct setting for working with this papis bibligraphy thus exported is setting
```lisp
  (setq bibtex-completion-pdf-field "file")
```
this seems to work with the `file` keyword as implemented now.

Cheers!

**Comment by alejandrogallo** [comment]
thanks for the info, that's nice!
