### ISSUE TITLE
`papis edit` does not update cache; what is the intended workflow/use-case for this command?

### ISSUE THREAD

**Issue by kwand** [papis/papis#360]
Perhaps this is more of a flaw of my current workflow and less of a bug, but I do admit that I'm a bit confused about what `papis edit` is intended for.

I'm often using the command to add tags after doing `papis add`, as I prefer VIM to a multi-line command in the terminal, but I'm finding that it doesn't actually update the tag values in the cache? (i.e. I have to run `papis --cc` every time I do this to clear the cache, so that it's rebuilt upon the next run)

As far as I can tell on the documentation, `papis edit` seems to mention use cases for adding notes, marks and such - I haven't had to use any of these features yet, so I can't tell what it's behaviour is with regards to the cache.

Is there some other command that I should be using to update/remove tags, or is this a bug that the cache is not being updated?

_____________________________

**Current workflow**:
1. `papis add` document
2. Find that I want to add some, or more, tags to a document. Run `papis edit` and do so within Vim.
3. `papis --cc` to clear cache, so changes are reflected in cache
4. `papis open`, using tag as query

**Ideal workflow**:
1. `papis add` document
2. `papis edit` to add tags
3. Directly run `papis open`, using tag as query without clearing cache with `papis --cc`.

(I'm aware my ideal workflow can be done by disabling the cache altogether, but that's not what I would consider ideal)

**Comment by alejandrogallo** [comment]
Hi,
thank you for your detailed issue, this is indeed a bug. I just fixed it, I don't know how I did not notice
this before and how it got there...

Thank you very much!
