### ISSUE TITLE
How to export subfolder

### ISSUE THREAD

**Issue by storopoli** [papis/papis#362]
How do I export a whole subfolder?

Tried `papis export 'folder:name_of_the_folder'` and tons of others things.
No mention in the documentation, docstrings or issues.

In the issue #152, @alejandrogallo suggest to use:

```bash
papis export subfolder=name_of_the_folder
```

but to no avail.

Thanks for the great CLI utility it is amazing!

**Comment by alejandrogallo** [comment]
Hi @storopoli 

I guess what you are trying to do is something like

```
papis export --doc-folder path/to/folder
```
This is a more straight foward way to do that, does this help you ? 
Best.

**Comment by alejandrogallo** [comment]
hmmm that is weird, can you clear your cache and do it again?
`papis --cc`

**Comment by storopoli** [comment]
Same:

```bash
❯ papis --cc
WARNING:db:cache:clearing cache /home/storopoli/.cache/papis/database/da593c6508050c57a2a48c38a1ffce5e-papers
❯ papis export --doc-folder ~/.local/share/papers/stats
INFO:cli:export:Dumping to stdout
@article{,
}

```

**Comment by storopoli** [comment]
Ok I have some updates.
This exports the whole folder:

```bash
papis export --doc-folder $HOME/.local/share/papers/stats/causality --folder -o temp
WARNING:cli:export:Only --folder flag will be considered
INFO:cli:export:Exporting doc  -  to temp
```

But just because the `--folder` flag is being considered.

I would like to export as bibtex a whole subfolder with papis.

**Comment by alejandrogallo** [comment]
sorry, I did not realise that your first example was wrong.
I thought you wanted to export a single document, to be on the same page,
a papis documents is a folder with an `info.yaml` file and a library is a set of papis documents.

IF you want to target a single document's folder with export, you should `--doc-folder`, which in your example it would be

```
doc="/home/storopoli/.local/share/papers/stats/01efeb2d4fa75ac1d7045f9f913acea5-jaynes-edwin-t."
papis export --doc-folder $doc
```

Now, I suppose you have a buch of papers in
`/home/storopoli/.local/share/papers/`
and also on
`/home/storopoli/.local/share/papers/stats`.

# Tagging
What I would do is to tag all papers in stats accordingly,
and do
```
papis export tags:stats
```

# Shell scripting

or alternatively what you can do is the following

```
subfolder=/home/storopoli/.local/share/papers/stats
for folder in $(find $subfolder -name info.yaml  -exec dirname {} \;); do
  echo exporting $folder
  papis export --doc-folder $folder
done
```
and so on.

I think I did not interpret your quetion correctly the first time.

**Comment by storopoli** [comment]
I did this, but is definitely very very slow:

```bash
#! /usr/bin/env bash
# papis-short-help:  Export a subfolder

if [[ $1 = "-h" ]]; then
  echo "Export a subfolder"
  cat <<EOF
Usage: papis fexport subfolder output.bib
EOF
  exit 0
fi

subfolder=$1
output_file=$2

# create output file
touch "$output_file"

for folder in $(find "$subfolder" -maxdepth 2 -name info.yaml -exec dirname {} \;); do
  echo "exporting" "$folder"
  papis export --doc-folder "$folder" -f bibtex | tee -a "$output_file"
done

echo "done exporting"
```

**Comment by alejandrogallo** [comment]
Well, now another way of doing this would be

```
papis -l /home/storopoli/.local/share/papers/stats export --all
```

This will probably be faster and I guess better, yes, you can use a
library by path and unnamed.

In hindsight I guess I should just have started with this as a solution.

**Comment by storopoli** [comment]
This is way faster! Thanks!
