### ISSUE TITLE
Adding Hash to document for namming folder strategy

### ISSUE THREAD

**Issue by reyman** [papis/papis#364]
Hi,

I take some time to reread the code to manage folder name when adding document.

The `get_hash_folder(data: Dict[str, Any], document_paths: List[str]) -> str: )` seems called only when we are into [default strategy (code here)](https://github.com/papis/papis/blob/00baeeb891c6ff400a9bff4cc0c7754dd9b3e723/papis/commands/add.py#L306 )/

So it could be cool to add the hash directly as an attribute of doc to define something like that: 

`add-folder-name = {doc[author_list][0][family]} - {doc[year]} - {doc[hash]}`

**Comment by alejandrogallo** [comment]
sure you could do this, but only for the building of the folder name or keep the hash forever.?

Related to this, one of the things that is left to be done in papis is creating a unique identifier for
every paper,this is kind of missing right now, that hash would be a good candidate probably,
but then everytime that a paper is added to the database has to be checked for having a hash and if not add one,
probably under the name `_papis_id` in the yaml or something like that.

I'm not yet sure, but this would certainly ease the work of things like implementing new database backends or
apps like the webapp and so on.

**Comment by reyman** [comment]
Actually this is only to build the folder name but ...  you're right, a forever hash, accessible and stored into the yaml will probably simplify lot of things ! 

Into org-roam for example they use something like that, generating an unique ID PROPERTY (ex `:ID:       c4c543a1-fa0d-458a-80b1-ed87fdbe86d7`) for each note.

**Comment by alexfikl** [comment]
We now have a `papis_id` in each document that acts as a sort of unique identifier. This seems to address the issue you had (even though it won't be the same as the hash generated by `get_hash_folder`).

Feel free to reopen if there are additional issues!
