### ISSUE TITLE
papis add --from url fails

### ISSUE THREAD

**Issue by Inkbottle007** [papis/papis#365]
* papis version (`$ papis --version` or commit number):

papis, version 0.11.1

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
$ papis add --from url https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.124.171801/
Usage: papis add [OPTIONS] [FILES]...

Error: Invalid value for '--from': 'url' is not one of 'arxiv', 'bibtex', 'crossref', 'doi', 'folder', 'lib', 'pdf2arxivid', 'pdf2doi', 'pmid', 'yaml'.
```

The command above is copied from the documentation. There is a similar line in `add.py`.

**Comment by alejandrogallo** [comment]
Thank you for noticing, you should just use it without the `--from url` part, and it should work.

I updated the documentation to be consistent.
Thank you
