### ISSUE TITLE
Using github discussions

### ISSUE THREAD

**Issue by jghauser** [papis/papis#369]
We used to have a zulip chat, but I think that idea sort of fizzled out. What do you think about enabling github discussions? It might help having some place for questions, to keep those separate from actual bugs and feature requests. Github discussions works well without people having to use yet another platform. Of course, if you prefer just using issues for that, that's fine too :).

I'm asking because -- surprise! -- I have a question. I actually wrote it on zulip ages ago and just now was reminded of it.

**Comment by jghauser** [comment]
That was quick! :)

**Comment by alejandrogallo** [comment]
I agree, I don't know, I could not keep up, login in and everything, I could not find the right workflow, sorry about that. Even though the zulip people were suuuper nice.
Let's see how the discussions work, I have not used them yet :)

**Comment by jghauser** [comment]
Yeah, I totally understand! It just gets too much when there's yet another platform to keep track of. Like this it's all centralised and not really any extra work to manage (I hope!). And also it's less of a barrier for people to post if they already have a github account.

**Comment by alejandrogallo** [comment]
FYI, I registered a libera channel under #papis, I intend to be quite online there, maybe this is also something to do some light chatting, not so much for complicated questions, if people use irc anyways ;)
