### ISSUE TITLE
ref-format config does not apply to entries added via arXiv link

### ISSUE THREAD

**Issue by matchatealeaf** [papis/papis#376]
* papis version : 0.11.1

`ref` entry in `info.yaml` file for an entry added via an arXiv link always default to their arXiv identifier instead of the `ref-format` set in config file.

Steps to reproduce:

1. Set `ref-format = {doc[author_list][0][family]} {doc[title]:.10}{doc[year]}` in `~/.config/papis/config`.
2. Run `papis add https://arxiv.org/abs/2204.09689`
3. Check `info.yaml`: `ref: 2204.09689v1`

On the other hand, for a non-arXiv link:

1. Run `papis add https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.128.160402`
2. Check `info.yaml`: `ref: AubrunEntangleme2022`

Which is the expected `ref` format.

**Comment by alejandrogallo** [comment]
I can confirm it.

**Comment by alexfikl** [comment]
#483 should fix this particular issue. Let me know if you get a chance to test it and see if it works!

**Comment by fbearoff** [comment]
I am seeing the same issue above with the pubmed importer

**Comment by alexfikl** [comment]
> I am seeing the same issue above with the pubmed importer

Good catch! I reworked #483 to generally not get a `ref` from the importers and downloaders. It doesn't seem like others are affected, so fingers crossed!
