### ISSUE TITLE
Cleaning notes-name

### ISSUE THREAD

**Issue by jghauser** [papis/papis#390]
I just tried out using jinja2 formatting for the `notes-name` (as implemented by @gouderm in #382). It works quite well but the resulting name isn't cleaned as are for example the folder and document names (using `papis.utils.clean_document_name`). Is that on purpose? I would love to have the notes files have names consistent with the other documents.

I'm on latest master.

**Comment by alejandrogallo** [comment]
yes, that would make sense, one should use the function
```
papis.utils.clean_document_name
```
to clean the notes path name in the same way that it is done otherwise,
do you want to give it a go in the pull request?

**Comment by jghauser** [comment]
Yes, I can make a PR. :)
