### ISSUE TITLE
Getting abstract of publications

### ISSUE THREAD

**Issue by sazam0** [papis/papis#392]
Hi,
My workflow heavily depends on the abstract, I am a long-time Mendeley user, and it saves the abstract in the bibliography. I am interested to move to the papis, 

Is there any option/way to save the abstract in the bibliography or as a note in the yml file?

Please direct me to the link if it is already available/discussed. 

Thank you for your time.

**Comment by alejandrogallo** [comment]
Hello,  

what do you mean exactly by saving the abstract in the bibliography?
Do  you mean when you add a paper from an online source or from your mendeley bibliography?

Normally when you add for instance a paper
from the Arxiv, the abstract field gets added in the `info.yaml`
file

```yaml

abstract: yadah yadah
  yadah yadah
  yadah yadah
  yadah yadah
```

But not  all sources are able to retrieve the abstract from online sources.


If you already have an abstract you can just store it in the yaml file
like

```
papis edit
```

and with your editor of choice you just add the abstract as an additional field.


I would need further workflow details to be able to assist more effectively.

Cheers!
Ale

**Comment by sazam0** [comment]
my bibtex file generated by Mendeley has an "abstract" field and it contains the abstract of the paper. So far it fills the abstract from all major publications (e.g., IEEE, arxiv, springer, sciencedirect, ....) .  Following is a sample entry: 
@article{aaa2019,
abstract = {aaaa bbbb},
author = {...},
doi = {...},
file = {.....},
keywords = {...},
title = {.....},
......
}
for me saving into the yaml file will also work.  but editing for each pdf is a lot of work.
As far as I know, Zotero does the same as well, but I am not ok with their file management system.

I was wondering if papis extract the abstract by itself. I am glad to know that you offer it for arxiv now.
Do you have future plans to expand the feature with other publications?

**Comment by alejandrogallo** [comment]
For several other publications papis can also get it, as long as the journals provide the abstract in the bibtex file.
Also if you just say

```
papis add your-url...
```
it will try out several possibilities including a fallback downloader, which tries to get abstract information from the website, however it is not (yet?) bulletproof. Our hope is that over time we can either leverage some of the zotero translators
in python or in the webapp or just expand the list of downloaders that we ourselves implement.
