### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#40]
Hi Alejandro, 

I like the idea in `ROADMAP.md` of a logo, so I went ahead and designed one. Perhaps this thread would be a good one to post logo ideas until you decide on one you like.

Thanks!

![papis_logo](https://user-images.githubusercontent.com/14098929/35749550-80915e90-0817-11e8-9857-b657d671f81b.png)
 or 

![papis_logo_2](https://user-images.githubusercontent.com/14098929/35753198-53e6a3ca-0824-11e8-81b5-0f94bb1ad837.png)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hi Michael, thanks a lot for this.

**Comment by michaelplews** [comment]
I have both in svg format and can commit whichever one we like. Personally I like the second one with just `papis_`. I'll give it a few weeks for others to comment/vote/add though.

**Comment by alejandrogallo** [comment]
Sure let's give it a rest for a few week and then let's see!
thanks again!

**Comment by nico202** [comment]
If I can vote I prefer the first one, with a smaller frame (less green) maybe.

**Comment by michaelplews** [comment]
@nico202 Thanks for voting. I'll take everyone's comments and make some more mockups after we've given others a chance to voice opinions.

**Comment by nico202** [comment]
@michaelplews can you propose also a possible design for an icon?

**Comment by alejandrogallo** [comment]
As an icon I was thinking maybe something like a puppy cartoon, since papis sounds like puppies in english, it would be funny, I don't know if you guys think it's too much ;)

**Comment by michaelplews** [comment]
I could give this a go.

**Comment by michaelplews** [comment]
@alejandrogallo sorry for all the PRs and updates. Suddenly had a lot of free time and wanted to work on this. I tried incorporating the 'puppy' idea in to the logo but I found it pretty difficult; I could see no good way of getting it simple enough without sacrificing the message of the application.

I went with something simpler instead. @nico202 mentioned they would like a smaller border around logo 1. I did that, and changed the font to [Overpass Mono](https://fonts.google.com/specimen/Overpass+Mono) (Google Fonts, OTF license). For the logo I simply shortened `>papis_` to `>p_`. Let me know what you guys think, I included a few extra colour options too.

# Banner
![papis_logo_3 svg](https://user-images.githubusercontent.com/14098929/40851011-bbf9b3d4-658b-11e8-9e55-67917222a716.png)
![papis_logo_3_blue](https://user-images.githubusercontent.com/14098929/40850996-b3ca2842-658b-11e8-9199-5796f53811ac.png)
![papis_logo_3_orange](https://user-images.githubusercontent.com/14098929/40851025-c42bb584-658b-11e8-82f3-d85cea32f5be.png)
![papis_logo_3_purple](https://user-images.githubusercontent.com/14098929/40851031-c6270e92-658b-11e8-9c72-13a7bcddbc3d.png)

# Logo
![papis_logo_3_sq](https://user-images.githubusercontent.com/14098929/40851054-d4638ff8-658b-11e8-98fd-48392e26648c.png)
![papis_logo_3_sq_blue](https://user-images.githubusercontent.com/14098929/40851055-d4827044-658b-11e8-9b46-5080da53de32.png)
![papis_logo_3_sq_orange](https://user-images.githubusercontent.com/14098929/40851056-d49e44cc-658b-11e8-93a4-b87e2460f355.png)
![papis_logo_3_sq_purple](https://user-images.githubusercontent.com/14098929/40851057-d4b684a6-658b-11e8-9822-7230a63f06d0.png)

**Comment by michaelplews** [comment]
# Blue
![papis_blue](https://user-images.githubusercontent.com/14098929/40935945-4dde740e-67ff-11e8-9faa-3edb0b5fe64f.png)

**Comment by michaelplews** [comment]
# Green
![papis_green](https://user-images.githubusercontent.com/14098929/40935983-635b5efa-67ff-11e8-8465-af86c45717b5.png)

**Comment by michaelplews** [comment]
# Orange
![papis_orange](https://user-images.githubusercontent.com/14098929/40935995-6d14dcb4-67ff-11e8-97c9-20740eda0bbf.png)

**Comment by michaelplews** [comment]
# Purple
![papis_purple](https://user-images.githubusercontent.com/14098929/40936008-7860305a-67ff-11e8-8774-aa98b93d43c8.png)

**Comment by michaelplews** [comment]
@alejandrogallo It's been about 2 weeks since I updated these so I think we have all the votes we're going to get. Would you like to pick one? Or if you have suggestions for improvements?

**Comment by c-bg** [comment]
thanks for those logo drafts :D one small question: could it be that the kerning changed from the first draft to the ones below? the "a" seems to almost touch the first "p"; I personally would suggest to perhaps increase that spacing a bit? :) what do you think? :) (only throwing out suggestions here, happy to hear different opinions)

**Comment by c-bg** [comment]
also I took 3 minutes to draw a small back-of-the-envelope sketch of an icon with a puppy ;) 
It could be made a lot more minimal. However perhaps it wouldn't fit the other logo, even if "minimalized", in which case this sketch has the purpose of general entertainment ;) :)  
![image](https://user-images.githubusercontent.com/32343021/82062637-b1df8f00-96ca-11ea-8dd9-13e1f1158779.png)

**Comment by kiike** [comment]
A logo would be great for the windows executable! I love the suggestions here, especially the puppy or the green logo >p. Now that papis is uppercase it looks more like a python too, which is a bonus! >P

**Comment by jghauser** [comment]
I actually asked a friend the other day whether he'd be willing to contribute a logo (he's designed logos in the past and has professional experience in this field). He said he'd be happy to make one. Imma follow this up next week and report back :)

**Comment by jghauser** [comment]
So I talked to my friend last week and he said he'd be happy to create a logo for us. He'll get back to me next week with a plan 😀

**Comment by jghauser** [comment]
We should have something by next week :tada:

**Comment by jghauser** [comment]
I've been writing back and forth with my friend a bit about the logo. At first, we were looking at logos more generally, but in the last iteration, he's focused on logos that are/can easily be square app icon type things. I think this would probably be the most important in Papis' case. I'm attaching a PDF here with the current options. Basically, he would like to get some feedback and could then elaborate things from there.

Let me know what you think @alexfikl, @kiike, @alejandrogallo.

I think i most like nr 4, 11, 12, 15 (by page numbers). 

[PAPIS.pdf](https://github.com/papis/papis/files/15394741/PAPIS.pdf)

**Comment by alejandrogallo** [comment]
I have a similar view as you, I would like the clip one but maybe adding something like that?
![21-05-24_21:59:14](https://github.com/papis/papis/assets/12715358/fef993c2-00f7-4307-926c-7af3c15416a4)

with the correct perspective and so on... and maybe with the correct font

**Comment by alexfikl** [comment]
OMG! This is happening! :heart: 

I'm also quite partial to the paperclip one that @alejandrogallo showed (page 12?).

I'm not sure about adding text though, since that won't look very good on smaller sizes. Maybe instead of the rectangle there, it could have one of those "command-line" symbols like 15 or 18? Maybe even make 15 more paperclippy at the bottom? (I'm assuming the paperclip is a shorthand for organizing?)

**Comment by jghauser** [comment]
@alejandrogallo, thanks for the feedback! I'm not sure we can fit the whole name of Papis in there. Once the thing is as small as logos often get, it won't be very legible anymore. I think we can have a logo that has the text "Papis" under it that we can use where a small squre tile isn't required -- but the logo itself should also look good and distinctive when small. I think we need something that is recognisable and maybe has the "P" in it to hint at Papis.

**Comment by jghauser** [comment]
I can ask him if we can make the paper clip logo a bit more "nerdy" in some way :blush:

**Comment by alejandrogallo** [comment]
I'm neutral with regard to color, but the orange of @michaelplews up there looked quite nice, but probably someone else other than me should decide... :D

**Comment by jghauser** [comment]
We could add something like the symbols of 15 and 18, which get across the nerdiness and can even be read as a "P". I do wanna ask my friend though to see if he thinks the logo would get to busy.

**Comment by alejandrogallo** [comment]
that was a good idea
![21-05-24_22:23:20](https://github.com/papis/papis/assets/12715358/d3341bd4-afd2-4b32-9cb0-b8bbee4e9f04)

here the svg file if someone wants to play with it
![logo](https://github.com/papis/papis/assets/12715358/5deef979-9987-4497-9b09-5368df1f2c12)

**Comment by kiike** [comment]
15 is my favorite, then the paperclip one. I like most of the designs! :clap:

**Comment by jghauser** [comment]
Thanks for all your feedback. I'm gonna talk to my friend again and maybe we can iterate on the two designs that were well liked (12, 15) though it looks like 12 is a clear favourite at the moment :).

**Comment by jghauser** [comment]
Second round for the paperclip idea: 
[Papis - PaperClip.pdf](https://github.com/papis/papis/files/15402985/Papis.-.PaperClip.pdf)

Colours are just to show some of things that are possible :).

I probably like nr 4 best even though it's a departure from our attempt of making it nerdier. However, it manages to get Papis in there and still look nice when small. It's also very unique. Nr 1 I also like a lot.

**Comment by jghauser** [comment]
> If I may offer 2 cents
> 
> I think some sort of terminal prompt -esque symbol fits the project better than `</>`, isn't that an XML/HTML thing and why is it here?
> 
> Terminal prompt -esque symbols:
> 
>     * `$`
> 
>     * `>`
> 
>     * `$_`
> 
>     * `>_`

Thanks for the feedback! Yeah, maybe these would be better. The reason why the html-esque symbols are in there is a combo of my friend not having a clue about cli and us wanting something that sorta looks like a "P". :grin:

**Comment by alexfikl** [comment]
> Second round for the paperclip idea: [Papis - PaperClip.pdf](https://github.com/papis/papis/files/15402985/Papis.-.PaperClip.pdf)
> 
> Colours are just to show some of things that are possible :).

I'm also most on board with 1 (maybe with a different symbol in there, like @tuurep suggested). For the colors, I'm leaning towards the green in 1 and the red in 3, but I'm far from understanding colors (even a bit red-green colorblind, for irony :D).

For some dissenting opinions: 
* I quite like 2 as well (especially the yellow-black combo), but not sure what to do with that if we don't use `</>`.
* Is the perspective on 1 ok? it seems a bit too narrow on top for me? But that might just be from staring at it too much..

**Comment by jghauser** [comment]
Here's one with more terminal prompt-y symbols! Looks even better actually :)

![Untitled](https://github.com/papis/papis/assets/10319377/58fb270a-e8bd-44c6-b710-dfc086e09d53)

**Comment by jghauser** [comment]
> * Is the perspective on 1 ok? it seems a bit too narrow on top for me? But that might just be from staring at it too much..

To me it looks alright, but we can play around with changing things. Did you mean that the top-most point could be further to the left?

**Comment by alexfikl** [comment]
> To me it looks alright, but we can play around with changing things. Did you mean that the top-most point could be further to the left?

I'm not sure if it's off, just wanted to mention it. But yes, I did mean either the pointy top-left point more to the left or the curved top-right point more to the right.

**Comment by jghauser** [comment]
Ok, I'll wait to see what the others have to say and include that in my next round of feedback to my friend :)

**Comment by alejandrogallo** [comment]
I love it, you have my vote! I think it's brilliant, I'm unsure about the color, I like the fact that the surface of the clip is in a darker color reminding of a terminal, although I use white background terminals ;)

**Comment by jghauser** [comment]
My friend made a couple new versions, now focusing on colour options. But first a few comments.

1. We checked the perspective, and found that changing things makes it worse. Which makes sense, as my friend told me he got the perspective by simply making a small version of the paper clip to get the perspective projection. Which sounds like the right thing to do :).
2. I hope it's ok we're just focusing on the paperclip logo. I did initially say we would also work on some versions of nr. 15 that @kiike and I also liked, but after the very clear endorsement of the paperclip, I decided this is the way to go.
3. We changed the writing to "Papis" to match our spelling (although we probably mostly need the image-only logo where this doesn't matter).

So, basically all there's left to be done is picking the colour. Here's some new options (mostly based on previously expressed preferences for green, red, and dark backgrounds):
![WhatsApp Image 2024-05-27 at 12 43 55](https://github.com/papis/papis/assets/10319377/e35a002c-923c-41c9-abf1-fcd4929d494a)

Colour options from previous rounds are of course still possible too :blush:. Let me know what you think!

Me personally I'm finding it hard to decide :sweat_smile:. I kinda like the original white foreground on green background, even if it's maybe a tad on the boring side. Or maybe the red version (last one in the second row), though I think I'd prefer a white, or at least lighter, foreground. I've asked my friend to give some more versions with less colourful foregrounds.

**Comment by jghauser** [comment]
![WhatsApp Image 2024-05-29 at 16 57 20](https://github.com/papis/papis/assets/10319377/dd8e6ed7-f41b-42f7-8c69-e49f95084efa)
![WhatsApp Image 2024-05-29 at 16 56 51](https://github.com/papis/papis/assets/10319377/2186e424-e7a7-44f6-8a5a-e1b7e5ff5b1a)

Some more with the paperclip in just black or white.

**Comment by jghauser** [comment]
And this (I like how it evokes the old green-on-black terminals): 
![2024-05-29T17:05:29,649869187+02:00](https://github.com/papis/papis/assets/10319377/8013b4bb-436c-4ac7-87d7-1c3151eed19b)

**Comment by alexfikl** [comment]
I really can't say about the color.. many of them look quite nice to me :( The only ones that I can say stand out are the black-on-yellow and yellow-on-black ones, but the blue/green variants also look very nice :grin: 

Some pragmatic points thought:
* It should be something with good contrast so that it's clear for everyone and different screens.
* Maybe we want a both a dark-logo/light-background and light-log/dark-background so that we can easily change in various light/dark color schemes? E.g. I have an automatic "switch to dark mode at night" plugin for Firefox that quite annoyingly makes some plugin icons disappear :heart:. I'm not sure if this icon will get used in such a setting, but just a thought..

@jghauser Thank you for checking the perspective thing! I assumed that it was done in software and my mind was just playing tricks on me, but yeah :confounded:

**Comment by alexfikl** [comment]
> Yeah same here! Actually now that you mention it, I do also like the yellow on black one haha. You mean these colours, right?

Yep, those are the ones I meant :grin: 

> I use such a plugin also, and whether it works seems to be hit or miss. I thiiiink that it should leave logos alone (as it does with photos) and that the logo should simply look good on both dark and light backgrounds. I think such plugins do support alternate logos, but only on websites that implement dark and light modes (including [github](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)). 

At least for Firefox WebExtensions, there's some way to specify some icons based on Light / Dark, e.g. see `theme_icons` in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action. I'm not sure it's worth worrying about that right now, but just wanted to mention it.

> I think we should leave the foreground colour at least alone though, to keep the logo recognisable.

Yeah, that's a good point!

> any other preferences regarding colour?

I mostly prefer the black/yellow one and the blue and green ones from https://github.com/papis/papis/issues/40#issuecomment-2137640236. 

I don't think I can pick one though :confounded:, so I would definitely defer to your friend for a final decision on what looks best considering where it'll be potentially used: e.g. in the README on Github, as the profile picture on Github, as a small icon in the Firefox/Chrome toolbar, etc.

**Comment by tuurep** [comment]
Some that look good to me on intuition:

![image](https://github.com/papis/papis/assets/15036238/d763b6c8-ac67-4f07-8f8c-88b871f90934)
![image](https://github.com/papis/papis/assets/15036238/637dc8eb-ae9d-4e7f-9ae7-daabc945a0d4)
![image](https://github.com/papis/papis/assets/15036238/a0a67a5c-15a3-4c97-890d-f4527ab2de55)
![image](https://github.com/papis/papis/assets/15036238/2851dba8-2859-4c67-8925-9f5e3ff3ba13)
![image](https://github.com/papis/papis/assets/15036238/f6688fd6-50c3-4625-b593-9290273a7b28)

Hmm.. I'm not sure how helpful this is but looks like I prefer the most high contrast or even B&W ones :D

Also I'd like to say that this was a good idea that could have been tried further:

![image](https://github.com/papis/papis/assets/15036238/01d5b663-75a3-4056-80ef-84a71fef94a0)

^ Also looks great with those exact colors, imo!

**Comment by jghauser** [comment]
Hi, just to let you know that I'm going to finalise the logo design with my friend on Monday or Tuesday. We're probably going for a version with a green background as that seems to have been well-liked. If anyone has any last minute comments, now would be a good time for them :). Thank you all for your help in this process, I'm very much looking forward to Papis having shiny new logo! :heart:

**Comment by jghauser** [comment]
I proudly present our new logo! :tada: 

![Papis Tile](https://github.com/papis/papis/assets/10319377/88da7319-9c42-4f2b-affd-8bdf15436c44)

This logo should look nice on both dark and light backgrounds, and it's high contrast.

I'll be adding it to the README later. My friend is also going to make a github social preview thingie, so that the logo will be used by github (@alejandrogallo will need to add that I think). Are there any other places the logo needs to be added (e.g. PyPI)?

**Comment by alexfikl** [comment]
@jghauser It just occurred to me that it would be nice to also add the logo to the documentation on https://papis.readthedocs.io/en/latest. 

For that maybe we can just have a white version with a transparent background with a "Papis" text next to it? I'm thinking mostly this: https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html. That's fairly constrained by the `sphinx_rtd_theme` as well, so not sure we can do much else and still have it look ok..

**Comment by jghauser** [comment]
completed with #883
