### ISSUE TITLE
"add-folder-name"-option creates not a folder hierarchy

### ISSUE THREAD

**Issue by dornhe** [papis/papis#401]
*papis version (0.12 [arch]):*

I set the named option to
add-folder-name = {doc[author]} / {doc[title]}

Expected behavior:
"papis add" creates folders like .../papers/author-names/paper-title/paper.pdf

Actual behavior:
"papis add" creates folders like .../papers/paper-title/paper.pdf

Edit: using {doc[author]}-{doc[title]} resolves to .../papers/author-title/paper.pdf so nested structures seem to be the issue

**Comment by alexfikl** [comment]
Something like this was recently added in #395, but it's not released yet.

For Arch, there's [papis-git](https://aur.archlinux.org/packages/papis-git) in the AUR, if using the `git` version is an option for you?

**Comment by dornhe** [comment]
ah, yes, that solves this issue. any hints on how to automatically remove all points '.' from generated file/dir-names?

**Comment by alexfikl** [comment]
Hm, `papis` does some cleaning for the paths in
https://github.com/papis/papis/blob/b3247777d3afad2f326aeecdf7dd179b24e6e007/papis/utils.py#L137-L153
but it allows dots (for file extensions). There might be some way to do that with `jinja` templates, but I haven't looked at that.

#373 may be worth keeping an eye on?

**Comment by dornhe** [comment]
yes. dots for file extensions are fine. the point is to have no dots excepts the file-extension ones for possible parsing/piping usage later on. and in general I think it just dosnt look good to have random points in the file name, but thats just me.
