### ISSUE TITLE
Webapplication for papis

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#41]
What about trying to get paperhero work with papis?

https://github.com/alejandrogallo/paperhero

**Comment by alejandrogallo** [comment]
With the last two commits in my fork of paperhoero it kind of works, of works a lot more fiddling around
and fix some style issues is necessary, but I'd say that it has potential, is just two commits away
from the original fork:

![screenshot_sun_feb__4_18 40 51_cet_2018](https://user-images.githubusercontent.com/12715358/35780405-25763a6a-09db-11e8-9005-f5504157683d.jpg)

**Comment by PatWie** [comment]
I think paperhero needs an overhaul in the client-side code, it was a very unelegant way of writing it without any planning. If I would need to add features, I would completely start from scratch, like I did here #42. And the best way I see to integrate this frontend is to rewrite most parts, using probably redact or vue.js or whatever is currently hyped. AngularJS was not a very nice experience at all.

Some things on my todo list (I wanted to implement but never had time for) were:
- SublimeText like fuzzy search
- mark multiple files to export bibtex (useful when writing papers)
- drag and drop to add pdf

Things it was never designed for (obvious drawbacks) were:
- no support for multiple download-sources
- no support for multiple files like supplementary, different versions
- share pdf

 I am open to learn basics of vue, redact or whatever to merge both projects. But I definitely cannot stem the entire workload.

**Comment by alejandrogallo** [comment]
Hi Patrick,

**Comment by alejandrogallo** [comment]
So what I was thinking is that for this to work we first need to create a good rpc server for papis,
so that actually other applications can also talk to papis via this server.

If for instance you edit then `info.yaml` file on the frontend, then you should actually do this via
an rpc call to the server. We have to think about a nice design for it.
One thing we need therefore in papis from now on is a strict ``id`` key for documents, which
is broadly done for the ``ref``, but some users got confused by it, so the ``id`` key is free to use
as the new unique identifier.

**Comment by PatWie** [comment]
Just take the path to the pdf as the unique id. 

```
collection
  dirA
    info.yml  # id = collection/dirA
    file.pdf
    file2.pdf
  dirB
    info.yml # id = collection/dirB
```
These are unique and rarely change. Further, it allows to just copy somebody's else collection easily. 

I will create a full prototype (Vue.js + materialize.css) in a separate git to not pollute this repository.
https://github.com/PatWie/papis-webfrontend
I would stick to the 5 api endpoints you currently provide.

Feel free to git-revert the pull-request in the meantime.

**Comment by alejandrogallo** [comment]
I think that's a good idea, anyways I wanted to open an organization github account for `papis`
to decouple it from my github account, so that the such guis and frontend can have their own
repos, I'll be then issuing pull requests there ;)
