### ISSUE TITLE
Move from LGTM.com to Github Code Scanning

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#411]
While waiting for LGTM to finish on #410, found that it's going to go away on December 16th

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

and they recommend moving to Github Code Scanning. The docs for enabling that instead are at

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually

**Comment by alejandrogallo** [comment]
Good idea, let's do this, probably I have to do it, so I'll take a look at it later
