### ISSUE TITLE
Papis citations command

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#435]
I have been a user of the hidden citation feature of papis for a while.
Now with the webapp I have implemented a citation tab that is just
super handy.

I was thinking about creating a command

```
papis citations
```

in order to manage the citations of every paper.

How this works now is that

`papis explore citations`

creates a `citations.yaml`, where we fetch the citations
information from crossref for every citation doi.

In the app, being able to go to the citations tab and just
see them and click the ones that are interesting is just
extremely useful.

For my library with 1500 documents the citations.yaml files amount to
40 MB, which is a breeze.

# Ideas

- design the CLI API
- add a flag in `papis add` in order to also create the citation.yaml file automatically
  when adding a document.
- Create clear functions to be reused by the `papis explore` and webapp

# Questions

- Probably rethink the word citation, since it is quite misleading.
  There is citations and references for words, but `ref` we already took
  for the bibtex refs.
  The harvard db https://ui.adsabs.harvard.edu/abs/1958PhRv..111.1554L/abstract
  uses citations for papers that cite this paper and references for citations the paper
  cites of other sources, which I think it's better, but
  `papis references` will lead the user to think (imo) that she's using the command
  to manage the bibtex references of the library.
![image](https://user-images.githubusercontent.com/12715358/207046011-e6c251de-676a-4389-b443-7dffd4a66726.png)

- SHould `paps add` create the `citations.yaml` file by default?

**Comment by alejandrogallo** [comment]
All done!

**Comment by inevespace** [comment]
Should default behavior of `papis citations` be fetching citations? Currently you need pass -c flag `papis citations -c`. Without it (or other flags) nothing happens.

**Comment by jghauser** [comment]
@inevespace, good question! From a quick glance at the source code, I feel like the command by default (that is, without any flags, so just `papis citations QUERY`) doesn't do anything. I think that default behaviour could be improved :smile:. @alejandrogallo, @alexfikl, what do you think? Might be worth opening a bug report for this.

**Comment by alexfikl** [comment]
> @inevespace, good question! From a quick glance at the source code, I feel like the command by default (that is, without any flags, so just `papis citations QUERY`) doesn't do anything. I think that default behaviour could be improved 😄. @alejandrogallo, @alexfikl, what do you think? Might be worth opening a bug report for this.
> 
> EDIT: we might also want to improve the help text, which currently says 'Handle document citations', to make it a bit more concrete.

Agreed on both accounts! We should be able to make one of those `--fetch-citations` or `--fetch-cited-by` flags mandatory so that the user gets some feedback about it not doing anything.

@inevespace Want to open a new issue to track this?
