### ISSUE TITLE
`papis add` stuck in while loop on linux

### ISSUE THREAD

**Issue by prataffel** [papis/papis#448]
* papis version (`$ papis --version` or commit number): a81e575006b630a3558063cfc6878338ce3bf683
* operating system: linux (result of `uname -r`: `5.15.81-1-MANJARO` 
* python version: `Python 3.10.8`

# how to reproduce the issue
Command and output of `papis --log INFO add --from doi 10.1090/noti963`

```
INFO:importer:doi:Using DOI '10.1090/noti963'
INFO:cli:add:There are 1 possible matchings
INFO:cli:add:Merging data from importer doi
- author:
- author_list:
- doi:
+ author: Gratzer, G.
+ author_list: [{'given': 'G.', 'family': 'Gratzer', 'affiliation': []}]
+ doi: 10.1090/noti963
- issue:
+ issue: 04
?        ++
- journal:
+ journal: Notices of the American Mathematical Society
- language:
+ language: en
?           ++
- month:
+ month: 4
?        +
- pages:
+ pages: 1
?        +
- publisher:
- title:
- type:
- url:
+ publisher: American Mathematical Society (AMS)
+ title: What Is New in LaTeX? VI. LaTeX on an iPad. Empire
+ type: article
+ url: http://dx.doi.org/10.1090/noti963
- volume:
+ volume: 60
?         ++
- year:
+ year: 2013
?       ++++
^^^^^^^^^
diff from
-----  -
+++++ Importer(doi, uri=10.1090/noti963)

Add all[a] Split[s] Reject[n] Quit[q] Cancel[c]
GENERAL DIFFERENCE

```
*papis is stuck forever*

---

As it appears to me, this happens because I am stuck in [this `while loop`](https://github.com/papis/papis/blob/a81e575006b630a3558063cfc6878338ce3bf683/papis/commands/add.py#L308). 

For me, this can be fixed by swapping to `pathlib.Path.is_relative_to` in `papis.utils.is_relative_to` (according to [the documentation of `os.path.relpath`](https://docs.python.org/3.10/library/os.path.html#os.path.relpath), a `ValueError` is only raised under Winows).

**Comment by alexfikl** [comment]
Thanks for the report!

Your analysis seems completely correct, so hopefully it's an easy fix. I'll take a look today or tomorrow, but PRs are always very welcome!

**Comment by prataffel** [comment]
I had a look into this, again, because none of the tests was failing for me on the old commit, either. I noticed that this was due to my config having a trailing slash in the library's directory path, e.g.,

```
[test]
dir = /tmp/papis-test/
```
and therefore, [`temp_path != out_folder_path`](https://github.com/papis/papis/blob/a81e575006b630a3558063cfc6878338ce3bf683/papis/commands/add.py#L309) was `True` when it should not be.

Note that this can tested by adding a slash to `folder` when [creating the test library](https://github.com/papis/papis/blob/a81e575006b630a3558063cfc6878338ce3bf683/tests/__init__.py#L118).
