### ISSUE TITLE
get_clean_doi regex tweak?

### ISSUE THREAD

**Issue by dsanson** [papis/papis#45]
Here is a url that contains a doi:

    http://onlinelibrary.wiley.com/doi/10.1111/nous.12244/abstract

Papis "cleans" this to:

    10.1111/nous.12244/abstract

But that isn't recognized by Crossref. It should clean it to:

    10.1111/nous.12244

which Crossref recognizes.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @alejandrogallo, and @michaelplews.

**Comment by alejandrogallo** [comment]
Thanks! Fixed, it will also fix the issue where `/` is replaced by the html
`%2F` format, which happened to me a couple of times.

Have fun!

**Comment by dsanson** [comment]
It appears doi's are obnoxious. Here is another one:

    https://doi.org/10.1093/analys/anw053

Unfortunately, the `/anw053` is part of the doi, and now gets trimmed off by the regex.

**Comment by dsanson** [comment]
Looking here https://www.doi.org/doi_handbook/2_Numbering.html#2.5 it appears that the doi "suffix" (the part after the first `/`) can include any character, including `/`. So you probably need to revert the regex so that it matches the whole suffice for,

    https://doi.org/10.1093/analys/anw053

and it fails to match correctly for things like

    http://onlinelibrary.wiley.com/doi/10.1111/nous.12244/abstract

If you want papis to handle urls like this Wiley one, I suspect you'll have to do it on a case-by-case basis, which might not be worth it.

**Comment by dsanson** [comment]
FWIW, this google search https://encrypted.google.com/search?q=inurl:doi+inurl:abstract appears to suggest that this thing of having a url that includes a doi followed by `/abstract` is specific to onlinelibrary.wiley.com.

**Comment by alejandrogallo** [comment]
I didn't know doi allows anything in the strings, it does not make a lot of sense to me but I guess
not everything in life necessarily hast to make sense.

Since I guess it might happen again in the future, I'll catch the abstract behaviour and then hope
that a good samaritan like you raises an issue here for a weird journal that breaks our code ;)

Thank you very much David
