### ISSUE TITLE
backspace not detected

### ISSUE THREAD

**Issue by nico202** [papis/papis#46]
in papis open, backspace does nothing while C-H and C-backspace are working.

I think it depends on the terminal emulator (there's plenty of discussiong like 
https://stackoverflow.com/questions/44943249/detecting-key-backspace-in-ncurses)

In my case urxvt the code is 127.

With terminology it is working

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by nico202** [comment]
I'm talking about papis.pick
