### ISSUE TITLE
Config parser doesn't fall back to defaults when 'settings' section missing

### ISSUE THREAD

**Issue by twrightsman** [papis/papis#496]
* papis version (`$ papis --version` or commit number): 0.12

# how to reproduce the issue

I installed `papis` with `pip` inside a venv and before running it for the first time (which I assume might populate a basic config file), I made my own (`~/.config/papis/config`) and added a library. It seems `papis` doesn't fall back to the defaults if the `[settings]` section is not present?

Command and output of `papis --log INFO <command>`:
```
(papis-venv) $ papis --log INFO --version
[...truncated...]
configparser.NoSectionError: No section: 'settings'
(papis-venv) $ pip list
Package            Version
------------------ ---------
arxiv2bib          1.0.8
beautifulsoup4     4.11.2
bibtexparser       1.4.0
certifi            2022.12.7
chardet            5.1.0
charset-normalizer 3.0.1
click              8.1.3
colorama           0.4.6
configparser       5.3.0
filetype           1.2.0
habanero           1.2.3
idna               3.4
isbnlib            3.10.13
lxml               4.9.2
papis              0.12
pbr                5.11.1
pip                23.0
prompt-toolkit     3.0.36
Pygments           2.14.0
pyparsing          3.0.9
python-doi         0.2.0
python-slugify     8.0.0
PyYAML             6.0
requests           2.28.2
setuptools         66.1.1
soupsieve          2.4
stevedore          5.0.0
text-unidecode     1.3
tqdm               4.64.1
urllib3            1.26.14
wcwidth            0.2.6
```

**Comment by twrightsman** [comment]
After adding an empty `[settings]` section, I get the same error as in https://github.com/papis/papis/issues/398. So this may be a duplicate, sorry! I can try the latest master and see if it persists.

**Comment by twrightsman** [comment]
Using the latest master I get the following error:
```
Exception: Library 'papers' does not seem to exist
```

Which seems to be related to https://github.com/papis/papis/issues/249.

**Comment by alexfikl** [comment]
Thanks for the bug report! 
But ouch, there seem to be a lot of issues around this, so we'll take a look asap.

In the meantime, the last error seems to be related to the fact that `papers` is defined as the default library here
https://github.com/papis/papis/blob/699c892ce0ab856717b30cde76cc3c41bb755a48/papis/config.py#L45
You can just add an entry to the config file to point to the library you defined instead.

**Comment by alexfikl** [comment]
@twrightsman Gave this a go in #497 and added some fixes for the scenarios you mentioned.

It would be great if you get chance to test that branch and see if it fixes things for you!

**Comment by twrightsman** [comment]
@alexfikl Your branch fixes the issue! Thanks so much.
