### ISSUE TITLE
Force https as standard

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#50]
It would be nice (and an easy fix) to change every URL to https to encourage security.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
I concur, but where do you mean ? In general across the
code?

**Comment by michaelplews** [comment]
Yes, it should be a quick fix but just change all the base URLs to https:// throughout the code (providing the URL would resolve)

**Comment by alejandrogallo** [comment]
This is done with the update of the downloaders
