### ISSUE TITLE
Change all references based on new ref-format

### ISSUE THREAD

**Issue by JBlocklove** [papis/papis#518]
For a long time I've had my `ref-format` set to `{doc[author_list][0][family]}{doc[year]}` but as my document library has grown that's now become an issue with things overlapping. I'd like to change my reference format but first I'm wondering if there's a way to change the ref of all of my current documents based on a new format? If not, would it be something worth adding? Some sort of command or script that updates all documents based on the config settings when the script is run?

**Comment by alexfikl** [comment]
Ideally `papis update` should be able to do that, since it has support for formatting, so
```
papis update --set ref '{doc[year]}' query
```
should have the expected result. However, `papis update` explicitly forbids updating the reference in
https://github.com/papis/papis/blob/c840ef5b4e9a7670c4dae67c06ad0fd002363d6c/papis/commands/update.py#L75-L77

@alejandrogallo Any thoughts on this? It seems to have been added for https://github.com/papis/papis/issues/80, but I don't really understand the reasoning there?

**Comment by JBlocklove** [comment]
Yeah, I actually tried almost that exact `papis update` command after I posted this once I realized I missed that function, but it didn't work so I assumed there was something else going on.

Based on the comment it seems like the intention is to keep refs the same so that generating a new bibtex file won't screw up all of the already existing `cite` calls in a LaTeX document, but I think it would make more sense to have a warning there as opposed to expressly forbidding it.

**Comment by alexfikl** [comment]
> Based on the comment it seems like the intention is to keep refs the same so that generating a new bibtex file won't screw up all of the already existing `cite` calls in a LaTeX document, but I think it would make more sense to have a warning there as opposed to expressly forbidding it.

Yeah, agreed. The only case where that would be annoying is if the importers changed the ref behind our backs all the time. But that should be a bug and hopefully mostly fixed by #376.

**Comment by alexfikl** [comment]
@JBlocklove Can you check out if #539 does what you had in mind? I tried bulk setting some refs with
```
papis update --all --set ref '{doc[year]}' <query>
```
and it seems to update everything correctly.

**Comment by JBlocklove** [comment]
Seems to work perfectly, thanks!
