### ISSUE TITLE
Bump minimum required Python version

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#550]
Now that 0.13 is out, I was thinking we could bump the minimum required python version, since it's quite old. For some reference, 3.5 went EOL in 2020, 3.6 went EOL in 2021 and 3.7 is about to go EOL.

https://devguide.python.org/versions/

@alejandrogallo @jghauser Thoughts? I was thinking 3.7, but would like 3.8 (having 4 supported python versions seems good enough?)

**Comment by jghauser** [comment]
I think 3.8 seems reasonable. Even debian stable is at 3.9 by now.

**Comment by alejandrogallo** [comment]
Thank you alex for taking the time to do this and also write the rationale.
I also agree, I always have this uneasy feeling about this but you gotta let go :D

**Comment by alexfikl** [comment]
Awesome! Thank you both for pitching in. 

I'll go ahead and merge that in so that we can start working on it and people get a change to complain if they actually need an older version :grin:
