### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#551]
Using `main` is the default on both github and git these days, so we should probably switch to that (it's really messing with my muscle memory too :cry:)

@alejandrogallo @jghauser Thoughts? This would probably just need some changes in the repo settings to update the default branch.

**Comment by jghauser** [comment]
Yeah, let's do that. This seems to be the new standard, and all my other repos are using it too.

**Comment by fixedfloatcom** [comment]
supporting this request

**Comment by alexfikl** [comment]
> I support this

@alejandrogallo Great! You'll have to go to the repository Settings > General > Default Branch (or something like that) to rename it, since I don't have access :grin:

**Comment by alejandrogallo** [comment]
ah sorry, I just did it, I hope hell does not break loose! haha

**Comment by alexfikl** [comment]
> ah sorry, I just did it, I hope hell does not break loose! haha

Haha, yeah, will probably confuse a few people, but it just needs to checkout the new branch and carry on! Github was nice enough to tell me it changed too and what to do locally
```
git branch master -m main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Thank you for making the change!
