### ISSUE TITLE
By default papis does not download pdfs anymore

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#556]
Papis only downloads pdfs now if `--force-download` is passed as an option.

Are we sure we want this behaviour to be the default? This feels quite odd.

**Comment by alexfikl** [comment]
Hm, from #387, it seems like the intended behavior was to download PDFs in the first case (no local file) but not the second (with local file)
```
papis add --from arxiv 'some-arxiv-url'
papis add --from arxiv 'some-arxiv-url' some-file.pdf
```
Does that not work as intended anymore or do you think it's a bad default?

**Comment by alejandrogallo** [comment]
exactly, AFAIK this does not work anymore, a quick test

![22-05-23_15:05:55](https://github.com/papis/papis/assets/12715358/800c8677-eee9-43ad-9ac3-c4ee751bd00a)

but your example works, i.e.
![22-05-23_15:09:48](https://github.com/papis/papis/assets/12715358/71dead57-37be-424f-b7dc-5ed85bb4148c)

So I guess the problem is giving an explicit `--from` flag, which I never do ;)

I'll take a look at it.
