### ISSUE TITLE
deprecated? import zotero.sqlite

### ISSUE THREAD

**Issue by tjallemaal** [papis/papis#560]
* papis version 0.12:

# how to reproduce the issue
Command `papis zotero import --from-sql-folder /home/jank11/Zotero/`
and output of `papis --log INFO <command>`:
```
(when trying to import zotero.sqlite i get this error message:)

Traceback (most recent call last):
File "/home/jank11/.local/bin/papis-zotero", line 8, in
sys.exit(main())
^^^^^^
File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in
call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in
main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/click/core.py", line 1654, in
invoke
super().invoke(ctx)
File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in
invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jank11/.local/lib/python3.11/site-packages/papis_zotero/init.py", line 14, in main
logger.info("library '{0}'".format(papis.api.get_lib()))
^^^^^^^^^^^^^^^^^
AttributeError: module 'papis.api' has no attribute 'get_lib'
```
it seems get-lib can't be called or something like that

**Comment by alexfikl** [comment]
What version of `papis-zotero` are you using? The latest versions are v0.13 for `papis` and v0.1.1 for `papis-zotero`, which no longer have that call and should work together.

From a quick search, `papis.api.get_lib` seems to have been removed in v0.9, which was released quite a while ago.

If you can't get `papis zotero` to work, another option is to export a BibTeX file from Zotero and import that directly with `papis add --from bibtex zotero.bib`. Hope that helps!

**Comment by tjallemaal** [comment]
Alright. It was papis-zotero being deprecated then. I was on 0.03.
I didn't notice because I just installed it the other day with pip as proposed ( but they have not updated their database), so i tried yay
