### ISSUE TITLE
windows default tools

### ISSUE THREAD

**Issue by l-spiecker** [papis/papis#568]
* papis version0.13

# how to reproduce the issue
Command and output of `papis open`:
```
FileNotFoundError: [Errno 2] No such file or directory: 'start'
```

Is it really needed to always set the settings on windows to something like this, to have the default programs opening the files?

```
editor = explorer
file-browser = explorer
browser = explorer
opentool = explorer
```

**Comment by alexfikl** [comment]
Unfortunately, we're not very knowledgeable about Windows, so any help here is welcome!

My understanding is that the `start` command should be available on all versions of Windows
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start
What version of Windows are you using? Can you try it from `cmd.exe`? Maybe we're doing something weird when calling it..

Is `explorer` meant to do the same thing on newer versions of Windows?

**Comment by l-spiecker** [comment]
Ok, the default seems not to work on windows 11. It works without the double quotes here.

opentool = cmd.exe /c start "" # does not work on windows 11, but on windows 10
opentool = cmd.exe /c start # works on both
opentool = cmd.exe /c # works on both too

Same for editor, etc. (You change does not change the default editor, so a config is still needed here right?)

**Comment by alexfikl** [comment]
> opentool = cmd.exe /c start "" # does not work on windows 11, but on windows 10 
> opentool = cmd.exe /c start # works on both 
> opentool = cmd.exe /c # works on both too

Hm, I stole that default from NerdTree
https://github.com/preservim/nerdtree/blob/c46e12a886b4a6618a9e834c90f6245952567115/nerdtree_plugin/fs_menu.vim#L464

When you say that they work, do they actually open the desired file with the correct viewer? At least the last one feels a bit weird that it actually opens anything, but I don't know much about Windows :(

I'll go ahead and try the second one to see if that works too, so fingers crossed!

> Same for editor, etc. (You change does not change the default editor, so a config is still needed here right?)

The editor would use the `EDITOR` environment variable first. Does Windows set that in any way? Otherwise it should also change the default for the editor; this is the code for it:
```
"editor": os.environ.get("EDITOR")
          or os.environ.get("VISUAL")
          or get_default_opener()
```

**Comment by l-spiecker** [comment]
Hm, just tested the first command again and it worked in shell and also on the current papis version, but on this MR it fails when setting it in the config. I just debugged it and saw that the shlex.split creates the quotes as an argument instead of an empty argument. The following worked but it might not be very nice:

cmd = shlex.split(str(opener), posix=not is_windows) + [file_name]
cmd = [s.replace('""', '') for s in cmd]

I don't think, that windows has an editor or visual env set by default, so going for the default opener would be best.

**Comment by alexfikl** [comment]
> Hm, just tested the first command again and it worked in shell and also on the current papis version, but on this MR it fails when setting it in the config.

According to the docs
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start
that additional `""` should just "specify the title to display in the Command Prompt window title bar", which should not be necessary if this is used to launch an external program. Not sure though..

> I just debugged it and saw that the shlex.split creates the quotes as an argument instead of an empty argument. The following worked but it might not be very nice:
> 
> cmd = shlex.split(str(opener), posix=not is_windows) + [file_name] 
> cmd = [s.replace('""', '') for s in cmd]

If I understand correctly, your suggestion also just removes the `""` at the end of the command, so I went ahead and just did that in #569. Hopefully it now works on all versions!

Let me know if you get a chance to test it!

**Comment by alexfikl** [comment]
> Got the same error when calling `papis add` in msys2 on version 0.13. But with #569 everything works fine (with the default config).

Thanks a lot of checking that the PR works! I'll go ahead and merge it.
