### ISSUE TITLE
Wrong string escape in commit message.

### ISSUE THREAD

**Issue by Sebastian-Jung** [papis/papis#577]
* papis version (`$ papis --version` or commit number): `0c0beb2415cf6bf686b5d38903d3f7245587cef9`

# how to reproduce the issue
In my case, when adding a paper from `arxiv.org` and having auto-commit set to true (by using the `use-git` config option) I end up commiting the message 

```
git commit -m 'Add document: 'PAPER TITLE''
```

Since the Paper Title is in single quotes `'` and the String used for commiting aswell, the bash command fails.

I have only tested it in my setup and only for arxiv, but I assume this is a general issue.

**Comment by alexfikl** [comment]
Fixed by #578.

**Comment by AlexBocken** [comment]
Is a release planned soon? Currently the latest release does not include this fix which makes the git integration difficult to use (at least the auto-commting/mv etc.)

**Comment by alexfikl** [comment]
> Is a release planned soon? Currently the latest release does not include this fix which makes the git integration difficult to use (at least the auto-commting/mv etc.)

@AlexBocken Yeah, there are quite a few fixes that would be good to get out there. I think we're generally ready to push out a release, but I'm afraid there's no particular timeline for it. @alejandrogallo would just need to find some time to do it.
