### ISSUE TITLE
Cannot register alternative picker anymore (papis-tui)

### ISSUE THREAD

**Issue by supersambo** [papis/papis#581]
* papis version (`$ papis --version` or commit number): papis, version 0.13

# how to reproduce the issue
1. install papis-tui
2. set `picktool = papis-tui` in config file
3. run `papis open test`
Command and output of `papis --log INFO papis open test`:
```
[ERROR] pick: Invalid picker: 'papis-tui'. Registered pickers are 'fzf', 'papis'.
[WARNING] commands.open: No documents retrieved
```

I cannot use papis-tui as picker anymore. Is there anything that changed with how plugins are managed recently?

I must admit that I cannot fully rule out, this has to do with my local python installation. However, other entry points such as `papis.command` still work. For instance `papis tui` still works.

**Comment by alexfikl** [comment]
Hm, nothing should have changed for how plugins are loaded. I'm running the latest `main` and everything seems to be working correctly: uninstalled `papis-tui` and it complained, but when it's installed it works.

Have you changed something in your local installation? Can you try reinstalling? Maybe worth running `papis --log DEBUG open test` to see if something looks off..

**Comment by supersambo** [comment]
Thanks for the quick reply! Uninstalling and reinstalling unfortunately did not solve the issue. I'll invesitgate further then. 

`papis --log DEBUG open test` gives 
```
[DEBUG] database.cache: Querying database for 'test'.
[DEBUG] database.cache: Getting documents from cache at '/home/supersambo/.cache/papis/database/e73cbe59d686b7e71b32151fa69eb145-papis'.
[DEBUG] database.cache: Loaded 1805 documents.
[DEBUG] docmatcher: Parsing query: 'test'.
[DEBUG] docmatcher: Parsed query: '[['test']]'.
[DEBUG] database.cache: Filtering 1805 docs (search 'test').
[DEBUG] plugin: Creating manager for namespace 'papis.format'.
[DEBUG] format: Using 'python' formater.
[DEBUG] database.cache: Finished filtering in 28.37ms (51 docs).
[DEBUG] plugin: Creating manager for namespace 'papis.picker'.
[ERROR] pick: Invalid picker: 'papis-tui'. Registered pickers are 'fzf', 'papis'.
[WARNING] commands.open: No documents retrieved
```

Actually, this might have started when switching to python 3.11. So it seems to have something to do with it. I'll follow that route for now. .
