### ISSUE TITLE
syncing 

### ISSUE THREAD

**Issue by tjallemaal** [papis/papis#586]
I'd like use my database on multiple computers. 
If I choose a service like dropbox, what way to do so would be recommended?
Like, should I make use of `git` or should I just go with the default syncing capabilities of dropbox ... ?
Sorry, I'm kind of dumb with computers

**Comment by octaskin** [comment]
I guess this should be in Discussions not in Issues.
My suggestion is to read the docs a bit more before diving in, here is the [library structure section](https://papis.readthedocs.io/en/latest/library_structure.html). In short papis is a bib manager, how the files are synced is entirely up to you.

**Comment by tjallemaal** [comment]
I've never been aware of the `discussions` section ... oh my
