### ISSUE TITLE
Discussion platform (irc ? gitter ?, both?)

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#59]
I feel that it's time to define a place where we can discuss some
future directions and also talk to users, and maybe not always the issues
are the place to do it, what do you guys use/propose, we could just use a freenode
channel called #papis.

**Comment by nico202** [comment]
I like gitter, irc does not require the user to be registered, but you need to be 24/7 online to receive messages. Gitter + irc bridge would be the best option IMHO
