### ISSUE TITLE
Export multiple elements

### ISSUE THREAD

**Issue by nico202** [papis/papis#60]
right now it is possible to either export all elements (-a) or a single one (query)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
In principle if you combine both, query and `-a`, you also have the export of multiple . It would be useful to put that in the documentation I'm thinking ;)

**Comment by alejandrogallo** [comment]
Apparently we already wrote documentation for that, which is useful 
http://papis.readthedocs.io/en/latest/commands.html#module-papis.commands.export

Is this what you had in mind?

**Comment by nico202** [comment]
Ops, you are right, sorry
