### ISSUE TITLE
Why --set option does not overwrite the data imported from importer/downloaders when adding an entry?

### ISSUE THREAD

**Issue by Twix53791** [papis/papis#615]
I find strange than the field data we pass manually via --set when adding an entry does not overwrite the ones retrieved by the importer.
Just a very small hack in the code changes that :

```diff
    data = {}
-    for data_set in set_list:
-        data[data_set[0]] = data_set[1]

    ctx = papis.importer.Context()
    ctx.files = [f for f in files if os.path.exists(f)]
    ctx.data.update(data)


    imported = papis.utils.collect_importer_data(
        matching_importers, batch=batch, only_data=only_data)
    ctx.data.update(imported.data)
    ctx.files.extend(imported.files)

+    set_data = {}
+    for data_set in set_list:
+        set_data[data_set[0]] = data_set[1]
+    ctx.data.update(set_data)

    if not ctx:
```

I made a pull request...

**Comment by alexfikl** [comment]
Is this in batch mode? 

When not using batch mode, the data from multiple importers is added interactively and can be modified by the user. In that case, I think it makes sense to add the values from `--set` first and then update them as needed with data from importers.

In batch mode, I agree that it probably makes more sense to give precedence to user provided values. Maybe having a `if batch..` and `if not batch` for these two cases is best?

**Comment by Twix53791** [comment]
Ah, yes, I understand ! I did'nt g into this functionality of picking the data when adding the file. Too fastidious! So many lines were your eyes have to find their way to the unique interesting line! I don't really like the interface. It would be so much easier with a tool like fzf (maybe one day I will code this...), or even I prefer the option --edit to directly edit the yaml file.
Having the possibility of merging different data from different importers seems amazing, but I am afraid it will be even more a mess to figure out where the important informations are. By the way, when I set an alternative data with --set, I can't see it when I pass through the list of keys. 

Anyway, two philosophies I guess. Personnality, I am using now most of the commands in the background (I am opening a new issue about that righ now!). I don't need to pickup the data, I take all and later I modify if something is really annoying! I am building a "wrapper" for papis using fzf to navigate the database and execute actions on range of files.

SO, understanding the logic of both options, I propose rather just to add an option:

```diff

@click.option(
    "-s", "--set", "set_list",
    help="Set some information before",
    multiple=True,
    type=(str, str))
+@click.option(
+    "-S", "--set-after", "set_after_list",
+    help="Set some information after",
+    multiple=True,
+    type=(str, str))
@click.option(
    "-d", "--subfolder",

def cli(files: List[str],
        set_list: List[Tuple[str, str]],
+        set_after_list: List[Tuple[str, str]],
        subfolder: str,

    imported = papis.utils.collect_importer_data(
        matching_importers, batch=batch, only_data=only_data)
    ctx.data.update(imported.data)
    ctx.files.extend(imported.files)

+    if set_after_list:
+        set_after_data = {}
+        for data_set in set_after_list:
+            set_after_data[data_set[0]] = data_set[1]
+        ctx.data.update(set_after_data)

    if not ctx:
```
