### ISSUE TITLE
A full batch option for papis update ?

### ISSUE THREAD

**Issue by Twix53791** [papis/papis#617]
Pursuing on my way to automatize everything and running all the process in the background (to be fast!), I added the batch option to papis update. BUT, my goal is to use the amazing --auto option, retrieving many interesting data from sources. I want to run all this process in the background : I fact, I wrote a small script I use in qutebrowser to adding urls like the zotero firefox connector. It add the url with `papis add -b`, then I want to run `papis update -b --auto`. All this in the background : I am peacefully continuing to browse articles while papis take ten seconds to add this rich new entry.

Problem:
The batch avoid the last prompt, but not the kind of list menu poping when importer.crossref is asking me to pick up the citations I want to add (I want all !!!). I guess this menu is set in crossref.py, but I don't see straightaway the best way to pass to this script the -batch message telling to it to bypass this menu and just adding everythin to the database. I guess I would be nice to pass batch as argument like for `papis.utils.collect_importer_data` ? As I not very confortable with python, a litle help to identify the points on which, in the code, I have to focus... I will do the rest myself...
For now, sadly, my implementing of the batch option is pointless, as the interactive menu breaks my quiet 'background' ideal !

```diff
@click.option("-s", "--set", "set_tuples",
              help="Update document's information with key value. "
                   "The value can be a papis format.",
              multiple=True,
              type=(str, str),)
+@click.option(
+    "-b", "--batch",
+    help="Batch mode, do not prompt or otherwise",
+    default=False, is_flag=True)
def cli(query: str,
        git: bool,
        doc_folder: str,
        from_importer: List[Tuple[str, str]],
+        batch: bool,
        auto: bool,

        imported = papis.utils.collect_importer_data(
-            matching_importers, batch=False, only_data=True)
+            matching_importers, batch=batch, only_data=True)
        ctx.data.update(imported.data)

```

**Comment by alexfikl** [comment]
From the diff you included, it seems like that should correctly add a `batch` option to update. Can you make a PR with your work in progress? Not sure what could be missing without running it a bit :confused:

Overall, it would be nice to have these commands be able to run quietly in the background without user input (essentially what `--batch` wants to do). I'm not sure the importer and downloader selection and merging is smart enough to make that experience smooth, but it's a good step in that direction!

**Comment by Twix53791** [comment]
yep i did it

you don't have any clues to pass the batch options into the importers scripts? I am gonna look for a solution...

**Comment by alexfikl** [comment]
> you don't have any clues to pass the batch options into the importers scripts? I am gonna look for a solution...

I'm not sure what you mean here. What importer scripts?

**Comment by alexfikl** [comment]
> In crossref.py:
> 
> ```diff
> -    def fetch_data(self) -> None:
> +    def fetch_data(self, batch=False) -> None:
>         data = papis.crossref.get_data(dois=[self.uri])
> 
> -    def fetch_data(self) -> None:
> +   def fetch_data(self, batch=False) -> None:
>         self.logger.info("Querying Crossref with '%s'.", self.uri)
> 
>         if docs:
>  -           self.logger.info("Got %d matches, picking...", len(docs))
>  -           docs = list(papis.pick.pick_doc(docs))
> +            if not batch:
> +                self.logger.info("Got %d matches, picking...", len(docs))
> +                docs = list(papis.pick.pick_doc(docs))
> ```

I don't think I agree with this. It changes the interface for the importers, so all of them would need to be updated.

From what I can tell, the `pick_doc` in there is just a bug and should be removed. All other importers just indiscriminately pick out the first document if there are multiples, e.g. the BibTeX importer at
https://github.com/papis/papis/blob/99464a621f7e120b7d7f444a5bc42839f7ef04e7/papis/bibtex.py#L213-L216

How are you using the `crossref` importer in batch mode? Maybe you'd be better served by using the `doi` importer using `papis add --from doi 'some-doi'`? That should also give single unique document.

**Comment by Twix53791** [comment]
I think we can cloe this issue. --batch is useless in update, because we can use -a option and the 'bug' in crossref.py got corrected, so the pick_doc menu doesn't pop-up anymore
