### ISSUE TITLE
Disable Codacy Code Analysis

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#619]
Currently most PRs fail due to this (it seems to flag asserts in tests). I'm not sure it does anything useful that our `mypy`, `flake8` and the Github CodeQL checks don't already do, so I propose removing it.

@alejandrogallo @jghauser What do you think? (Does removing it just mean deleting the `.codacy.yml` file?)

**Comment by alejandrogallo** [comment]
I think so, yes, codacy is annoying, I can remove it

**Comment by alejandrogallo** [comment]
I also disabled the webhook! thank you for discussing!

**Comment by alexfikl** [comment]
Awesome! Thanks for disabling it :grin:
