### ISSUE TITLE
unable to open notes.tex

### ISSUE THREAD

**Issue by oaken-source** [papis/papis#62]
running `papis edit`, or pressing the `e` key in the gui results in the info.yaml file being opened, instead of the notes.tex file, which is the behavior described in the documentation.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @alejandrogallo, and @nico202.

**Comment by alejandrogallo** [comment]
Hi @oaken-source, 
I think you have to use the flag `-n` to open notes. 
```
papis edit -n
```
Let me know if this causes problems.
Also, can you tell me where did you read that the default behaviour should be opening notes?
Thanks!

**Comment by oaken-source** [comment]
it seems I didn't read into the manpage far enough :)

under the `notes-file` setting, there is the text:

> In papis edit you can edit notes about the document. notes-name is the default name of the notes file, which by default is supposed to be a TeX file.

but further down the `-n` switch is introduced, as you say, so I could have caught that.

Is there a way to open the notes from the papis gui though?

**Comment by oaken-source** [comment]
it's all good, I added the '-n' switch to the edit calls in main.vim. that fixes the issue, as far as I am concerned :)
