### ISSUE TITLE
Why --doc-folder doesn't handle multiples folders?

### ISSUE THREAD

**Issue by Twix53791** [papis/papis#627]
I need to update several entries in once. Problem : I have to execute `papis update --doc-folder` multiple times, for each entry. It is VERY slow (0.5 second for each entry, 5sec for 10 entries...).

So, I changed cli.py to allows --doc-folder to accept a large string containing many folders. Then parse this large string to get a list of folders. I made a pull request.

The current solution is not the best:
1) doc-folder doesn't check anymore if the folders are valid
2) cli.py now import re (regex needed to split the string and build a list of folders)

It would be more elegant to allow --doc-folder to accept multiples arguments. I almost achieved that, but I have to pass a `nargs` value setting the number of arguments and I don't understand how to set it to an undefined number... 

Anyway, my fix works : `papis update --doc-folder "folder1 folder2 folder3"` will update the three folders in about 0.5 sec (there is now almost no difference in the speed of updating one or more folders).

```diff
import click
+import re

import papis.config
import papis.pick

@@ -56,7 +57,6 @@ def doc_folder_option(**attrs: Any) -> DecoratorCallable:
    return click.option(
        "--doc-folder",
        default=None,
-        type=click.Path(exists=True),
        help="Document folder on which to apply action",
        **attrs)

@@ -95,7 +95,9 @@ def handle_doc_folder_or_query(
        :func:`papis.document.from_folder`).
    """
    if doc_folder:
-        return [papis.document.from_folder(doc_folder)]
+       folders = [x.strip('\'"') for x in re.findall(r'\'.*?\'|".*?"|\S+', doc_folder)]
+       doc_folders = [papis.document.from_folder(f) for f in folders]
+       return doc_folders
    return papis.database.get().query(query)
```

**Comment by alexfikl** [comment]
What use case do you have that requires adding multiple documents using `--doc-folder`? 

If you're importing/migrating or moving documents around, maybe it's better to write a little script for yourself. You can see a wonderful example of this in https://github.com/papis/papis/issues/591#issuecomment-1633870907.

You can also check out the developer documentation: https://papis.readthedocs.io/en/latest/api.html

**Comment by Twix53791** [comment]
Its a question of design philosophy I guess. Some of your design choices are really good, for example the way of adding options or to parse config file ; really easy to understand and hack. Fast, simple. Personnaly, my philosophy in coding is to  favor rapidity and reliability. Fast and simple, but also hackable. Allows all the commands taking at least one arguments to process multiple arguments is about rapidity and hackability. I think personally than in every program, the commands should accept multiple arguments if possible. It allows users to have more versatility about their uses of the program, especially for "large scale uses" of a program (when you need to automatize things, seek for optimization and so on).

Actually, I am coding a fzf wrapper for papis [https://github.com/Twix53791/fzf-papis](url). It displays all the papis library entries in a fzf menu, and from there, I can execute 'commands' (edit the selected entries, browse the selected entries, cite, export, delete, tag, etc.). It is design to execute actions on multiples entries. For example delete multiples entries at once, or tag multiple entries with some tags, or browse multiple entries, etc. When I can, I avoid using papis commands, because bash is faster. But I use some papis commands : `papis rm`, `papis update` (essential to update the whoosh database), `papis browse`, `papis export`. I use these commands with `--doc-folder` because I is more reliable than use a pattern to search (why use a pattern? I know precisely which files I want to modify, from the fzf menu list). So, if I delete 10 entries at once, I don't want to run ten times `papis rm --doc-folder`, it is slow! Even worse to update entries. For example, I tag at once 50 files (I create a new category and add all my references about this topic), a bash script just writes the tag in the 50 info.yaml files, then, I have to update the whoosh database : I use `papis update --doc-folder`. Each papis run take at least 0.5 seconds (time to init papis). So it gonna takes 25 seconds?! Allowing --doc-folder to deal with multiples papis-folders reduce the time to less than 1 second... VERY good optimization in my mind...

**Comment by alejandrogallo** [comment]
I think this was a good idea, but as I see this is already in master, right? so we can  close this issue?

**Comment by alexfikl** [comment]
Yeah, it's already fixed and merged!
