### ISSUE TITLE
papis update picker multi-select

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#692]
* papis version (`$ papis --version` or commit number): 0.13

# Brief Workflow Description
I start writing a new paper and I want to begin assembling some references that I think will be relevant. Currently, my preferred method for doing this is to begin adding some new label associated with this new paper to the `project` field in the `info.yaml` file for each reference I want to associate with the project. Then, when I need the BiBTeX file I run something like `papis export --all project:"myNewPaper" > myNewPaper.bib`. It is very tedious to run `papis edit`, browse, find a relevant reference, manually add the label to the `project` field of the yaml file, rinse and repeat.

# What I (Think I) Want
The `papis update` command looks like what I want as it allows `set`ting fields of multiple documents' `info.yaml` files by using the `--all` flag. However, it seems the only way to get it to work for multiple documents is to use a query, e.g. (from the docs),

```
papis update --all --set tags '{doc[tags]} physics' einstein
```

I presume that if one runs without a query then the picker appears and the update command is run on the (one and only) document selected from the picker.

I think what I want is to run `papis update --all --set project '{doc[project]} myNewPaper'`, have the picker appear, and then proceed to peruse/browse, and 'mark' (i.e., select) multiple documents before the picker is closed. Is multi-select something reasonable to incorporate into the picker, in general, or should I re-think how I work?

**Comment by alexfikl** [comment]
The default picker should allow selecting multiple entries using `<Control-t>`. Can you try and see if that works for you?

There are also some settings to control this, e.g. (could definitely use more documentation from the looks of it!)
https://papis.readthedocs.io/en/latest/configuration.html#config-tui-mark_key

**Comment by avonmoll** [comment]
I did not know about that! That solves it for me (mostly). The problem that remains is when the field I want to update is a list. However, I see that there is a PR (#681) that would exactly address that. I will close this issue and wait for that PR to be integrated. Thank you!
