### ISSUE TITLE
use-git = False not respected

### ISSUE THREAD

**Issue by hseg** [papis/papis#698]
* papis version (`$ papis --version` or commit number): 0.13

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
[INFO] commands.add: Constructing an automatic (hashed) folder name.
[INFO] commands.add: Document folder is '/home/gesh/thesis-papers/trace-moments/418449a6ffc7aed8e811edc93470ca1d'.
[INFO] commands.add: Checking if this document is already in the library. This uses the keys ['doi', 'ref', 'isbn', 'isbn10', 'url', 'doc_url'] to determine uniqueness.
[INFO] commands.add: No document matching the new metadata found in the 'trace-moments' library.
[INFO] commands.add: [MV] '/tmp/tmpob91u6tq' to '/home/gesh/thesis-papers/trace-moments/418449a6ffc7aed8e811edc93470ca1d'.
[INFO] git: Adding '/home/gesh/thesis-papers/trace-moments/418449a6ffc7aed8e811edc93470ca1d'.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[INFO] git: Committing '/home/gesh/thesis-papers/trace-moments/418449a6ffc7aed8e811edc93470ca1d' with message 'Add document ' - ''.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Below is `papis/config` -- note even specifying `use-git = False` both globally and for the specific library fails
```
[settings]
default-library = trace-moments
opentool = xdg-open
editor = vim
use-git = False
notes-name = notes.md
database-backend = papis
bibtex-unicode = False
ref-format = {doc[title]:.15} {doc[author]:.6} {doc[year]}
multiple-authors-format = {au[family]}, {au[given]}
citations-file-name = citations.yaml

[trace-moments]
dir = /home/gesh/thesis-papers/trace-moments
opentool = xdg-open
editor = vim
use-git = False
notes-name = notes.md
database-backend = papis
bibtex-unicode = False
ref-format = {doc[title]:.15} {doc[author]:.6} {doc[year]}
multiple-authors-format = {au[family]}, {au[given]}
citations-file-name = citations.yaml
```

Moreover -- something that is not clear from the docs is that the git integration doesn't create its own repository at the library root -- hence if one places the library under an existing git repo, the papis history and the existing git repo history will be entangled (which while it makes sense in hindsight, was surprising when I noticed it)

**Comment by alexfikl** [comment]
Can you check if #700 fixes it for you?

As for the documentation, I agree that it could be clearer about what the `git` integration actually does. Would you be willing to make a PR adding a few sentences for that where you think is appropriate?

**Comment by hseg** [comment]
Ah, I uninstalled papis yesterday in a fit of frustration. Am a bit busy in the coming month, and the dependencies are sufficiently annoyingly packaged that I can't test right now. Will try to remember to check in again in early December.

**Comment by alexfikl** [comment]
Sorry it didn't work out for you, but thank you very much for taking the time to file all the issues!

I'll go ahead and merge #700 then, but feel free to re-open this issue (or make a new one) if you get the chance to test it out again.

**Comment by alexfikl** [comment]
I updated the git docs too in #706. It now mentions that a git repository must be created by the user in a big warning, so hopefully it will be clear to newcomers! You can see the updated page at
https://papis.readthedocs.io/en/latest/git.html

**Comment by hseg** [comment]
Looks great, thanks!
