### ISSUE TITLE
[Documentation]: Mention formatter syntax at the top of configuration doc

### ISSUE THREAD

**Issue by hseg** [papis/papis#704]
* papis version (`$ papis --version` or commit number): 0.13

It is unclear until one reaches the end of `configuration.html` that some configuration settings subsequently undergo expansion using a formatter. It would be helpful to mention this at the top.
(Incidentally, why did we accept the bootstrap problem that is specifying the formatter to be used _inside_ the config file? Especially given we support `config.py`, there seem to be better ways of doing this, eg by having a default formatter that can be overridden with a value set in `config.py`)

**Comment by alexfikl** [comment]
Added a little warning to tell users about the formatter in the configuration docs. It now looks like this:

![Screenshot_20231115_105108](https://github.com/papis/papis/assets/777240/b6331f80-dcce-4937-9ec0-81c15ffb9649)

What do you think? We could probably use some more examples of how the formatters work, but that's for another time.

> (Incidentally, why did we accept the bootstrap problem that is specifying the formatter to be used inside the config file? Especially given we support config.py, there seem to be better ways of doing this, eg by having a default formatter that can be overridden with a value set in config.py)

I'm not quite sure what you mean that there's a bootstrap problem with the formatter? I don't even use `config.py` and it seems to work just fine. The only issue we seem to hit with it is related to #662.

**Comment by hseg** [comment]
> What do you think? We could probably use some more examples of how the formatters work, but that's for another time.

LGTM!
> > (Incidentally, why did we accept the bootstrap problem that is specifying the formatter to be used inside the config file? Especially given we support config.py, there seem to be better ways of doing this, eg by having a default formatter that can be overridden with a value set in config.py)
> 
> I'm not quite sure what you mean that there's a bootstrap problem with the formatter? I don't even use `config.py` and it seems to work just fine. The only issue we seem to hit with it is related to #662.

Rereading my comment, I apparently had misconstrued at which point formatting was coming in. I was under the mistaken impression that formatting occurs _while reading the config file_, which is obviously incorrect and insensible.
The point still stands, though severely weakened -- why did we even bother providing flexibility in formatter choice?
And the suggestion of an alternative could be salvaged as -- given that we did decide to bother, why not make it into a plugin?

**Comment by alexfikl** [comment]
> Rereading my comment, I apparently had misconstrued at which point formatting was coming in. I was under the mistaken impression that formatting occurs _while reading the config file_, which is obviously incorrect and insensible.

Yeah, the formatter is called when we try to display a string to the user (e.g. `papis list --format {doc[author]}`) or the user gives a formatted string to add to a document (e.g. setting `ref` from some `{doc[doi]}`). Both of these are after the configuration is loaded, so it should be fine on that end.
 
> The point still stands, though severely weakened -- why did we even bother providing flexibility in formatter choice? And the suggestion of an alternative could be salvaged as -- given that we did decide to bother, why not make it into a plugin?

The formatter is already a plugin? We have two official implementations that use the standard `str.format` and `jinja2` templating. There's a bit of documentation here (but overall needs more work too)
https://papis.readthedocs.io/en/latest/developer_reference.html#module-papis.format
It's probably not very popular, but people have implemented some custom versions too
https://github.com/hrdl-github/papis/blob/49b9c17e9b2e70b24529d818e17434e9b354d957/papis/format.py#L88

Is this what you meant?

**Comment by hseg** [comment]
On Sun, Nov 19, 2023 at 12:28:45AM -0800, Alex Fikl wrote:
> > The point still stands, though severely weakened -- why did we even bother providing flexibility in formatter choice? And the suggestion of an alternative could be salvaged as -- given that we did decide to bother, why not make it into a plugin?
> 
> The formatter is already a plugin? We have two official implementations that use the standard `str.format` and `jinja2` templating. There's a bit of documentation here (but overall needs more work too)
> https://papis.readthedocs.io/en/latest/developer_reference.html#module-papis.format
> It's probably not very popular, but people have implemented some custom versions too
> https://github.com/hrdl-github/papis/blob/49b9c17e9b2e70b24529d818e17434e9b354d957/papis/format.py#L88
> 
> Is this what you meant?

This is _precisely_ what I meant -- it wasn't reflected in
https://papis.readthedocs.io/en/latest/plugins.html, so I had absolutely no idea
that this was already a feature (though I should've realized this from browsing
through #662).
