### ISSUE TITLE
readthedocs.org is not updating

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#708]
After merging #707, I noticed that the online docs are not updating?
https://readthedocs.org/projects/papis/builds/

@alejandrogallo I'm not sure what could be wrong, but a guess could be this recent change
https://blog.readthedocs.com/security-update-on-incoming-webhooks/
Do we have something like that set up to use readthedocs? I haven't had to change that for another project, so I'm not convinced that's the issue, but I don't have other ideas..

**Comment by f0rki** [comment]
There is also a problem with the asciicinema recording here: https://papis.readthedocs.io/en/latest/commands/list.html
not sure, but maybe related to this?

**Comment by alexfikl** [comment]
> There is also a problem with the asciicinema recording here: [papis.readthedocs.io/en/latest/commands/list.html](https://papis.readthedocs.io/en/latest/commands/list.html) not sure, but maybe related to this?

Hm, not sure, but we should definitely transition those to using [vhs](https://github.com/charmbracelet/vhs) like the README. It's a lot nicer :heart:

**Comment by alejandrogallo** [comment]
![09-02-24_19:34:19](https://github.com/papis/papis/assets/12715358/3709c33e-8a21-4778-9026-61e851b0b139)
I think I solved the readthedocs issue, it should work from now on, again 
I'm sorry this took so long...

**Comment by alexfikl** [comment]
That's awesome! What was the problem in the end?

**Comment by alejandrogallo** [comment]
they included secrets on readthedocs and I had to paste them also in the github integration, it took me a while but ok in the end it was trivial, it seems to work

https://papis.readthedocs.io/en/latest/configuration.html#serve-web-app-options

**Comment by alexfikl** [comment]
Thanks again for taking care of it!
