### ISSUE TITLE
Add bibtex-journal-key option

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#73]
## Problem
Currently, `papis export --all --bibtex` shows the full journal title in the `journal` key. When writing articles, some publishers prefer journal abbreviations in the bibliography.

## Solution
There should be a config option `bibtex-journal-key`, and, possibly, a command line option, to export bibtex with the journal key defined by the user, allowing bibtex files to be made with the journal as either `full_journal_title` or `abbrev_journal_title`. Default should just be `journal` seeing as it will need to be backwards compatible with entries not containing the new fields. 

I can take care of this

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/10 (Additional bibtex keys), https://github.com/alejandrogallo/papis/issues/35 (Add unicode to latex support for bibtex export), https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn), https://github.com/alejandrogallo/papis/issues/39 (file-name option and adding files with incomplete metadata), and https://github.com/alejandrogallo/papis/issues/38 (Multiple authors in bibtex).
