### ISSUE TITLE
Fallback method may results in incompatible bibtex export

### ISSUE THREAD

**Issue by apraga** [papis/papis#731]
* papis version 0.13 (Gentoo)

# how to reproduce the issue

Some papers are identified as OriginalPaper but bibtex does not know this format. Example with this paper : https://www.nature.com/articles/s41592-018-0054-7

```
papis --log INFO export -o bisonex.bib synthetic

[ERROR] bibtex: BibTeX type 'OriginalPaper' not valid in document: '/home/alex/papers/li-a-synthetic-diploid-benchmark-for-accurate-variant-calling-evaluation/info.yaml'.
[WARNING] bibtex: Skipping document export: '/home/alex/papers/li-a-synthetic-diploid-benchmark-for-accurate-variant-calling-evaluation/info.yaml'.
```

Would it be possible to replace OriginalPaper to article in the bibtex export ? Thanks

**Comment by alexfikl** [comment]
It would probably be better to fix that in the importer / downloader, so that documents like that don't get into the library to begin with. What did you use to add that document?

If that's not possible, it should be very simple to add it to the `bibtex_type_converter` list here
https://github.com/papis/papis/blob/a7c26761b2cb2a097b5c7175d0b920464b92ebf3/papis/bibtex.py#L229

**Comment by alexfikl** [comment]
By the way, there's a [papis doctor](https://papis.readthedocs.io/en/latest/commands/doctor.html) command that could help with finding all documents with weird types like that. You can run it with
```
papis doctor --explain --check bibtex-type <QUERY>
```
to see all the broken documents. Unfortunately it can't automatically fix them in papis 0.13, but #732 adds that, so hopefully in the next release it will be nicer to use.

**Comment by apraga** [comment]
This doctor command helps to find such mistake, thanks. 
I used the fallback method which marked it as OriginalPaper. Using the DOI does not have this issue. Actually, DOI is a much safe bet as I've had issues with the year not added from the fallback method.

**Comment by alexfikl** [comment]
> I used the fallback method which marked it as OriginalPaper. Using the DOI does not have this issue. Actually, DOI is a much safe bet as I've had issues with the year not added from the fallback method.

Yeah, I also usually use `--from doi <DOI>` or `--from arxiv <ARXIV>` because they give good results. The fallback method just scrapes the web page, so it's going to be a lot less accurate in general..

**Comment by alexfikl** [comment]
#735 should fix this for the fallback method and in the BibTeX exporter! Thank you very much for the report!
