### ISSUE TITLE
papis zotero does not honour --pick-lib or -l my_lib

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#75]
## Problem

`papis --pick-lib zotero my_bib.bib` or `papis -l my_lib zotero my_bib.bib` currently does not honour the library options and will add the contents of the bib file to the default library defined in the config file.

## Solution

Add `-l papis.api.get_lib()` option to `examples/scripts/papis-zotero`

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/64 (Rofi GUI doesn't honour 'editor' option in .config/papis/config), https://github.com/papis/papis/issues/66 (Why does papis browse not default to using the doi?), and https://github.com/alejandrogallo/papis/issues/41 (Webapplication for papis).
