### ISSUE TITLE
Tests: Don't fail when whoosh isn't installed

### ISSUE THREAD

**Issue by hseg** [papis/papis#750]
* papis version (`$ papis --version` or commit number):
5a0799c910f97b2692195b15c382f2f956d25e49

# how to reproduce the issue
On a system without whoosh installed:
```
cd "$(mktemp -d)"
git clone https://github.com/papis/papis.git
cd papis/
python setup.py build
python -m pytest papis tests
```
Error log: 
[error.log](https://github.com/papis/papis/files/14283511/error.log)

**Comment by hseg** [comment]
Problem found: `test_cache_path` is missing an `importorskip("whoosh")`

**Comment by alexfikl** [comment]
That sounds right to me! Want to make a pull request?

**Comment by hseg** [comment]
Oops, thought I had opened it
