### ISSUE TITLE
test failing when using jinja2 formatter

### ISSUE THREAD

**Issue by joelsleeba** [papis/papis#757]
https://github.com/papis/papis/blob/84a90d19b17d26616a8e78b31a8b396869b0d1ba/papis/database/cache.py#L103C1-L104C10

This is the exact line that is failing. I am using jinja2 formatter. I also noticed this format works fine with my configuration

```
>>> match_document(document, regex('e in'), '{{ doc.author }}') is None
False
```

**Comment by joelsleeba** [comment]
It is possible that this is a configuration error. Scraping the config passed the tests.

**Comment by alexfikl** [comment]
It's likely not a configuration error. The issue is that the doctests (in the `papis` folder) are run with the global config, while the unit tests (in the `tests` folder) are run with empty temporary configs.

We should make the doctests use a new config too, but haven't gotten around to it yet..
