### ISSUE TITLE
papis not preserving case for subfolder name?

### ISSUE THREAD

**Issue by JetpackJackson** [papis/papis#774]
* papis version (`$ papis --version` or commit number): papis, version 0.13

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
[I] jet@sharky~ $ papis --log INFO add https://wiki.archlinux.org/ --folder-name 4B
[INFO] utils: papis.downloaders.fallback.Downloader (fallback) fetched data for query 'https://wiki.archlinux.org/'!
[INFO] commands.add: These importers where automatically matched. Select the ones you want to use.
0. fallback (files: ) 
Select matching importers (for instance 0, 1, 3-10, a, all...) (): 0
[INFO] utils: Merging data from importer 'fallback'.
- title: 
+ title: None
?        ++++
- url: 
+ url: https://wiki.archlinux.org/
^^^^^^^^^
diff from
-----  - 
+++++ Downloader(fallback, uri=https://wiki.archlinux.org/)

Add all[a] Split[s] Reject[n] Quit[q] Cancel[c]                                         
--- Diff view: all changes ---
[INFO] commands.add: Created reference 'None'.
[INFO] commands.add: Document folder is '/home/jet/docs/notes/papers/4b'.
[INFO] commands.add: Checking if this document is already in the library. This uses the keys ['doi', 'ref', 'isbn', 'isbn10', 'url', 'doc_url'] to determine uniqueness.
[INFO] commands.add: No document matching the new metadata found in the 'papers' library.
[INFO] commands.add: [MV] '/tmp/tmp_8aim_j9' to '/home/jet/docs/notes/papers/4b'
```
Result: paper was placed in papers/4b, leaving papers/4B (the dir I made for the document) empty
Expected result: papis would add the document into the papers/4B dir and not create any other dirs.

**Comment by alexfikl** [comment]
This is likely related to #311.

**Comment by JetpackJackson** [comment]
Alright. I see some work has been done regarding that, and I have some free time today, so I'll test if the issue persists and close it if needed.

**Comment by JetpackJackson** [comment]
Looks like it's still happening, I got the same result as last time. What else should I do to help debug/fix it?

**Comment by alexfikl** [comment]
> Looks like it's still happening, I got the same result as last time. What else should I do to help debug/fix it?

Did you set `doc-paths-lowercase = false` in your config? That should keep it from lowercasing.

**Comment by JetpackJackson** [comment]
I did not, I'll try that! Thanks!

**Comment by JetpackJackson** [comment]
I put that in my [settings] block but it's not working:
```
[papers]
dir = ~/docs/notes/school/papers

[4B]
dir = ~/docs/notes/school/4B

[settings]
default-library = papers
doc-paths-lowercase = false
```
is this the correct format?

**Comment by JetpackJackson** [comment]
`papis config doc-paths-lowercase` outputs `false`
I made a debug library with a folder "DEBUG", and when I kept the folder name option, it did "../DEBUG/4b" but when I tried a different site and without the --folder-name, it put it in "../DEBUG". So I'm guessing it has something to do with that option specifically.

With folder name option:
`[INFO] commands.add: [MV] '/tmp/tmp0d2mcx68' to '/home/jet/docs/notes/school/DEBUG/4b'.`

Without:
`[INFO] commands.add: Document folder is '/home/jet/docs/notes/school/DEBUG/219c6fec691365e668161f31884a3b84'.`

New stuff in config:
```
[debug]
dir = ~/docs/notes/school/DEBUG
```

**Comment by JetpackJackson** [comment]
Note: I'm currently running this on the nixpkgs version of papis, because the `papis-git` package on Arch is taking forever to build, but once it builds I can test with that one too. In my original post I believe I was using the `papis` package from the AUR, but it appears to be orphaned.

**Comment by jghauser** [comment]
> There's a nix flake in the repository too, if you prefer to use that. I believe it builds the git version, but I'm not a nix user.

Yes, it does

**Comment by kiike** [comment]
> There's a nix flake in the repository too, if you prefer to use that. I believe it builds the git version, but I'm not a nix user.

It does :smile:

**Comment by jghauser** [comment]
haha, nice timing @kiike :laughing:

**Comment by kiike** [comment]
> haha, nice timing @kiike 😆

We felt summoned and compelled to reply, @jghauser!

**Comment by JetpackJackson** [comment]
> There's a nix flake in the repository too, if you prefer to use that. I believe it builds the git version, but I'm not a nix user.

Alright cool! I'll try that out then!

**Comment by kiike** [comment]
> is 0.13 the git version? or did I build it incorrectly? I also tested the nixpkgs one again with the same command and it gave me `[INFO] commands.add: [MV] '/tmp/tmpyglhp2j3' to '/home/jet/docs/notes/school/DEBUG/4b'.` But it's also version 0.13.

Re the version you are getting with `papis --version`, if it says 0.13 it's expected, as that's the version declared in the package metadata (`pyproject.toml`), so you can more accurately know what git commit you are running from if you get info about the link in `./result/bin/papis`, like with

```bash
ls -l ./result/bin/papis
```

On my machine it gives `../../../../nix/store/0i89hqjbmzgd9bagsjwx9hicm0043cah-python3.11-papis-a8f927a/bin/papis`. So my `papis` binary is built from revision **a8f927a**.

Re your issue, I have copied your config and your directory structure, but trying downloading a PDF from arXiv instead of the arch wiki.

```
cat ~/.config/papis/config.debug774
[papers]
dir = ~/docs/notes/school/papers

[4B]
dir = ~/docs/notes/school/4B

[settings]
default-library = papers
doc-paths-lowercase = false
```
Run with the option set to true, downloading to the library 4B
```
./result/bin/papis -c ~/.config/papis/config.debug774 -l 4B --log INFO --set doc-paths-lowercase true add https://arxiv.org/abs/2404.13111
[INFO] downloader.arxiv: Downloading file from 'http://arxiv.org/pdf/2404.13111v1'.
[...]
[INFO] commands.add: [MV] '/tmp/nix-shell.0995uF/tmpvoz0mg55' to '/home/kiike/docs/notes/school/4B/0aaa9b4b66f41a7d8da9ce184b4747b5-kushnir-doron-and-k'.
```
That option set to false, downloading to library 4B

```
./result/bin/papis -c ~/.config/papis/config.debug774 -l 4B --log INFO --set doc-paths-lowercase false add https://arxiv.org/abs/2404.13115
[INFO] downloader.arxiv: Downloading file from 'http://arxiv.org/pdf/2404.13115v1'.
[...]
[INFO] commands.add: [MV] '/tmp/nix-shell.0995uF/tmpceh_fpwj' to '/home/kiike/docs/notes/school/4B/9cea0cf721df931c44c923b8a189194c-Dursun-Deniz-Cennet'.
```
As for `--folder-name`: I put in `--folder-name` gets converted to lowercase, which is something I would personally expect. If you want to separate with subfolders, maybe try `--subfolder`:

```
./result/bin/papis -c ~/.config/papis/config.debug774 --log INFO --set doc-paths-lowercase true add --subfolder FOOBAR https://arxiv.org/abs/2404.13109
[...]
[INFO] commands.add: [MV] '/tmp/nix-shell.0995uF/tmp70lspfyx' to '/home/kiike/docs/notes/school/FOOBAR/0d5893c61a5d53579f41071fd18ea46f-d-agnolo-raffaele-t'.
```
Note the subfolder has not been turned to lowercase, while the document folder is all in lowercase. Is this what you want?

**Comment by JetpackJackson** [comment]
Yes, that's perfect! Thank you so much! Using the subfolders works perfectly for my usecase. And my papis binary is also built from `a8f927a` (it has the exact same store path and everything).

**Comment by JetpackJackson** [comment]
I also just figured out that the export command works great with subfolders too which is also great for my usecase (`papis export ARXIV` will export docs from the ARXIV subfolder even if there are other subfolders with documents from arxiv!) Should I close this issue as completed then?

**Comment by alexfikl** [comment]
> Should I close this issue as completed then?

If there's no other related problem with the lowercasing, sure, go ahead and close it!

Thanks for trying things out and thank you to @kiike for explaining the usage properly! :heart:

**Comment by JetpackJackson** [comment]
Thank you all again so much for your help!!

**Comment by kiike** [comment]
Glad i could be of help! Cheers!
