### ISSUE TITLE
Do our own journal abbreviations?

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#78]
Hi @alejandrogallo, 

This one is more of a question/idea. I've noticed that some of the journal abbreviations picked up from crossref are incorrect sometime. e.g.

```bash
papis add --from-doi '10.1038/ncomms11683'
```

results in `abbrev_journal_title: Nat Comms` which should be `Nat. Commun.`

I think Zotero and other citation software calculates their own abbreviations. I wondered whether this is a direction you think papis should go in?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/73 (Add bibtex-journal-key option).

**Comment by alejandrogallo** [comment]
Hi Michael,

I think this could be done via a python papis script, that you can run
periodically or whenever you want. Instead of cluttering the already
cluttered crossref  code. What do you think ?

Thank you very much !

**Comment by michaelplews** [comment]
I like that idea. I think then it could be easily edited by users for other languages without needing to dive directly into the code.  

PR incoming
