### ISSUE TITLE
`config.py` gets loaded when running `pytest`

### ISSUE THREAD

**Issue by jghauser** [papis/papis#784]
As discussed in #783, when we run `pytest`, the monkeypatching doesn't get rid of options set by the user in a `config.py` (because they are `eval`-ed into the global scope). This means that whatever options are set there may cause the tests to fail.

**Comment by alexfikl** [comment]
Might be able to fix this by using a session scoped fixture to point `XDG_CONFIG_HOME` to `/tmp` before pytest starts importing our modules.

https://docs.pytest.org/en/6.2.x/fixture.html

**Comment by jghauser** [comment]
Excellent, that does look like it should do the trick. Thanks for having a look!
