### ISSUE TITLE
README: Inexistent maintainer for papis-zotero

### ISSUE THREAD

**Issue by kiike** [papis/papis#824]
I just noticed that the README [lists a maintainer for papis-zotero](https://github.com/papis/papis/blob/4bd6ca5d6011eb612b54efa19f10d13956a380b8/README.rst?plain=1#L156) who [no longer is on Github](https://github.com/lennonhill).

**Comment by alexfikl** [comment]
Stab in the dark, but.. @hrdl-github Is that you? Are you still at all interested in maintaining `papis-zotero`?

**Comment by alexfikl** [comment]
> Yes, that's me. I've stopped using papis in favour of zotero 7 + better bibtex to reduce the mental overhead. I'd be happy to review the submitted nix flake, but ideally you'd find another maintainer soon.

That's no problem at all! You don't need to review anything, we're just going to update the README so that it's up to date.
