### ISSUE TITLE
[hubation] Implement immediate reference redirecting  

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#84]
## Problem
Right now, If I use the `hubation` script to search the references, I have to go to the references section of the journal, look up the bibliographic information, run `papis hubation`, and then search the results for the bibliographic information.

## Solution
I've noticed that the references caught by `hubation` are usually in order of how they appear in the paper. It might be useful to add an additional argument e.g. `papis hubation ref='Plews2019' 28` where 28 is the inline reference. Papis could then download information for all the references, stopping when it got to 28 and then returning the result.

I can work on this.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.
