### ISSUE TITLE
(bindist) Wheel should only include user-needed files

### ISSUE THREAD

**Issue by hseg** [papis/papis#848]
* papis version (`$ papis --version` or commit number): HEAD (b6fe8962)

Currently, building a bindist as recommended, i.e.
```bash
python -m build --wheel --no-isolation
python -m installer --destdir=tmp_man_install dist/*.whl

local site_packages=$(python -c 'import site; print(site.getsitepackages()[0])')
export PYTHONPATH="$(pwd)/tmp_man_install/${site_packages}:${PYTHONPATH}"
make -C doc man

python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
```
has the unfortunate consequence of also packaging `papis/sphinx_ext.py` and
`papis/testing.py`, confusing automated dependency-checking tooling like
[`namcap`](https://gitlab.archlinux.org/pacman/namcap) (specifically, it makes
it think `sphinx`, `docutils`, and `pytest` are runtime dependencies of `papis`).

AFAICT, these are only needed for build/dev time, correct?
So there is no reason they should be in a bindist wheel.

**Comment by alexfikl** [comment]
Those files are included because they should be used by plugins to simplify testing and documentation. For example, after the next release, we'll probably make `papis-zotero` use that to remove a bunch of code that was copied over.

For `namcap`, could that be solved with `optdepends`?

**Comment by alexfikl** [comment]
For comparison, `click` also has similar helpers and they're packaged separately as `pytest-click` and `sphinx-click`. Maybe we can think about separating them, but I'm not sure that's worth it right now..

**Comment by hseg** [comment]
So checking the use sites, it seems `namcap`'s logic is too weak to be silenced
-- it eg doesn't check for `try: import .. catch ImportError` blocks -- so I'll
just need to ignore its warnings.

Just to confirm, then -- the only direct dependency in terms of build
environment is on `sphinx-click`, but the package should advertise optional
dependencies on `docutils`, `sphinx`, `sphinx-click` and `pytest` in case
plugins make use of `papis.{sphinx_ext,testing}`?

**Comment by alexfikl** [comment]
> Just to confirm, then -- the only direct dependency in terms of build environment is on `sphinx-click`, but the package should advertise optional dependencies on `docutils`, `sphinx`, `sphinx-click` and `pytest` in case plugins make use of `papis.{sphinx_ext,testing}`?

Yeah, that sounds right. And you only need `sphinx-click` if you want to build the docs or man pages.

**Comment by hseg** [comment]
Right, that's what I meant by "direct dependency in terms of build environment" - a packager-side dependency.

**Comment by alexfikl** [comment]
@hseg Did you have any additional questions? Can this be closed?

**Comment by hseg** [comment]
Don't think so. I'll open a fresh issue if needed.

**Comment by alexfikl** [comment]
Sounds good!
