### ISSUE TITLE
python-papis.scm Guix recipe fails to build

### ISSUE THREAD

**Issue by JetpackJackson** [papis/papis#857]
* papis version (`$ papis --version` or commit number): 0.13

# how to reproduce the issue
1. download https://papis.readthedocs.io/en/latest/_downloads/092dec70a64af479ea312a1a75fa68d4/python-papis.scm from the latest version of the documentation
2. run `guix package --install-from-file=python-papis.scm --substitute-urls=https://ci.guix.gnu.org` (the other substitute server is being wonky right now, but the command in the manual is what i would normally use)
3. wait for downloads and builds and see that the build fails
Command and output of `papis --log INFO <command>`: N/A

Logfile from Guix:
[papis-logfile.txt](https://github.com/papis/papis/files/15381898/papis-logfile.txt)

I'm just beginning to tinker with Guix so I'm not quite sure the best way to go about fixing this. I can also try and test in a fresh VM of the Guix system since my test right now was on my Arch system running Guix package manager on top, if that would be helpful. Thanks in advance!

**Comment by alexfikl** [comment]
@stasvlasov As the original author, do you have any time to look into this? It seems like it's an issue with `tqdm`, which we might have introduced when we removed that as a dependency..

Otherwise, I have no experience with Guix, so if you figure it out.. PRs are very welcome! :heart:

**Comment by JetpackJackson** [comment]
Alright, I'll try that in a few and see if it works!

**Comment by JetpackJackson** [comment]
The previous version works!
