### ISSUE TITLE
Migrate to click for simplicity and maintainability

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#86]
I'm migrating the command line parsing to the great library click

https://github.com/pallets/click

The branch `click` is slowly becoming ready.
@michaelplews I would be interested in knowing what you think about it, I think the code base
is getting much simpler like this, and also what concerns writing scripts, I changed
the `papis-hubation` script in the `click` branch and I think it is much more maintainable now and readable.

**Comment by michaelplews** [comment]
@alejandrogallo I just checked out the branch and I like it. It seems like it will improve handling of options which I already find difficult.

One problem is that I couldn't get `hubation` to honour the config options set. It always defaults to scihub. Perhaps this is a side effect of `click`?

**Comment by alejandrogallo** [comment]
Hi Michael,

I also think it will make the whole thing much simpler, we get rid of a
large Chunk of the code and we can use it too to show people how to write
nice scripts.

About the hubation, so I changed it a little bit because it was a little
bit confusing. I think the configuration options of an external script
shouldnt be on the main code, so right now the hubation configuration gets
declared at the beginning of the code, if you have the latest version
you'll be able to see it. And then I turned hubation into a section with a
command option. So you can set for instance in the configuration file

```
hubation-command = open
```

Etc. You can take a look and we can change the whole thing, it was just
that it would be nice to turn hubation into the main example of a well
written papis script, with configuration options and cli.

**Comment by michaelplews** [comment]
@alejandrogallo I see. I missed that but I will look again.

I agree. It would be nice to make the script writing clear and concise to encourage users to write more scripts. It might also be nice to include a README in the scripts folder, or perhaps a different repo entirely just for scripts, that explains what each script does. Right now it's hard to see what the scripts do without reading through their code.

If there is any help you need refactoring some of the code to work with `click`, please let me know and I'd be more than happy to help.

**Comment by alejandrogallo** [comment]
Click is now working as the version 0.6 of papis was working, INCLUDING the automatic documentation
of the command line
