### ISSUE TITLE
No documents retrieved when using FZF picker

### ISSUE THREAD

**Issue by xmalbertox** [papis/papis#869]
* papis version (`$ papis --version` or commit number):
    + papis-git 0.13.r473.g898e0334-1 (installed from the AUR)
    + fzf 0.53.0 (c4a9ccd6)
    + python 3.12.3

# how to reproduce the issue
Command and output of `papis --log DEBUG open`:

## With FZF picker
```
papis --log DEBUG open
[DEBUG] database.whoosh: Initialized index found for library.
[DEBUG] database.whoosh: Querying database for 'title:*'.
[DEBUG] database.whoosh: Found 478 results: <Top 478 Results for Every('title', boost=1.0) runtime=0.1334660590000567>
[DEBUG] plugin: Creating manager for namespace 'papis.picker'.
[DEBUG] plugin: Creating manager for namespace 'papis.format'.
[DEBUG] format: Using 'python' formatter.
[WARNING] commands.open: No documents retrieved
```

## With default picker

```
papis --log DEBUG open
[DEBUG] database.whoosh: Initialized index found for library.
[DEBUG] database.whoosh: Querying database for 'title:*'.
[DEBUG] database.whoosh: Found 478 results: <Top 478 Results for Every('title', boost=1.0) runtime=0.12472776699905808>
[DEBUG] plugin: Creating manager for namespace 'papis.picker'.
[DEBUG] tui.widgets.list: Processing 478 options.
[DEBUG] plugin: Creating manager for namespace 'papis.format'.
[DEBUG] format: Using 'python' formatter.
[DEBUG] tui.widgets.list: Processing headers.
[DEBUG] tui.widgets.list: Got 478 headers.
[DEBUG] tui.widgets.list: Processing matchers.
[DEBUG] tui.widgets.list: Got 478 matchers.
[DEBUG] tui.widgets.list: Created items in 1.6 ms.
[DEBUG] utils: Running command: '['rifle', '/home/malberto/Documents/Work/References/a09bfbac71f4e0492b28860b48b216af-kardar-mehran-and-p/kardardynamic-scaling1986phys.pdf']'.
[DEBUG] utils: Not waiting for process to finish.

```

# Final remarks

It was working normally until recently, I noticed yesterday that I could not open any documents, after some investigation I narrowed it down to only happening when using the FZF picker.

The archlinux fzf package was updated last week (June 6), it is possible that is something caused by the update since I usually update my work computer on monday mornings.

**Comment by jghauser** [comment]
I just checked on my NixOS unstable machine (which also has the latest 0.53.0 fzf) and it seems to work :thinking:

**Comment by alexfikl** [comment]
I can confirm that it doesn't work on Arch. Will investigate over the weekend if no one beats me too it! :grin: 

Any help is welcome though! I'm not very familiar with the many many fzf options :(

**Comment by alexfikl** [comment]
Seems like this is the problem:
https://github.com/junegunn/fzf/discussions/3844
i.e. replacing the `execute(..)` statements in our code with `become(..)` makes at least `papis open` work again for me. Not sure how to make that a bit backwards compatible though. Any idea when the `become` function was introduced in fzf?

**Comment by jghauser** [comment]
Just wanted to say that this error definitely also occurs on NixOs. I had some custom fzf commands configured that were unaffected and that made me think everything was working normally.

**Comment by xmalbertox** [comment]
Thank you @alexfikl  for narrowing down the source of the bug. I will try and build a local version and see if the proposed fix works.

**Comment by alexfikl** [comment]
@xmalbertox Thank you for checking! 

There's a PR #876 that uses `become` and should fix this (works for me™). Any additional testing is very welcome.

**Comment by tuurep** [comment]
Thanks, I really rely on the fzf picker :)

Can confirm PR fixes it for me, at least for what I usually do which is:

* `papis open`
* `papis edit -n`

lmk if I should test anything more specific.

**Comment by alexfikl** [comment]
Ok then, I'll go ahead and merge #876. Feel free to re-open this if some issues persist!

Thanks again for the testing and help :heart:

**Comment by Panadestein** [comment]
@alexfikl any chance this fix will make it to `nixos-unstable` any time soon? I see that the last release is a year old, how do NixOS users typically use this package, with an overlay or a flake instead of the channel?

**Comment by alexfikl** [comment]
Glad to hear it works well for you! :grin:

**Comment by apraga** [comment]
@alexfikl Today, I have the same issue, even though my config didn't change. FZF wasn't updated either

- papis  0.13 (nix) and 6137701eeb7108e46afc2896936888aa4927feee
- fzn 0.54.3 (9e92b6f)
- tested on nushell and bash
- default config with a fresh database

I feel it's an issue on my side but hasn't been able to pinpoint it. Could you confirm the fzf picker still work?It looks very much like #918 but my config did not change...
869I'm having trouble to pinpoint the issue as my config did not changed. FZF was not updated either
I use the default config with fzf with the default cache. It has the same issue across shells (found on nushell but also occurs in Bash).
I

`papis --log DEBUG list` and pressing `Enter` :
```
[DEBUG] database.cache: Querying database for '.'.
[DEBUG] database.cache: Getting documents from cache at '/home/alex/.cache/papis/database/f77645e6646798f4d4eb2b2cce65b0a5-papers2'.
[DEBUG] database.cache: Loaded 2 documents.
[DEBUG] plugin: Creating manager for namespace 'papis.picker'.
[DEBUG] plugin: Creating manager for namespace 'papis.format'.
[DEBUG] format: Using 'python' formater.
[WARNING] commands.list: No documents retrieved
```

**Comment by apraga** [comment]
Update : tested on another machine with nushell and latest papis : fzf works (so I'm a bit stumped).

**Comment by alexfikl** [comment]
> Update : tested on another machine with nushell and latest papis : fzf works (so I'm a bit stumped).

I'm on zsh with fzf 0.55.0 and it seems to work just fine with all the commands I tried. I'm not sure what could be wrong in your environment. Could you open a new issue? It doesn't sound like you're having the same problem as in this issue.

Maybe it's worth adding some more debug logging messages into the fzf picker to figure this out?
