### ISSUE TITLE
Scripts repository

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#87]
@michaelplews 
You're right, I think it would be wise to have a repository with contributed scripts,
and maybe also a `scripts` command to automatically install them, like a very simple
package manager. What do you think? Do you have any special idea for it?
I thougt about a repository with folder per script and inside there should be a simple setup.py
file.

**Comment by alejandrogallo** [comment]
I would say something like that, very simple, and it also can install all kinds of scripts

https://github.com/papis/scripts/tree/master/papis-scihub

So you could install it with 

```
pip3 install papis-scihub
```

Which I think is neat.

**Comment by michaelplews** [comment]
Awesome! and papis recognizes the scripts if they are only installed with `pip`?

**Comment by alejandrogallo** [comment]
Yes, they work, since they are set in path by the setup.py script, so the command system of papis
recognises them as long as they are called `papis-{somecommand}`.

I'm also looking at travis ci in order to be able to update automatically also the scripts into
pypi, so for instance if you push to the scripts directory, the would be updated automatically
too on pypi, it's nice because then we would not need a package manager at all, since pypi does all
the heavy lifting. And you can install all sorts of scripts, `papis-scihub` is bash, which by the way
it would be nice to port it to python in a clean and readable way, if you're interested... :)

I'm currently cleaning up in the click branch and I added coverage support for papis, so that we can see which parts of the code are not tested, right now 60 % of papis is tested, and we should strive
towards 90 %

**Comment by alejandrogallo** [comment]
Creation of papis/scripts repository closes this
