### ISSUE TITLE
Escaping Metacharacters (&) in bibtex export

### ISSUE THREAD

**Issue by supersambo** [papis/papis#870]
I sometimes run into problems when compiling latex documents with .bib files exported from papis. I get errors due to non escaped metacharacters (specifically the `&`).  A relatively easy fix is to escape these characters in the corresponding `yaml` file. However, I think it would be a better aproach to escape these characters when bibtex is exported.

**Comment by alexfikl** [comment]
These should already be escaped if you set `bibtex-unicode = false` in your config. We're using `string_to_latex` from `bibtexparser` to do the conversion, so hopefully it works well enough.
https://github.com/sciunto-org/python-bibtexparser/blob/f4fd17edd3258949e6ffed41c058434061bbd3f9/bibtexparser/latexenc.py#L18

If you're looking for a quick fix for some documents, there's also
https://papis.readthedocs.io/en/latest/bibtex.html#override-keys

Did you mean that we should escape just `&` and some other characters that aren't allowed? Right now setting `bibtex-unicode = false` will also convert any unicode characters, e.g. `é` to `{\'e}`. I vaguely recall we wanted to do that at some point, but couldn't find a list of symbols that aren't allowed in pure BibTeX. Do you happen to know if there is such a list?

**Comment by supersambo** [comment]
Sorry, I was not aware of that option! I changed this setting and everything is working perfectly. Don't know about were to find such a list either. My issue was much more trivial :)
