### ISSUE TITLE
Quick guide references an non-existant command

### ISSUE THREAD

**Issue by erooke** [papis/papis#889]
The [quick start guide](https://papis.readthedocs.io/en/latest/quick_guide.html) references a `papis init` command which does not seem to work.

``` 
> papis --version
papis, version 0.13
```

```
> papis init
Command 'init' is unknown!
Usage: papis [OPTIONS] COMMAND [ARGS]...

Error: No such command 'init'.
```

**Comment by alexfikl** [comment]
Hi! By default, the docs direct you to the latest version, which is unreleased at the moment.

You can go to the "stable" version in the menu in the lower left corner or here:
https://papis.readthedocs.io/en/stable
Unfortunately, version 0.13 doesn't yet have the `papis init` command, so you'll either have to wait until the next release or use the development (git) version of Papis.

**Comment by erooke** [comment]
Ah, I kind of figured it might be something like that. For what its worth, I poked around looking for an alternative version of the docs. None of my guessed urls worked nor could I find any other links. It might be worth adding a link to the stable docs to the readme or mention this distinction in the docs somewhere; this makes figuring out how to use Papis as a new user harder.

**Comment by alexfikl** [comment]
@erooke That's a good idea! #893 adds a little banner warning that this is the dev version, so hopefully that will clear things up.
