### ISSUE TITLE
add-name in "first-author"-"year" format?

### ISSUE THREAD

**Issue by sanjayankur31** [papis/papis#90]
Hi,

Is it possible to mention the `add-name` config to create folders in the `author-year` format?

I tried this: `add-name = {doc[author_list][0]}{doc[year]}`, but that errors out with a `IndexError: string index out of range` message on import. It's used in the `ref-format` setting and works, but not in the `add-name` setting.

Thanks for papis---it's awesome!

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn), https://github.com/alejandrogallo/papis/issues/39 (file-name option and adding files with incomplete metadata), https://github.com/alejandrogallo/papis/issues/38 (Multiple authors in bibtex), and https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion).

**Comment by sanjayankur31** [comment]
A similar setting doesn't work in the `file-name` setting too. This is papis 0.6.

**Comment by alejandrogallo** [comment]
Hi @sanjayankur31 
Have you tried simply
```
add-name = {doc[author]}{doc[year]}
```

The author list will not be always defined, and therefore if you try to get the 0th component
of something that does not exist then you get an `IndexError`.

Thanks for your interest! Please keep on posting doubts and issues ;)

**Comment by sanjayankur31** [comment]
Hello!

Thanks for your reply. I did try that, but that uses a concatenated list of all authors, and I don't want that---it's far too long, and since our bibliography keys (and citations) are in the "FirstAuthor-Year" style, it just feels more consistent :)

I got one or two "file name too long" errors when I used "Author-Title" too. Maybe a check to truncate the combined string to 70 (or another suitable number of) characters should also be added.

Cheers,
Ankur

**Comment by alejandrogallo** [comment]
Hi @sanjayankur31 
the format is a python format

https://docs.python.org/2/library/string.html#format-string-syntax

so maybe you can also trim it in the format

```
add-name = {doc[author]:.20}-{doc[year]}
```

this will cut down the author field to 20 characters.
I think this might work for you, would it?

Cheers

**Comment by sanjayankur31** [comment]
Yeh, it'll certainly help. Thanks :)
