### ISSUE TITLE
`multiple-authors-format` setting does not respect formatter choice

### ISSUE THREAD

**Issue by AlexBocken** [papis/papis#905]
* papis version 0.13.r498.g95e0b545

Hi there! Many thanks for the project, I've been enjoying the use of papis greatly so far.
While creating more complicated formatting rules I've noticed how the setting `multiple-authors-format` does not appear to respect the formatter choice. It seems to always use the default python formatter.

# how to reproduce the issue

Papis needs to use the jinja2 formatter and set a custom  multiple-authors-format. Hence in your `~/.config/papis/config` it should include something like:

```
formatter = jinja2
mutliple-authors-format = {{au.family}}, {{au.given}}
```

Run any command which uses this setting. (For example `papis add `)

This will print out an author key of `{au.family}, {au.given} and {au.family}, {au.given}` etc. not the actual author names

The following settings create the expected output:
```
formatter = jinja2
multiple-authors-format = {au[family]}, {au[given]}
```

(I.e. not changing the `multiple-authors-format` setting or using python formatting)

# Expected behaviour

Instead of using the python formatter for this setting, use the set one in the config, in this case jinja2

Let me know if you need further help from my side. I think the issue is straightforward. Probably it was forgotten to add the formatter check to the handling for this settting.

**Comment by alexfikl** [comment]
Nice catch! 

#906 should fix this (assuming CI passes). Can you test that it fixes things for you?

**Comment by AlexBocken** [comment]
Thanks for the quick PR! Looking forward to the merge! Will close issue once merged.

**Comment by alexfikl** [comment]
> Thanks for the quick PR! Looking forward to the merge! Will close issue once merged.

Went ahead and merged that fix! Feel free to re-open if the issue persists :grin:
