### ISSUE TITLE
No result with whoosh backend

### ISSUE THREAD

**Issue by apraga** [papis/papis#909]
* papis version (`$ papis --version` or commit number): 5b6e339562cd06f2cee
Also tested with nixpgks.

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
❯ papis --log DEBUG open f
Error while loading entrypoint 'EntryPoint(name='isbn', value='papis.isbn:Importer', group='papis.importer')': No module named 'pkg_resources'.
Error while loading entrypoint 'EntryPoint(name='isbn', value='papis.isbn:explorer', group='papis.explorer')': No module named 'pkg_resources'.
[DEBUG] database.whoosh: Initialized index found for library.
[DEBUG] database.whoosh: Querying database for 'f'.
[DEBUG] database.whoosh: Found 0 results: <Top 0 Results for <_NullQuery> runtime=1.306000012846198e-05>
[DEBUG] plugin: Creating manager for namespace 'papis.picker'.
[WARNING] commands.open: No documents retrieved
```

My papis config 
```
[settings]
default-library = papers
notes-name = notes.norg
database-backend = whoosh

[papers]
dir = ~/papers
```

I do have  ~/.cache/papis/database/whoosh/e0a36b953f4c1d28665a2b9cfb7fe3fb-papers/.
I installed from source and `pip install`'d whoosh both in the virtual environment  and globally. Any idea ? Thanks

**Comment by alexfikl** [comment]
Not very familiar with the `whoosh` syntax, but this seems to work
```
papis open 'f*'
```
i.e. it needs a wildcard `*` otherwise it just looks for the full word and probably didn't find a separated "f" in your library.

**Comment by apraga** [comment]
Indeed, thanks !
