### ISSUE TITLE
vim/vimtex integration

### ISSUE THREAD

**Issue by sanjayankur31** [papis/papis#91]
Is there a suggested way of integrating papis with vim, such as using the vimtex plugin? vimtex supports completion from a bibtex file (using YCM I think, and so do a bunch of other plug-ins), but from what I see of papis' functioning, that'll require one to export the bibliography each time after making changes which isn't ideal.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by michal-h21** [comment]
@alejandrogallo I am glad it works. I think repo under papis would be best, to keep things organized. I can then clean it a little, make things like `\cite` command configurable.

**Comment by alejandrogallo** [comment]
It's great. For instance I change it like this


```

command! -bang -nargs=* Papis
      \ call fzf#run(fzf#wrap({'source': 'papis list <args> --format "{doc[author]}: {doc[title]} @{doc[ref]}"', 'sink*': function('<sid>handler'), 'options': '--multi --expect=ctrl-y --print-query'}))


```

where I added the `<args>` and changed the `@{doc[id]}` by `@{doc[ref]}`.
What would you like the repo be called ? `papis/vim`, `papis/papis-vim`, `papis/vimtex` ?

**Comment by michal-h21** [comment]
I think `papis-vim` is best, the other names would infere with other packages when installed using Vim plugin managers.

**Comment by alejandrogallo** [comment]
I agree, I already created it:

  https://github.com/papis/papis-vim

feel free to do as you it's best.

**Comment by michal-h21** [comment]
Thanks! I've added the code and a basic README file. It needs some polishing, I am not really good in writing documentation :/

**Comment by alejandrogallo** [comment]
Awesome, thanks, I'll be writing also a couple of things, don't worry!
