### ISSUE TITLE
FZF picker does not open notes

### ISSUE THREAD

**Issue by apraga** [papis/papis#918]
* papis version (`$ papis --version` or commit number): 9b270726e271

# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
Minimal reproducible example
```
papis add --from doi 10.1145/30355
papis add --from doi 10.1090/noti963 
 echo "a" > what-is-new-in-latex-vi.-latex-on-an-ipad.-empire/notes.norg
```
Then `ctrl-q` on this entry show
```❯ papis --log INFO edit *'
[WARNING] commands.edit: No documents retrieved
```
Using the default picker works.
Configuration
```
[settings]
default-library = papers
notes-name = notes.norg
add-folder-name = ``{doc[title]}``
doctor-key-type-check-keys = ['year:int', 'month:int', 'files:list', 'notes:str', 'author_list:list', 'doi:str', 'ref:str', 'isbn:str', 'author:str', 'journal:str', 'note:str', 'type:str', 'publisher:str', 'title:str', 'shorttitle:str', 'tags:list']
database-backend = whoosh
picktool = fzf

[papers]
dir = ~/papers2
```
Thanks !

**Comment by alexfikl** [comment]
That picker seems to currently just have an edit and open commands, e.g.
https://github.com/papis/papis/blob/d5244da73c015a0a0f9958361a01a6255514138e/papis/fzf.py#L72-L82
Should be pretty easy to add another one to the list.
