### ISSUE TITLE
papis-python-rofi

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#92]
I updated from Ubuntu 16.04 to 18.04 and I am now having dependency issues. I tried reinstalling, and ran into this.

```
Collecting papis-python-rofi>=1.0.1 (from papis)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8729dfd7b8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/papis-python-rofi/
```

Any ideas?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/43 (papis-python-rofi wrong name), https://github.com/papis/papis/issues/41 (Webapplication for papis), https://github.com/papis/papis/issues/64 (Rofi GUI doesn't honour 'editor' option in .config/papis/config), https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError), and https://github.com/alejandrogallo/papis/issues/6 (gui --rofi crashing on delete).

**Comment by michaelplews** [comment]
It was my connection. My bad
