### ISSUE TITLE
papis open not working on symlinked documents

### ISSUE THREAD

**Issue by Ottermanns** [papis/papis#921]
* papis version: 0.13

Hello. I can import from zotero with "papis-zotero" using symlinks to pdfs (thanks to alexfikl). With "papis serve" I can see the linked pdfs and open them. But when I use "papis open" the linked documents are not available, although the symlinks are available together with the yaml in the library directory. Any help is appreciated.

**Comment by Ottermanns** [comment]
Figured it out. It was an xdg-config issue: "xdg-mime default xpdf.desktop application/pdf" -> fixed. Issue can be closed.

**Comment by alexfikl** [comment]
Thanks for following up on this!

xref: https://github.com/papis/papis-zotero/issues/52
