### ISSUE TITLE
Why `au` in `multiple-authors-format`?

### ISSUE THREAD

**Issue by jghauser** [papis/papis#923]
I recently had to adjust the `multiple-authors-format` option as I use `jinja2` for formatting. This works well, but I'm wondering why instead of `author` or `author_list`, it requires `au`: e.g. `"multiple-authors-format": '{{au["family"]}}, {{au["given"]}}'` (this is in my `config.py`). It's not a big deal, but given that this is a user-facing option now, it might be nice to have it be consistent with other things in Papis (if there's not some reason for it's needed this way).

**Comment by alexfikl** [comment]
Hm, that's kind of "always been there". 

I think it's just a shorthand: most formats take a `doc`, the mark ones take a `mark`, this takes an `au`. Would `author` be clearer?

**Comment by jghauser** [comment]
Yeah, I thought `author` (or `author_list`) would be clearer, but now I'm not so sure anymore. Cause writing something like `au["family"]` (as I have in my config) at least makes it clear that this is not an instance of getting the value at `author["family"]` (or `author_list["family"]`). It is somewhat confusing, but maybe for the better haha
