### ISSUE TITLE
Support references for update command

### ISSUE THREAD

**Issue by apraga** [papis/papis#928]
A suggestion rather than an issue. Currently, `update` does not allow to update all references according to a new naming scheme.
My current "hack" is to removet the `ref` field from all yaml and use `papis doctor` to add new references.

It would be cool to have `update` do that :)

**Comment by alexfikl** [comment]
```
papers update --set ref 'New{doc[year]}' --all <QUERY>
```
works for me, i.e. it changes all the refs to the expected value. What version of Papis are you on? This was just fixed on the git version, I'm afraid, not 0.13.

**Comment by apraga** [comment]
Ha, thanks. One more thing to add to the doc then :)
