### ISSUE TITLE
Compatibility Issue with Python 3.13 - Missing Modules (cgi and typing.re)

### ISSUE THREAD

**Issue by yamaguchiraf** [papis/papis#929]
* papis, version 0.13

# how to reproduce the issue
Hello,

I'm encountering compatibility issues when running papis on Python 3.13. It appears that papis depends on modules that have been deprecated or removed in Python 3.13, resulting in the following errors:

```python
Error while loading entrypoint 'EntryPoint(name='serve', value='papis.commands.serve:cli', group='papis.command')': No module named 'cgi'.
[ERROR] plugin: Error while loading entrypoint 'EntryPoint(name='fzf', value='papis.fzf:Picker', group='papis.picker')': No module named 'typing.re'; 'typing' is not a package.
```

**Comment by alexfikl** [comment]
I'm afraid version 0.13 is not compatible with Python 3.13. 

This was fixed in the development version in #864 and is awaiting a release.
