### ISSUE TITLE
DOAI integration

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#93]
[DOAI.io](http://doai.io) is a doi resolver that returns a pdf of the article when legally freely available elsewhere. 

It would be great to be able to run requests through doai, as it automatically redirect to `doi.org/YOUR_DOI` when another version is not available.

See this example:

[This redirects to a pdf uploaded through ResearchGate.net](http://doai.io/10.1139/f92-220)

[This is the same doi as above, but done through doi.org](http://doi.org/10.1139/f92-220)

[This link has no free version, so it redirects to the original doi](http://doai.io/10.1021/nn4005022)

It is made by the same people that make [Unpaywall](http://unpaywall.org/), which I would also recommend

@alejandrogallo what are your thoughts on this?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/91 (vim/vimtex integration).

**Comment by alejandrogallo** [comment]
Hi Michael,

**Comment by michaelplews** [comment]
I believe it always redirects you to a pdf if one is available. Otherwise, it redirects through `dx.doi.org/`.

I was thinking about writing a python module for the Unpaywall [REST API ](http://unpaywall.org/products/api) which we could implement. It returns a JSON structure for any DOI, which we could then search for if a pdf is freely available or not.

Example:

[No PDF available](https://api.unpaywall.org/v2/10.1021/nn4005022?email=YOUR_EMAIL)
[PDF available](https://api.unpaywall.org/v2/10.1038/nature12373?email=YOUR_EMAIL)

Where 'PDF available' has attribute `best_oa_location` with information for the version available through open access.

I think writing a separate python module would allow better versatility for other users, as well as easy implementation for us.

**Comment by alejandrogallo** [comment]
Let's do this, it sounds great, do you want to create the python package in
your github or in papis organization?

**Comment by michaelplews** [comment]
I think it would be best to keep papis and the python package as separate as possible, to encourage others to use it also as a standalone package, rather than be tempted to integrate it in the papis code. [I created a repo](https://github.com/michaelplews/python-unpaywall) and will start work on it. 

@alejandrogallo please feel free to contribute. It would be very useful to have you looking over the code also; I have never built a python package before!

**Comment by alejandrogallo** [comment]
Wonderful, I'll be happy to contribute.
Also maybe you find my forked cookiecutter for python projects useful
https://github.com/alejandrogallo/cookiecutter-python

you just do

```
pip3 install cookiecutter
git clone https://github.com/alejandrogallo/cookiecutter-python
cookiecutter cookiecutter-python
```

**Comment by alejandrogallo** [comment]
I wrote tests for some downloaders and refactored a little bit the code.
Now the tests are actually downloading papers from some journals, if they're oopen access
it works, if not, it doesn't but papis does not blow up.

So actually now papis is ready for doai, but whenever you're ready, no rush.

**Comment by alejandrogallo** [comment]
We should review this with the new downloaders plugin system.

**Comment by alejandrogallo** [comment]
This is quite old now, and the downloaders have been completely renewd, I'll close this for the time being.
