### ISSUE TITLE
hubation deprecation

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#94]
@michaelplews 

I just updated the explore command, now you could do

```
papis explore citations <some query> export --yaml cits.yaml pick cmd 'papis scihub {doc[doi]}' 
```

which I think is much more flexible, check it out if you've got time!
Maybe you've got some improvements in mind.

**Comment by michaelplews** [comment]
@alejandrogallo after playing around with this I can see it being much more flexible. I like it a lot.

I think this would play well with the idea of aliases. 

For example:

```
papis explore citations <some query> export --yaml cits.yaml pick cmd 'firefox {doc[url]}' 
```

becomes
```
papis hubation <some query>
```

Unfortunately, bash aliases do not allow paramaters, so this may have to be something we implement directly in papis. But it would be cool to allow users to dynamically create their own aliases for complex functions such as this.

What would be even cooler is implementing these in a separate file that would allow users to submit their own aliases that they have constructed through github. We could then have a common alias file (from the community), as well as a private alias file. The aliases files would just need to be listed in the config file.

Just an idea.

**Comment by alejandrogallo** [comment]
Hi Michael, thank you for taking the time for this ! It is indeed a good idea I think, however
you can actually do it in bash, or with scripts, for instance you could define a bash function

```
alias popen='papis open'
hubation() { papis explore citations $1 export --yaml /tmp/cits.yaml pick cmd 'firefox {doc[url]}'; }
```
and hit `hubation einstein `,
or just write the short script `papis-hubation`

```
#!/usr/bin/bash

papis explore citations $1 export --yaml /tmp/cits.yaml pick cmd 'firefox {doc[url]}'
```

and then you'd be able to do `papis hubation einstein` etc...
