### ISSUE TITLE
CI: Windows build has flaky version parsing

### ISSUE THREAD

**Issue by alexfikl** [papis/papis#940]
It currently does something like this
```
git describe --tags --dirty \
	| awk -F '-' '{ printf "%s.dev%s+%s\n", substr($1, 2), $2, $3 }'
```
because it expects a git output like `v0.13-533-gab7488cd`. 

* [ ] This breaks if the current commit is the last tag (for which we just get `v0.13`).
* [ ] Also breaks if the version is something like `0.14rc1`, which is allowed by Python but not for MSI versions.

It would be nicer to make this more robust. Example failed workflow
https://github.com/papis/papis/actions/runs/11747502229/job/32729554402

cc @kiike

**Comment by kiike** [comment]
Do you think a Python script would make sense to both avoid awk and reduce context switching?

**Comment by alexfikl** [comment]
Yeah, it seems like it would be quite complicated to do the parsing in the shell :\
