### ISSUE TITLE
Feature request: Mark tests that need git so they can be disabled on non-git setups

### ISSUE THREAD

**Issue by hseg** [papis/papis#944]
* papis version (`$ papis --version` or commit number): 0.14

# how to reproduce the issue
On a system where `git` isn't installed (for example, a clean chroot on a build system containing the minimal `papis` dependencies), the following tests fail due to its absence
```
FAILED tests/commands/test_git.py::test_git_cli - FileNotFoundError: Command ...
ERROR tests/commands/test_add.py::test_add_run - FileNotFoundError: Command n...
ERROR tests/commands/test_rm.py::test_rm_files_run - FileNotFoundError: Comma...
```

Alternatively, please document that `git` is required to be installed.

**Comment by alexfikl** [comment]
#945 should add a way to workaround this.

Any idea how to add `git` as an optional dependency? Maybe we can depend on something like `pygit2` and use that instead of calling the `git` executable directly..

**Comment by hseg** [comment]
I'd think noting that "Papis ships with integrations for git" in the README would be clear enough. Or are you referring to documenting this in `pyproject.toml`?

**Comment by alexfikl** [comment]
> I'd think noting that "Papis ships with integrations for git" in the README would be clear enough. Or are you referring to documenting this in `pyproject.toml`?

Yeah, it should be documented together with the other dependencies..

**Comment by hseg** [comment]
Hrm. Guidance I'm getting from `#python` is that `pyproject.toml` is for pip-specific dependencies -- perhaps add it to https://github.com/papis/papis/blob/main/PACKAGING.md#dependencies ?

**Comment by alexfikl** [comment]
> Hrm. Guidance I'm getting from `#python` is that `pyproject.toml` is for pip-specific dependencies -- perhaps add it to [`main`/PACKAGING.md#dependencies](https://github.com/papis/papis/blob/main/PACKAGING.md?rgh-link-date=2024-11-10T19%3A39%3A26Z#dependencies)?

Yeah, that's probably a good place for it!
