### ISSUE TITLE
papis and ipython require incompatible versions of prompt-toolkit on conda

### ISSUE THREAD

**Issue by bluehood** [papis/papis#99]
To reproduce:

```bash
$ conda create -n papis python=3 ipython pip
$ conda activate papis
$ pip install papis
...
ipython 6.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you will have prompt-toolkit 2.0.4 which is incompatible.
Found existing installation: prompt-toolkit 1.0.15
  Uninstalling prompt-toolkit-1.0.15:
    Successfully uninstalled prompt-toolkit-1.0.15
Successfully installed prompt-toolkit-2.0.4 
...
$ papis # OK
$ ipython
Traceback (most recent call last):
  File "/home/eguiraud/Tools/miniconda2/envs/papis/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

Of course the workaround is to have separate environments for papis and ipython but that is very annoying, I was wondering whether there is a better solution.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/92 (papis-python-rofi).

**Comment by alejandrogallo** [comment]
I know, it is very annoying, I have been thinking for a while how to resolve the problem, 
but sadly I haven't been able to find a solution.

I had this problem also with other libraries, I'm quite disenchanted with PyPi and pip for that reason actually, either I don't know the dependency system well enough or it's very limited.

For instance I also thought about packaging all papis dependencies with papis, and do
```
import papis.deps.prompt_toolkit as prompt_toolkit
```
to import them, however to do this you would also have to package de dependencies of the dependencies.

And I suppose that if even projects like ipython do not do this, it means to me that there is no
obvious way of doing it.

**Comment by bluehood** [comment]
uhm, I see now that the problem is actually worse than I thought: even with just pip, with no conda involved, you can't have both papis and ipython installed: `pip install ipython papis` gives you a broken papis, while `pip install papis ipython` gives you a broken ipython.

in my opinion conflicting with ipython, of all packages, is very bad.
do you think it would be possible at all to run papis with `prompt-toolkit` version 1?

**Comment by alejandrogallo** [comment]
You're right, and I think it would probably work with version one, and if not we should make it work... I'll look into it shortly

**Comment by UmutAlihan** [comment]
updating pip to new version resolved the issue for me

I read that problem caused by the api structure change on the prompt-toolkit 2.*.* 

try:
`pip install -U pip `

**Comment by bluehood** [comment]
i can't reproduce the issue anymore. i did not dive into check who changed what dependency or default package version, but it seems 
```
$ conda create -n papis python=3 ipython pip
$ conda activate papis
$ pip install papis
```
works fine now.

**Comment by alejandrogallo** [comment]
Really solved now, not having a pypi dependence for prompt_toolkit anymore
